src/components/patch/Patch.less, src/components/patch/Patch.tsx, src/components/patch/PatchContainer.test.tsx, src/components/patch/PatchContainer.tsx
This set of changes includes the implementation of search by patch description, some element styling, and a test to confirm that search works as expected.
=> EVG-6308: Add searching of patches

package-lock.json, package.json, src/components/app/App.tsx, src/models/client_config.ts
If you want to see this for yourself, you can manually add some runtime error, hit it, and then visit https://app.bugsnag.com/mongodb/evergreen/errors to see it
=> EVG-6480 add bugsnag

src/components/task/TaskPanel.less, src/components/task/TaskPanel.test.tsx, src/components/task/TaskPanel.tsx
One tiny thing left to do on this ticket- a few of the fields I use here are cast from Time to Date because they are defined as being the Time type in the model for APITasks. They use the Time type because that's how the class was defining them in Go. Should I update the type in evergreen.js or stick to using this cast?
=> EVG-6550: add task details to build view

package-lock.json, package.json, src/components/app/App.tsx, src/components/navbar/DevMenu.tsx, src/components/patch/PatchContainer.test.tsx, src/components/patch/PatchContainer.tsx, src/rest/evergreen_mock.ts, src/rest/interface.ts, src/types/index.ts
Reverts evergreen-ci/spruce#29 for now
=> Revert "EVG-6595: render project patches if specified in pathname"

package-lock.json, package.json, src/components/app/App.tsx, src/components/navbar/DevMenu.tsx, src/components/patch/PatchContainer.test.tsx, src/components/patch/PatchContainer.tsx, src/rest/evergreen_mock.ts, src/rest/interface.ts, src/types/index.ts
Reverts evergreen-ci/spruce#31
=> Revert "Revert "EVG-6595: render project patches if specified in pathname""

config/webpack.config.prod.js
these code changes load mjs files so we can use ApolloClient
=> EVG-7158: load mjs modules for prod build

LICENSE, README.md
Add the Apache license to the project to officially mark it as OS
=> Add Apache2.0 license to project

src/App.tsx, src/components/Navbar/index.tsx, src/context/auth.tsx
To see the rest of the user stories for the projects dropdown see the New UI Google Doc [here](https://docs.google.com/document/d/1rxWptM-e3w8t4254KuW-jJvNCdcsU2MXX_iQViF9qlg/edit?ts=5e398dbc#heading=h.m8k76qa75acs)
**The colors of the border will all be changed to fir Mongo. Doing so tho requires modifying webpack config. How we are going to accomplish this with CRA is TBD.**
**Ben signs off on this UI**
=> EVG-7200: Select component with search input

src/components/Navbar/index.tsx, src/components/ProjectSelect/index.tsx
No code changes. Project select is its own component.
=> ProjectSelect is its own component

package-lock.json, package.json, src/gql/GQLWrapper.tsx
https://jira.mongodb.org/browse/EVG-7508
=> EVG-7508: timeout gql requests after 60 seconds

.evergreen.yml
https://jira.mongodb.org/browse/EVG-7488
=> EVG-7488: use wait-on to fix flakey auth tests

cypress/integration/patch-route.js, package-lock.json, package.json, src/components/Breadcrumb/index.tsx, src/components/Typography/index.ts, src/components/styles/index.ts, src/pages/Patch.tsx, src/pages/patch/BuildVariants.tsx, src/pages/patch/buildVariants/TaskSquare.tsx
https://mongodb.invisionapp.com/share/S7W848CN3GC#/screens/408295791
=> EVG-7514: patch build variants UI

cypress/integration/patch/patch-route/tasks-filters.js, src/components/styles/filters.tsx, src/components/styles/index.ts, src/gql/queries/get-patch-tasks.ts, src/hooks/index.ts, src/hooks/useFilterInputChangeHandler.ts, src/pages/patch/patchTabs/Tasks.tsx, src/pages/patch/patchTabs/tasks/TaskFilters.tsx, src/pages/task/TestsTable.tsx
https://jira.mongodb.org/browse/EVG-7520
- updates the VARIANT url param when user types into input
- removes VARIANT url param if user deletes all text from input
=> EVG-7520: variant input field updates variant url param onChange

src/pages/patch/patchTabs/tasks/TasksTable.tsx
=> EVG-7667: Table sort function should push statuses as comma separated values

src/components/TreeSelect.tsx, src/pages/task/TestsTable.tsx, src/pages/task/testsTable/StatusSelector.tsx
https://jira.mongodb.org/browse/EVG-7691
=> EVG-7891: Make TreeSelect resizable

src/gql/generated/types.ts, src/gql/queries/my-patches.ts
https://jira.mongodb.org/browse/EVG-7920
This PR makes codegen possible. e2e tests are not affected.
=> EVG-7920: Update UserPatches query fields to reflect schema changes

cypress/integration/commit_queue.ts, src/components/CodeChangesTable/index.tsx, src/gql/generated/types.ts, src/gql/mutations/remove-patch-from-commit-queue.ts, src/pages/CommitQueue.tsx, src/pages/commitqueue/CommitQueueCard.tsx
Tests wont pass until the corresponding pr in evergreen is merged so i can get some data. 
https://github.com/evergreen-ci/evergreen/pull/3540
Also realized there also isn't an empty state for the commit queue. Lara is working on some designs
=> EVG-7909 Wire up remove patch from commit queue mutation

cypress/integration/page_tabs.ts, src/gql/generated/types.ts, src/gql/queries/get-task.ts, src/pages/Task.tsx
https://jira.mongodb.org/browse/EVG-7557
=> EVG-7557: include file count in Files Tab

src/pages/task/FilesTables.tsx, src/pages/task/logs/LogTypes.tsx, src/pages/task/testsTable/TestsTableCore.tsx
https://jira.mongodb.org/browse/EVG-7608
This pr adds loading skeletons for all the tabs in the Task page
=> EVG-7608: Task page tabs loading skeletons

src/components/Button/index.tsx, src/pages/configurePatch/configurePatchCore/ConfigureTasks.tsx
Adds some tasty features to the leafygreen button, like showing a loading indicator
=> EVG-7947: shared button component with loading icon

src/gql/queries/get-user-settings.ts, src/pages/Preferences.tsx, src/pages/preferences/NotificationField.tsx, src/pages/preferences/NotificationsTab.tsx, src/pages/preferences/PreferencesTabs.tsx, src/pages/preferences/fieldMaps.ts
Created the notifications tab of the user preferences page. Cypress tests will follow once the mutations are created and everything is wired up and all 3 pages are made.
=> EVG-7994 Add the notification tab

package.json, src/App.tsx
https://jira.mongodb.org/browse/EVG-7311
=> EVG-7311: only import required antd css

package-lock.json, package.json, src/components/Accordian/index.tsx, src/constants/externalResources.ts, src/pages/preferences/PreferencesTabs.tsx, src/pages/preferences/preferencesTabs/CliTab.tsx, src/pages/preferences/preferencesTabs/cliTab/AuthenticationCard.tsx, src/pages/preferences/preferencesTabs/cliTab/ConfirmationCard.tsx, src/pages/preferences/preferencesTabs/cliTab/DownloadCard.tsx, src/pages/preferences/preferencesTabs/cliTab/NodeList.tsx, src/pages/preferences/preferencesTabs/cliTab/VerifyCard.tsx, src/pages/preferences/preferencesTabs/cliTab/index.ts, src/pages/preferences/preferencesTabs/cliTab/nodeList/Node.tsx, src/stories/2-NodeList.stories.js
Still need to create mutations and queries for fetching the contents of the authentication file. Will do that in a follow up pr as well as creating tests for that functionality.
=> EVG-8018 Add CLI tab

cypress/integration/my_patches.ts, src/pages/MyPatches.tsx, src/pages/patch/patchTabs/Tasks.tsx, src/pages/task/testsTable/TestsTableCore.tsx, src/types/patch.ts, src/utils/url/index.ts
https://jira.mongodb.org/browse/EVG-7957
=> EVG-7957: Use shared pagination components for My Patches page

src/gql/generated/types.ts, src/gql/queries/get-user-config.ts, src/gql/queries/index.ts, src/pages/preferences/preferencesTabs/cliTab/AuthenticationCard.tsx
Added the authentication info to the auth card in the cli tab
this is dependent on.
https://github.com/evergreen-ci/evergreen/pull/3625
THE API KEY IN THE PICTURE IS NOT MY REAL API KEY ITS FOR MY LOCAL EVERGREEN SERVER
=> EVG-8066 Add auth config to authentication card

src/pages/UserPatches.tsx
https://jira.mongodb.org/browse/EVG-8148
This PR adds in usePollQuery hook to the UserPatches page. This code change originally existed in https://github.com/evergreen-ci/spruce/pull/186 and was removed in https://github.com/evergreen-ci/spruce/pull/190
=> EVG-8148: add in polling code after dropping from bad merge

.eslintrc.js, cypress/integration/patch/configure-patch.ts, src/pages/configurePatch/ConfigurePatchCore.tsx, src/pages/configurePatch/configurePatchCore/ConfigureBuildVariants.tsx, src/pages/configurePatch/configurePatchCore/ConfigureTasks.tsx, src/utils/array/index.ts
You can select multiple  variants by command clicking on them
=> EVG-7974 Add support for selecting multiple tasks in the configure tab

cypress/integration/nav_bar.ts, src/components/Navbar/index.tsx, src/components/styles/StyledLink.tsx, src/hooks/index.ts, src/hooks/useLegacyUIURL.ts
Added a link that sends you to the legacy evergreen ui.
=> EVG-7337 Add link to legacy ui to nav

src/pages/patch/ActionButtons.tsx
https://jira.mongodb.org/browse/EVG-8170
remove this button until we code the subscription modal for this page
=> EVG-8170: Remove Notify Me button on Patch page

src/components/Breadcrumb/index.tsx
=> EVG-8195 Fix breadcrumb link styling

package-lock.json, package.json, src/App.test.tsx, src/App.tsx, src/components/Content/index.tsx, src/components/ErrorBoundary/index.tsx, src/components/NotificationModal.tsx, src/components/TaskStatusBadge.tsx, src/context/auth.tsx, src/gql/GQLWrapper.tsx, src/pages/commitqueue/CommitQueueCard.tsx, src/pages/configurePatch/ConfigurePatchCore.tsx, src/pages/patch/patchTabs/Tasks.tsx, src/utils/errorReporting.test.ts, src/utils/errorReporting.ts, src/utils/request.ts
https://jira.mongodb.org/browse/EVG-7645
=> EVG-7645: report handled and unhandled errors to bugsnag

src/analytics/navbar/useNavbarAnalytics.ts, src/components/Navbar/index.tsx
=> EVG-8239 Add waterfall link to NavBar

src/gql/generated/types.ts, src/gql/mutations/index.ts, src/gql/queries/aws-regions.ts, src/gql/queries/index.ts, src/pages/preferences/preferencesTabs/ProfileTab.tsx
This will only work in staging or prod. The dropdown will now populate with the available aws regions.
Dependent on https://github.com/evergreen-ci/evergreen/pull/3684
=> EVG-7977 Update  dropdown to dynamically select aws regions

cypress/integration/patch/configure-patch.ts, src/pages/task/logs/LogTypes.tsx
https://jira.mongodb.org/browse/EVG-8141
=> EVG-8141: Autoupdate logs on task page

src/components/WelcomeModal/WelcomeModal.tsx, src/pages/preferences/preferencesTabs/NewUITab.tsx, src/pages/preferences/preferencesTabs/ProfileTab.tsx, src/pages/preferences/preferencesTabs/notificationTab/NotificationField.tsx
Some inputs werent being auto filled with their default values.  Also fixes a bug where the welcome modal would opt you out of spruce
=> EVG-8627 Save value of updated settings

src/components/WelcomeModal/WelcomeModal.tsx
center modal and add padding between description and carousel dots
=> EVG-8270: modal styles

src/hooks/tests/usePatchStatusSelect.test.ts, src/hooks/usePatchStatusSelect.ts, src/pages/patch/PatchRestartModal.tsx, src/pages/patch/patchRestartModal/PatchBuildVariantAccordian.tsx, src/pages/patch/patchRestartModal/PatchStatusCheckboxContainer.tsx, src/pages/patch/patchRestartModal/TaskStatusCheckbox.tsx
Changes from before:
- Remove the custom memo comparator
- Actually pass the checked tasks to the places that care about it. oops
=> EVG-8287 improve restart modal performance

cypress/integration/task_metadata_card.ts, src/pages/task/Metadata.tsx
https://jira.mongodb.org/browse/EVG-8142
=> EVG-8142: Task durations seem wrong

src/components/CodeChangesTable/index.tsx, src/pages/task/FilesTables.tsx
[EVG-8323](https://jira.mongodb.org/browse/EVG-8323)
=> EVG-8323 remove scroll and show all items at once from changes table

src/components/Typography/index.ts
https://jira.mongodb.org/browse/EVG-8293
=> EVG-8293: word break long variant names

cypress/integration/task_actions.ts
https://jira.mongodb.org/browse/EVG-12487
I removed the flaking tests because I didn't think the test descriptions added value to our test suite
=> EVG-12487: Fix task_actions flake

cypress/integration/hosts/hosts-sorting.ts
some things in cypress just do not work
=> EVG-12559: delete flakey host sorting e2e test

src/components/Navbar/NavDropdown.tsx, src/constants/routes.ts, src/pages/Preferences.tsx, src/pages/preferences/PreferencesTabs.tsx, src/pages/preferences/preferencesTabs/NewUITab.tsx, src/pages/preferences/preferencesTabs/PublicKeysTab.tsx
https://jira.mongodb.org/browse/EVG-12559
This PR also refactors some code to make things more type safe
App screen shot after code changes:
=> EVG-12559: render Manage Public Keys page

src/gql/generated/types.ts, src/gql/queries/get-host-events.ts, src/gql/queries/get-host.ts, src/gql/queries/hosts.ts, src/pages/Host.tsx
[EVG-12730](https://jira.mongodb.org/browse/EVG-12730)
=> EVG-12730 Host Events Query

cypress/integration/patch/patch-route/patch-modal.ts, src/hooks/usePatchStatusSelect.ts, src/pages/patch/PatchRestartModal.tsx, src/pages/patch/patchRestartModal/PatchBuildVariantAccordian.tsx, src/pages/patch/patchRestartModal/PatchStatusCheckboxContainer.tsx
=> EVG-8003 Add checkbox to restart all tasks for a variant

cypress/integration/spawn/route.ts, src/components/Content/index.tsx, src/components/styles/SideNav.tsx, src/components/styles/index.ts, src/constants/routes.ts, src/pages/Preferences.tsx, src/pages/Spawn.tsx, src/pages/spawn/SpawnHost.tsx, src/pages/spawn/SpawnVolume.tsx
https://jira.mongodb.org/browse/EVG-12577
=> EVG-12577: Create tabs for Volumes and Hosts + placeholder pages

src/gql/generated/types.ts, src/gql/queries/get-my-hosts.ts, src/gql/queries/index.ts, src/pages/Spawn.tsx, src/pages/spawn/SpawnHost.tsx, src/pages/spawn/spawnHost/SpawnHostButton.tsx, src/pages/spawn/spawnHost/SpawnHostModal.tsx, src/pages/spawn/spawnHost/SpawnHostTable.tsx, src/pages/spawn/spawnHost/index.ts
Splitting up the spawn host page work this pr just contains the basic structure of the spawn host page plus data fetching
=> EVG-12780 Create spawn house page layout

cypress/integration/patch/patch-route/tasks-filters.ts, cypress/integration/patch/task-table.ts, cypress/integration/task_route.ts, src/components/TaskStatusBadge.tsx, src/gql/generated/types.ts, src/gql/queries/get-patch-tasks.ts, src/gql/queries/get-task.ts, src/pages/Task.tsx, src/pages/patch/patchTabs/Tasks.tsx, src/pages/patch/patchTabs/tasks/TaskFilters.tsx
https://jira.mongodb.org/browse/EVG-8140
this PR relies on https://github.com/evergreen-ci/evergreen/pull/3915
=> EVG-8140: Show the Blocked status badge on the Task page title and Tasks Table

cli-scripts/deploy-prod.js
Just updated the hint for the post deploy steps
=> Update deploy script instructions

cypress/integration/preferences/public_key_managment.ts
https://jira.mongodb.org/browse/EVG-12901
temporarily mute flakey test
=> EVG-12901: mute flakey test

cli-scripts/deploy-prod.js, cli-scripts/deploy-utils.js, cli-scripts/git-tag-proc.js, cli-scripts/notify-email.js, package-lock.json, package.json
These updates clean up some of the logic around deploying. 
The deploy messages will be more inline with what the evergreen deploys look like.
The commits for each deploy should also be more accurately tracked and reflected in the commit message
=> EVG-12932 Clean up deploy process and messaging

src/gql/generated/types.ts, src/gql/queries/get-my-volumes.ts, src/gql/queries/index.ts, src/pages/spawn/spawnHost/SpawnHostModal.tsx, src/pages/spawn/spawnHost/spawnHostModal/HostDetailsForm.tsx
This adds volumes selection to the spawn host modal it is still waiting on the spawn volume modal.
Tests will follow when this feature is complete.
=> EVG-12914 Add volumes selection to spawn host modal

cypress/integration/host/host_events.ts, cypress/integration/host/host_sidebar.ts, src/pages/host/HostTable.tsx, src/pages/host/Metadata.tsx
=> EVG-12899 Change LastCommunication Format on /host/<hostID>

src/pages/task/FilesTables.tsx
https://jira.mongodb.org/browse/EVG-12950
=> EVG-12960: fix task files input style

src/pages/hosts/HostsTable.tsx
Realized i broke the types for this file when i changed the type for a hosts InstanceTags this should fix it. This pr uses the correct type for the Hosts field
=> Fix typescript error

config/.cmdrc_sample.json, src/components/Banners/SiteBanner.tsx, src/components/Content/index.tsx, src/components/Feedback/index.tsx, src/gql/generated/types.ts, src/gql/queries/get-spruce-config.ts, src/gql/queries/index.ts, src/utils/getEnvironmentVariables.ts
This adds a feature requests link to the bottom of all pages that takes the user to uservoice. 
A new `.cmdrc.json` is needed to test
Depends on https://github.com/evergreen-ci/evergreen/pull/3995
=> EVG-12929 Create uservoice feedback component

src/components/Feedback/index.tsx, src/gql/generated/types.ts, src/gql/queries/get-spruce-config.ts, src/pages/task/Metadata.test.tsx
Query field was changed on the backend
=> EVG-12929 Update query for uservoice

.evergreen.yml, package.json
This adds a task which typechecks spruce
=> EVG-13063 Add typecheck to evergreen

src/gql/generated/types.ts, src/pages/spawn/spawnHost/fields/VolumesField.tsx, src/pages/spawn/spawnHost/spawnHostModal/HostDetailsForm.tsx
https://jira.mongodb.org/browse/EVG-13110
=> EVG-13110: run codegen and update types

src/components/Feedback/index.tsx
The feedback component now remembers if it was last closed or opened. It will default to open if its the first time a user has seen it.
=> EVG-13123 Save feedback component state

src/pages/patch/Metadata.tsx
requires the changes in https://github.com/evergreen-ci/evergreen/pull/4039
=> EVG-12596 only display base link if there is one

.evergreen.yml, cypress.json, cypress/integration/my_patches.ts, cypress/integration/patch/configure-patch.ts, cypress/integration/patch/patch-route/tasks-filters.ts, cypress/integration/patch/subscription-modal.ts, cypress/integration/patch/task-table.ts, cypress/integration/preferences/public_key_managment.ts, package-lock.json, package.json
https://jira.mongodb.org/browse/EVG-12901
I am open to suggestions for the retry count. It is possible to specify a retry count for specific tests and test suites. https://docs.cypress.io/guides/guides/test-retries.html#Global-Configuration
This PR also unmutes tests we marked as flakey
=> EVG-12901: Upgrade to Cypress 5 and enable test retries

src/gql/generated/types.ts, src/gql/mutations/edit-spawn-host.ts, src/gql/mutations/index.ts, src/pages/spawn/spawnHost/EditSpawnHostModal.tsx, src/pages/spawn/spawnHost/editSpawnHostModal/useEditSpawnHostModalState.ts, src/pages/spawn/spawnHost/fields/5-userTagsField.stories.tsx, src/pages/spawn/spawnHost/fields/UserTagsField.test.tsx, src/pages/spawn/spawnHost/fields/UserTagsField.tsx
I wanted to start adopting this useReducer pattern a little bit more when it comes to complex state updates. It lets us be more explicit and deliberate about state changes.
=> EVG-13188 Refactor Edit Spawn Host modal to use reducer

src/pages/host/getHostEventString.tsx, src/types/host.ts
=> EVG-13086  Evergreen Add fallback host event to Spruce

src/components/Buildbaron/BBComponents.tsx, src/gql/generated/types.ts
=> EVG-13107 Evergreen fix build baron badge overflow

package-lock.json, package.json, src/pages/Task.tsx
This also disables the tabs instead of trying to hide them.
=> EVG-13427 Fix bug where leafygreen tabs hijacked arrow key input on text boxes

src/gql/generated/types.ts, src/gql/queries/get-task-tests.ts, src/pages/task/testsTable/TestsTableCore.tsx
Dependent on https://github.com/evergreen-ci/evergreen/pull/4100
=> EVG-8296 Add base statuses to tests table

src/analytics/addPageAction.ts, src/analytics/index.ts, src/analytics/preferences/usePreferencesAnalytics.ts, src/pages/Preferences.tsx, src/pages/preferences/preferencesTabs/NewUITab.tsx, src/pages/preferences/preferencesTabs/NotificationsTab.tsx, src/pages/preferences/preferencesTabs/ProfileTab.tsx, src/pages/preferences/preferencesTabs/PublicKeysTab.tsx, src/pages/preferences/preferencesTabs/cliTab/AuthenticationCard.tsx, src/pages/preferences/preferencesTabs/cliTab/DownloadCard.tsx, src/pages/preferences/preferencesTabs/publicKeysTab/EditModal.tsx
https://jira.mongodb.org/browse/EVG-12705
=> EVG-12705: Preferences Pages analytics 

src/components/Banners/SiteBanner.tsx
=> EVG-13117 Linkify jira tickets in banner

src/analytics/spawn/useSpawnAnalytics.ts, src/pages/spawn/spawnVolume/SpawnVolumeButton.tsx, src/pages/spawn/spawnVolume/spawnVolumeButton/SpawnVolumeModal.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/DeleteVolumeBtn.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/UnmountBtn.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/mountButton/MountVolumeModal.tsx
https://jira.mongodb.org/browse/EVG-12706
analytics for the Edit Volume Modal is included in #485
=> EVG-12706: Volume page analytics

src/gql/queries/get-my-volumes.ts, src/pages/spawn/spawnHost/EditSpawnHostModal.tsx, src/pages/spawn/spawnHost/SpawnHostModal.tsx, src/pages/spawn/spawnVolume/spawnVolumeButton/SpawnVolumeModal.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/DeleteVolumeBtn.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/UnmountBtn.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/editButton/EditVolumeModal.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/mountButton/MountVolumeModal.tsx
https://jira.mongodb.org/browse/EVG-13329
=> EVG-13329: refetch MyVolumes, MyHosts and MyPublicKeys after mutations

src/pages/spawn/SpawnVolume.tsx, src/pages/spawn/spawnHost/SpawnHostCard.tsx, src/pages/spawn/spawnVolume/SpawnVolumeTable.tsx
https://jira.mongodb.org/browse/EVG-13330
=> EVG-13330: Copy updates

package-lock.json, package.json, src/pages/Task.tsx
Is there some place we need to add the new env variable so that this works in production?
=> EVG-12870: Turn Trend Charts on

cypress/integration/spawn/volume.ts, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/DeleteVolumeBtn.tsx
https://jira.mongodb.org/browse/EVG-13354
related discussion: https://github.com/evergreen-ci/evergreen/pull/4127
=> EVG-13354: Delete volume confirmation checkbox

cypress/integration/spawn/volume.ts, src/components/Spawn/Layout.tsx, src/constants/routes.ts, src/pages/spawn/spawnVolume/SpawnVolumeTable.tsx
https://jira.mongodb.org/browse/EVG-13335
=> EVG-13335: Link from spawn/volume to spawn/host by clicking on host name

cypress/integration/spawn/volume.ts, src/components/Spawn/Layout.tsx
https://jira.mongodb.org/browse/EVG-13334
=> EVG-13334: make table dropdown card caret clickable

cypress/integration/spawn/host.ts, src/pages/spawn/spawnHost/SpawnHostModal.tsx, src/pages/spawn/spawnHost/fields/VolumesField.tsx, src/pages/spawn/spawnHost/spawnHostModal/HostDetailsForm.tsx
https://jira.mongodb.org/browse/EVG-13339
=> EVG-13339: Only allow home volumes in the virtual workstation dropdown

src/components/Spawn/DetailsCard.tsx, src/constants/externalResources.ts, src/pages/Spawn.tsx, src/pages/spawn/spawnHost/SpawnHostCard.tsx, src/pages/spawn/spawnHost/SpawnHostModal.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/SpawnVolumeCard.tsx
=> EVG-13381 EVG-13376 Conditionally render ide link and hide expiration for mounted volumes

src/gql/generated/types.ts, src/gql/mutations/edit-spawn-host.ts, src/pages/spawn/spawnHost/EditSpawnHostModal.tsx
https://jira.mongodb.org/browse/EVG-13415
=> EVG-13415: update EditSpawnHost query param

cypress/integration/spawn/volume.ts, src/components/Popconfirm/PopconfirmWithCheckbox.test.tsx, src/components/Popconfirm/index.tsx, src/components/Spawn/Layout.tsx, src/pages/spawn/spawnHost/EditSpawnHostButton.tsx, src/pages/spawn/spawnHost/SpawnHostActionButton.tsx, src/pages/spawn/spawnHost/SpawnHostTableActions.tsx, src/pages/spawn/spawnVolume/spawnVolumeButton/SpawnVolumeModal.test.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/DeleteVolumeBtn.tsx
https://jira.mongodb.org/browse/EVG-13364
=> EVG-13364: Wrap Host trash btn in popconfirm

src/analytics/preferences/usePreferencesAnalytics.ts, src/pages/preferences/preferencesTabs/ProfileTab.tsx
As discussed in the UI meeting this removes the logout button
=> EVG-13313 Remove logout button

src/components/BuildBaronAndAnnotations/AddIssueModal.tsx, src/components/BuildBaronAndAnnotations/AnnotationTickets.tsx, src/components/BuildBaronAndAnnotations/BuildBaron.test.tsx, src/components/BuildBaronAndAnnotations/BuildBaron.tsx, src/components/BuildBaronAndAnnotations/BuildBaronContent.tsx, src/gql/generated/types.ts, src/gql/mutations/add-annotation.ts, src/gql/queries/get-task.ts, src/pages/Task.tsx
Depends on [4284](https://github.com/evergreen-ci/evergreen/pull/4284).
=> EVG-13641 Let users add Issues and Suspect Issues on the UI

.evergreen.yml, .gitignore, cypress/integration/code_changes_table.ts, cypress/integration/my_patches.ts, cypress/integration/test_table.ts, cypress/utils/index.js, src/components/CodeChangesTable/index.tsx, src/components/Typography/index.ts, src/pages/patch/patchTabs/Tasks.tsx, src/pages/preferences/preferencesTabs/PublicKeysTab.tsx, src/pages/spawn/spawnHost/SpawnHostTable.tsx, src/pages/spawn/spawnVolume/SpawnVolumeTable.tsx, src/pages/task/FilesTables.tsx, src/pages/task/testsTable/TestsTableCore.tsx
https://jira.mongodb.org/browse/EVG-13416
=> EVG-13416: Wrap column names

cypress/integration/task/annotations.ts, src/components/BuildBaronAndAnnotations/AddIssueModal.tsx, src/components/BuildBaronAndAnnotations/AnnotationTickets.tsx, src/components/BuildBaronAndAnnotations/AnnotationTicketsTable.tsx, src/gql/generated/types.ts, src/gql/mutations/move-annotation.ts, src/gql/mutations/remove-annotation.ts, src/gql/queries/get-code-changes.ts, src/gql/queries/get-commit-queue.ts
Depends on [4284](https://github.com/evergreen-ci/evergreen/pull/4284).
=> EVG-13170 Let users delete Issues and Suspect Issues on the UI

src/components/BuildBaronAndAnnotations/AnnotationNote.tsx, src/components/BuildBaronAndAnnotations/AnnotationTickets.tsx, src/components/BuildBaronAndAnnotations/BBCreatedTickets.tsx, src/components/BuildBaronAndAnnotations/BuildBaronContent.tsx, src/gql/generated/types.ts, src/gql/queries/get-task.ts, src/pages/Task.tsx, src/pages/task/Metadata.test.tsx
Combined with [the EVG PR](https://github.com/evergreen-ci/evergreen/pull/4310)
=> EVG-13167 move annotation permission to task

src/components/BuildBaronAndAnnotations/AnnotationTicketsTable.tsx
=> EVG-13706  Align buttons between the Issues and Suspected Issues Tables

.evergreen.yml
This likely wont be the last pr for this ticket. This fixes the broken builds after this is merged we will be able to see if  the email issue on the next deploy is still present
=> EVG-13506 Fix evergreen deploys

cypress/integration/host/host_events.ts, src/pages/host/getHostEventString.tsx
Depends on [4325](https://github.com/evergreen-ci/evergreen/pull/4325)
=> EVG-13813 Host Event Additional Details Bug

README.md, package.json
I kind of did the minimum here but I think it makes things better. Suggestions are welcome!
=> EVG-13657 make cypress a bit more friendly

cypress/integration/host/host_buttons.ts, cypress/integration/hosts/select-hosts.ts, src/components/Hosts/RestartJasper.tsx, src/gql/generated/types.ts, src/gql/queries/get-host.ts, src/gql/queries/hosts.ts, src/pages/Host.tsx, src/pages/Hosts.tsx, src/pages/hosts/HostsTable.tsx
Depends on: [4335](https://github.com/evergreen-ci/evergreen/pull/4335)
=> EVG-13574 Restart Jasper button is wrong for legacy provisioned hosts

src/pages/configurePatch/configurePatchCore/ConfigureBuildVariants.tsx
https://jira.mongodb.org/browse/EVG-13571
Before & After
https://user-images.githubusercontent.com/10734386/105244709-e69bc400-5b3e-11eb-98ba-331e9a6e9509.mov
https://user-images.githubusercontent.com/10734386/105244730-ee5b6880-5b3e-11eb-9ccc-ba47dd801101.mov
=> EVG-13571: Configure Page: Prevent text selection when using hot keys

cli-scripts/deploy-prod.js
Deploy script now always just pushes up a git tag and lets evergreen deploy by default.
Also added a fallback in the script in case we want to manually redeploy locally.
=> EVG-13506 Update deploy process to favor using evg for deploys

cypress/integration/project/patches.ts, src/pages/task/taskTabs/buildBaronAndAnnotations/BBComponents.tsx
=> EVG-14073 fix annotation note metadata styling

cypress/integration/test_table.ts
This is to fix the failing test table tests because the data changed.
=> EVG-13726 Fix test table tests

src/gql/generated/types.ts, src/gql/queries/get-patch-build-variants.graphql, src/gql/queries/get-patch-tasks.graphql, src/hooks/tests/usePatchStatusSelect.test.ts, src/hooks/usePatchStatusSelect.ts, src/pages/patch/BuildVariants.tsx, src/pages/patch/buildVariants/buildVariants.test.ts, src/pages/patch/buildVariants/utils.ts, src/pages/patch/patchRestartModal/PatchBuildVariantAccordian.tsx, src/pages/patch/patchRestartModal/PatchStatusCheckboxContainer.tsx
This should be merged and deployed after https://github.com/evergreen-ci/evergreen/pull/4442 is deployed
=> EVG-14187 Temporarily make subset fields similar to task field

cypress/integration/commit_queue.ts, src/constants/externalResources.ts, src/gql/generated/types.ts, src/gql/queries/get-commit-queue.graphql, src/pages/CommitQueue.tsx, src/pages/commitqueue/CommitQueueCard.tsx
relies on https://github.com/evergreen-ci/evergreen/pull/4538
=> EVG-14215 show more data for commit queue pull requests

cypress/integration/patch/task_filters.ts, src/analytics/patch/usePatchAnalytics.ts, src/components/TreeSelect.tsx, src/hooks/useFilterInputChangeHandler.ts, src/hooks/useStatusesFilter.ts, src/pages/patch/patchTabs/Tasks.tsx, src/pages/patch/patchTabs/tasks/PatchTasksTable.tsx, src/pages/patch/patchTabs/tasks/TaskFilters.tsx
The input would lose focus because it would quickly rerender between inputs for some reason it was more apparent on prod vs locally. Also fixed a unsafe dismount warning that was occurring because of a state update in the analytics hook. Also did some cleanup.
=> EVG-13884 Fix input defocus when typing in characters

src/pages/TaskHistory.tsx, src/pages/VariantHistory.tsx
For now these are just placeholders until we wire up the queries that contain the data
=> EVG-13863 Create Page titles

src/pages/spawn/spawnHost/SpawnHostModal.tsx
The dropdown will now fit its contents
=> EVG-14193 Make distro dropdown wider

src/gql/generated/types.ts, src/gql/queries/get-task-tests.graphql, src/pages/task/taskTabs/testsTable/TestsTableCore.tsx
=> EVG-14417 use Display test name in tests table

cypress/integration/project/patches.ts, src/components/PatchesPage/PatchCard.tsx, src/gql/fragments/patchesPage.graphql, src/gql/generated/types.ts, src/gql/queries/get-patch.graphql, src/gql/queries/get-task.graphql, src/pages/patch/Metadata.tsx, src/pages/task/Metadata.tsx
See https://github.com/evergreen-ci/evergreen/pull/4567 for details.
=> EVG-14328 use project identifier for patch workflow

src/context/toast.tsx
=> EVG-14384 Fix toast word break

cypress/integration/commit_queue.ts, src/pages/commitqueue/CommitQueueCard.tsx
=> EVG-14418 Remove ability to remove patch from commit queue card

src/pages/task/taskTabs/buildBaronAndAnnotations/AnnotationTicketsTable.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/BBComponents.tsx
=> EVG-14134 Fix spacing between issue metadata and button

src/pages/spawn/spawnHost/SpawnHostTable.tsx
=> EVG-14573 Fix host id wrapping

src/pages/patch/buildVariants/GroupedTaskSquare.tsx
Also updated a style to use the proper util file
=> EVG-13386 Use strict regex matching for build variant squares

cypress/integration/patch/configure_patch.ts, src/pages/configurePatch/ConfigurePatchCore.tsx
relies on https://github.com/evergreen-ci/evergreen/pull/4635
there aren't really any changes here, I just cleaned up a query so that we can remove an unneeded field and also added a test
=> EVG-14074 add display task test

src/gql/generated/types.ts, src/gql/queries/get-patch-configure.graphql
John forgot to remove this  field from the query
=> EVG-14074 Remove no longer existent type

src/pages/task/TaskTabs.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/AnnotationNote.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/AnnotationTickets.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/AnnotationTicketsTable.tsx
=> EVG-14445 Rename 'Task Annotations' tab to Failure Details

src/pages/configurePatch/ConfigurePatchCore.tsx, yarn.lock
[EVG-14725](https://jira.mongodb.org/browse/EVG-14725)
This existed before and was removed in a refactor
=> EVG-14725 Remove typename from patch params query

src/pages/spawn/spawnHost/EditSpawnHostButton.tsx, src/pages/spawn/spawnHost/EditSpawnHostModal.tsx, src/pages/spawn/spawnHost/SpawnHostButton.tsx, src/pages/spawn/spawnHost/SpawnHostTableActions.tsx
=> EVG-14664 Update hostspawn tooltip to leafy green

cypress/integration/patch/configure_patch.ts, package.json, src/components/SpruceForm/__snapshots__/SpruceForm.stories.storyshot, yarn.lock
[EVG-14652](https://jira.mongodb.org/browse/EVG-14652)
=> EVG-14652 Fix indeterminate handling of select all checkboxes

src/pages/configurePatch/ConfigurePatchCore.tsx
[EVG-14799](https://jira.mongodb.org/browse/EVG-14799)
=> EVG-14799 Open configure tab by default on configure page

cypress/integration/task/annotations.ts, src/gql/generated/types.ts, src/pages/task/taskTabs/buildBaronAndAnnotations/AddIssueModal.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/AnnotationNote.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/AnnotationTicketsTable.tsx
[EVG-14884](https://jira.mongodb.org/browse/EVG-14884)
Refetch more specific queries instead of the whole task. This fixes the flaky annotations test. I also refactored the test a bit so that it is more readable.
=> Evg 14884 Fix flaky cypress test for task_annotations

src/constants/announcementToast.ts
- Remove navigation announcement added in #777
=> Remove navigation announcement toast

.evergreen.yml
=> Bump go to 1.16

src/components/PatchActionButtons/RestartPatch.tsx, src/components/PatchesPage/PatchCard.tsx, src/components/PatchesPage/patchCard/DropdownMenu.tsx, src/gql/fragments/patchesPage.graphql, src/gql/generated/types.ts, src/pages/Patch.tsx, src/pages/patch/ActionButtons.tsx, src/pages/patch/PatchRestartModal.tsx
[EVG-14597](https://jira.mongodb.org/browse/EVG-14597)
I am breaking out this work so that Sophie can re-use it when working on EVG-14974 so that we can avoid merge conflicts and duplicating work.
=> EVG-14597: Patch through childPatches

src/components/SearchableDropdown/SearchableDropdown.stories.tsx, src/components/SearchableDropdown/SearchableDropdown.test.tsx, src/components/SearchableDropdown/__snapshots__/SearchableDropdown.stories.storyshot, src/components/SearchableDropdown/index.tsx, src/pages/TaskHistory.tsx, src/pages/commits/projectSelect/ProjectOptionGroup.tsx
[EVG-15257](https://jira.mongodb.org/browse/EVG-15257)
[Check the storybook build when the storybook task completes for a live demo.](https://mciuploads.s3.amazonaws.com/spruce/spruce_ubuntu1604_storybook_patch_cf94d556699ba8d6f862c3cc5be3b50dd7b5c619_611d308c2fbabe101d249f8c_21_08_18_16_08_45/storybook/index.html?path=/story/searchable-dropdown--story)
Unit tests, and manual storybook tests
=> EVG-15257 Create a reusable multi select  component with search

src/components/SearchableDropdown/__snapshots__/SearchableDropdown.stories.storyshot, src/components/SearchableDropdown/index.tsx, src/constants/routes.ts, src/gql/generated/types.ts, src/gql/queries/get-build-variant-history.graphql, src/gql/queries/get-task-history.graphql, src/gql/queries/index.ts, src/pages/TaskHistory.tsx, src/pages/VariantHistory.tsx, src/pages/taskHistory/BuildVariantSelector.tsx, src/pages/variantHistory/TaskSelector.tsx, yarn.lock
[EVG-14996](https://jira.mongodb.org/browse/EVG-14996)
Create build variant and task history drop downs
designs
demo
https://user-images.githubusercontent.com/4605522/130275250-a41365f2-3690-43b1-885b-a24ac007a0c8.mov
On staging and locally
=> EVG-14996 Create build variant and task history dropdowns

cypress/integration/task/execution_task_table.ts, src/components/PatchTabs/downstreamTasks/DownstreamProjectAccordion.tsx, src/components/PatchTabs/tasks/PatchTasksTable.tsx, src/components/Table/TasksTable.tsx, src/components/Table/__snapshots__/TasksTable.stories.storyshot
[EVG-15332](https://jira.mongodb.org/browse/EVG-15332)
There are no functionality changes. This is just a small refactor to cleanup some logic and hopefully make this table a little more readable and maintainable
=> EVG-15332 Clean up task tables 

cypress/integration/job_logs.ts, env/.cmdrc_sample.json
[EVG-15427](https://jira.mongodb.org/browse/EVG-15427)
Fix a url that was changed in https://github.com/evergreen-ci/spruce/pull/880
=> EVG-15427 Fix failing tests

src/components/Icon/__snapshots__/Icon.stories.storyshot, src/components/Icon/icons/index.tsx, src/pages/Preferences.tsx, src/pages/ProjectSettings.tsx, src/pages/Spawn.tsx, src/pages/spawn/spawnHost/SpawnHostActionButton.tsx, src/pages/spawn/spawnHost/SpawnHostTableActions.tsx, src/pages/task/taskTabs/testsTable/TestsTableCore.tsx
EVG-15421
- Use icon for "Copy SSH Command" button
- Fix tasks table action button wrapping (use xsmall button)
- Remove play and pause icons now that they are part of LG icon set
- Fix side nav console warning
=> EVG-15421: Action button fixes

src/pages/task/taskTabs/logs/LogTypes.tsx
[EVG-15433](https://jira.mongodb.org/browse/EVG-15433)
=> EVG-15433 Switching Log types shouldn't switch execution

src/gql/generated/types.ts, src/gql/mutations/index.ts, src/gql/mutations/override-task-dependencies.graphql, src/gql/queries/get-task.graphql, src/pages/Task.tsx, src/pages/task/ActionButtons.tsx, src/pages/task/Metadata.test.tsx, src/pages/task/Metadata.tsx, src/pages/task/metadata/DependsOn.tsx
[EVG-8326](https://jira.mongodb.org/browse/EVG-8326)
Dependent on https://github.com/evergreen-ci/evergreen/pull/5058
=> EVG-8326 Create button to override dependencies

src/pages/task/Metadata.tsx
[EVG-15526](https://jira.mongodb.org/browse/EVG-15526)
=> EVG-15526 Use user timezone for dates and  times in task metadata

src/components/HistoryTable/Row.tsx, src/components/HistoryTable/row/DateSeparator.tsx
[EVG-13953](https://jira.mongodb.org/browse/EVG-13953)
Actual: 
Design:
=> EVG-13953: History Table Date Separator 

src/pages/task/taskTabs/buildBaronAndAnnotations/AnnotationNote.tsx
[EVG-15371](https://jira.mongodb.org/browse/EVG-15371)
=> EVG-15371 Update annotation note state when originalMessage changes

src/gql/generated/types.ts, src/gql/queries/failed-task-status-icon-tooltip.graphql, src/pages/commits/ActiveCommits/buildVariantCard/WaterfallTaskStatusIcon.test.tsx, src/pages/commits/ActiveCommits/buildVariantCard/WaterfallTaskStatusIcon.tsx
[EVG-15664](https://jira.mongodb.org/browse/EVG-15664)
Show the remaining number of failing tests not represented in the tooltip
Jest
=> EVG-15664: Show failed test count in waterfall icon tooltip

src/components/ProjectSettingsTabs/GeneralTab/GeneralTab.tsx, src/components/ProjectSettingsTabs/GeneralTab/getFormData.ts, src/components/ProjectSettingsTabs/GeneralTab/index.ts, src/components/ProjectSettingsTabs/GeneralTab/testData.ts, src/components/ProjectSettingsTabs/GeneralTab/transformers.test.ts, src/components/ProjectSettingsTabs/GeneralTab/transformers.ts, src/components/ProjectSettingsTabs/GeneralTab/types.ts, src/components/ProjectSettingsTabs/Header.tsx, src/components/ProjectSettingsTabs/transformers.ts, src/components/ProjectSettingsTabs/types.ts, src/pages/ProjectSettings.tsx, src/pages/projectSettings/Tabs.tsx
EVG-15921
- Transform data from GQL results to form state in shared Tabs component (rather than within each tab). This prevents the data from having to be memoized so as not to be re-processed on each render. It also avoids having to do two separate transformations of the data.
- Improving typing and organization of transform functions
=> EVG-15921: Improve transformers and typing

src/gql/generated/types.ts, src/gql/queries/get-build-baron.graphql, src/hooks/tests/UseBuildBaronVariables.test.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/BuildBaron.test.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/BuildBaronContent.tsx
[EVG-16015](https://jira.mongodb.org/browse/EVG-16015)
There is now a use case for creating custom tickets without a webhook being defined.
=> EVG-16015 Tickets filed using the created_ticket endpoint are not showing up on the UI

src/components/ProjectSettingsTabs/VariablesTab/VariableRow.test.tsx
EVG-16083
- Fix invalid import introduced by #1013
=> EVG-16083: Fix invalid import

src/components/SpruceForm/FieldTemplates.tsx, src/components/SpruceForm/SpruceForm.stories.tsx, src/components/SpruceForm/__snapshots__/SpruceForm.stories.storyshot, src/components/TreeSelect/__snapshots__/TreeSelect.stories.storyshot
EVG-16089
- Support hidden objects in SpruceForm
- Add storybook entry which can be expanded for further demonstration of supported UI options
=> EVG-16089: Support hidden option for objects

src/components/ExpandedText/__snapshots__/ExpandedText.stories.storyshot, src/components/ExpandedText/index.tsx
[EVG-16086](https://jira.mongodb.org/browse/EVG-16086)
=> EVG-16086 Cursor wont change on hover of more button

src/gql/generated/types.ts, src/pages/task/metadata/DependsOn.tsx, src/pages/task/metadata/Metadata.stories.tsx, src/pages/task/metadata/__snapshots__/Metadata.stories.storyshot
[EVG-16008](https://jira.mongodb.org/browse/EVG-16008)
Running tasks will show the running icon in the dependency metadata 
https://github.com/evergreen-ci/evergreen/pull/5309
=> EVG-16008 Add started dependency icon

yarn.lock
[EVG-16130](https://jira.mongodb.org/browse/EVG-16130)
This would get regenerated every time i ran yarn which means it was probably not committed the first time.
=> EVG-16130 Update yarn lock

cypress/integration/commits/chart_toggle.ts, src/components/CommitChartLabel/index.tsx, src/components/ExpandedText/index.tsx, src/components/Header/Navbar.tsx, src/pages/Commits.tsx, src/pages/commits/ActiveCommits/ChartToggle.tsx, src/pages/commits/ActiveCommits/CommitChart.stories.tsx, src/pages/commits/ActiveCommits/CommitChart.tsx, src/pages/commits/ActiveCommits/CommitChartTooltip.tsx, src/pages/commits/ActiveCommits/Grid.tsx, src/pages/commits/ActiveCommits/ProjectHealth.stories.tsx, src/pages/commits/ActiveCommits/__snapshots__/CommitChart.stories.storyshot, src/pages/commits/ActiveCommits/__snapshots__/ProjectHealth.stories.storyshot, src/pages/commits/ActiveCommits/index.tsx, src/pages/commits/CommitsWrapper.tsx, src/pages/commits/InactiveCommits/InactiveCommits.stories.tsx, src/pages/commits/InactiveCommits/InactiveCommits.test.tsx, src/pages/commits/InactiveCommits/__snapshots__/InactiveCommits.stories.storyshot, src/pages/commits/InactiveCommits/index.tsx, src/pages/commits/PaginationButtons.tsx, src/pages/commits/RenderCommit.tsx, src/pages/commits/constants.ts, src/types/commits.ts
[EVG-16120](https://jira.mongodb.org/browse/EVG-16120)
Refactored the commits page to have a more semantically correct html structure. Which now allows us to use the `position: sticky` css attribute.  
This also updates some sizes in preparation for EVG-16152
There is also a refactor of some storybook stories and some components to make it easier to render the project health view in a storybook story.
https://user-images.githubusercontent.com/4605522/150557960-a1a713b0-19f3-41fe-9747-0d88048b3338.mov
=> EVG-16120 Sticky column headers and refactor commits page

src/pages/preferences/preferencesTabs/cliTab/DownloadCard.tsx
[EVG-14662](https://jira.mongodb.org/browse/EVG-14662)
=> EVG-14662 Add arm MacOS download card

.storybook/preview.js, package.json, src/.eslintrc.js, src/components/Dropdown/Dropdown.stories.tsx, src/components/EditableTagField/EditableTagField.stories.tsx, src/components/EditableTagField/__snapshots__/EditableTagField.stories.storyshot, src/components/FilterBadges/FilterBadges.stories.tsx, src/components/GroupedTaskStatusBadge/GroupedTaskStatusBadge.stories.tsx, src/components/HistoryTable/HistoryTable.stories.tsx, src/components/HistoryTable/HistoryTableIcon/HistoryTableIcon.stories.tsx, src/components/HistoryTable/HistoryTableTestSearch/HistoryTableTestSearch.stories.tsx, src/components/HistoryTable/row/FoldedCommit.stories.tsx, src/components/Icon/Icon.stories.tsx, src/components/SpruceForm/SpruceForm.stories.tsx, src/components/TaskStatusBadge/TaskStatusBadge.stories.tsx, src/components/TaskStatusIcon/TaskStatusIcon.stories.tsx, src/components/TupleSelect/TupleSelect.stories.tsx, src/pages/commits/ActiveCommits/ProjectHealth.stories.tsx, src/pages/spawn/spawnHost/fields/userTagsField.stories.tsx, src/pages/spawn/spawnHost/spawnHostModal/publicKeyForm.stories.tsx, yarn.lock
[EVG-16218](https://jira.mongodb.org/browse/EVG-16218)
Storybook recently released a [set of eslint rules ](https://storybook.js.org/blog/how-to-use-storybook-with-eslint/) i thought it might be useful to incorporate them in our codebase.
=> EVG-16218 Add storybook eslint rules

cli-scripts/setup-credentials.js, src/components/ErrorBoundary/ErrorBoundary.test.tsx, src/components/ErrorBoundary/index.tsx, src/test_utils/utils.ts, src/utils/errorReporting.test.ts, src/utils/errorReporting.ts
[EVG-16264](https://jira.mongodb.org/browse/EVG-16264)
Needed to add the RELEASE STAGE field to the script that generates the env variables for prod deploys.
Also updated and refactored some tests around bugsnag
=> EVG-16264 Add release stage to bugsnag config and update tests

src/components/VersionRestartModal/VersionRestartModal.tsx
[EVG-16300](https://jira.mongodb.org/browse/EVG-16300)
Noticed the restart modal was performing a query on initial page load this is an expensive query. (Uses GetTasksByVersion under the hood) We shouldn't be making it for a part of the page that a user may never open.
=> EVG-16300 Skip query unless modal is opened

src/pages/commits/ActiveCommits/CommitChartTooltip.tsx, src/pages/commits/InactiveCommits/index.tsx, src/pages/commits/constants.ts
[EVG-16340](https://jira.mongodb.org/browse/EVG-16340)
=> EVG-16340 Fix waterfall tooltip blocked by options

.evergreen.yml
EVG-16392
- Fix e2e task based on changes in https://github.com/evergreen-ci/evergreen/pull/5410
=> EVG-16392: Fix e2e task

src/components/VersionRestartModal/BuildVariantAccordian.tsx
[EVG-16278](https://jira.mongodb.org/browse/EVG-16278)
before:
after:
=> EVG-16278 Fix accordion title misalignment

src/components/ProjectSettingsTabs/VariablesTab/transformers.test.ts, src/components/ProjectSettingsTabs/VariablesTab/transformers.ts, src/components/ProjectSettingsTabs/testData.ts
EVG-16419
- Fix bug where private variables were saved with value `{REDACTED}`
- Fix tests
=> EVG-16419: Fix private variable save bug

src/gql/generated/types.ts
=> Bump gql types

src/pages/commits/ActiveCommits/CommitChart.tsx, src/pages/commits/ActiveCommits/__snapshots__/CommitChart.stories.storyshot, src/pages/commits/ActiveCommits/__snapshots__/ProjectHealth.stories.storyshot
[EVG-16222](https://jira.mongodb.org/browse/EVG-16222)
Tooltip activation is now the entire waterfall grid instead of only the width of a single bar
https://user-images.githubusercontent.com/4605522/157714950-64e33180-f667-4a4e-9200-d9ed01405952.mov
=> EVG-16222 Make waterfall tooltip easier to click

cypress/integration/version/version_route.ts
[EVG-16827](https://jira.mongodb.org/browse/EVG-16827)
=> EVG-16827 Fix broken cypress test

cypress/integration/breadcrumbs.ts, cypress/integration/nav_bar.ts, cypress/integration/projectHealth/commits.ts, cypress/integration/projectHealth/route.ts, cypress/integration/projectHealth/taskHistory.ts, src/pages/Commits.tsx, src/utils/environmentalVariables.ts
[EVG-16824](https://jira.mongodb.org/browse/EVG-16824)
This will reenable e2e tests on ci.
=> EVG-16824 Enable mainline commits locally and on ci

src/pages/configurePatch/configurePatchCore/ConfigureTasks.tsx
[EVG-15647](https://jira.mongodb.org/browse/EVG-15647)
Sort the tasks in the configure page even when the build variant selection changes.
=> EVG-15647: Sort task names in configure page

src/constants/welcomeModalProps.ts
[EVG-16847](https://jira.mongodb.org/browse/EVG-16847)
< link to a corresponding evergreen PR if applicable >
=> EVG-16847 Remove broken link in welcome modal

src/components/CommitChartLabel/index.tsx, src/components/WelcomeModal/WelcomeModal.tsx, src/pages/commits/ActiveCommits/__snapshots__/ProjectHealth.stories.storyshot
[EVG-16852](https://jira.mongodb.org/browse/EVG-16852)
Make modal focus on carousel immediately. This makes it easier to use the arrow keys to change carousel slides. 
Don't close modal on backdrop click. This helps make it harder to accidentally close the modal.
=> EVG-16852 Welcome modal improvements

src/pages/projectSettings/Header.tsx
[EVG-<number>](https://jira.mongodb.org/browse/EVG-16924)
This removed the unnecessary default to repo button on event log page
Tested on staging
=> EVG-16924 Remove unnecessary default to repo button on event log page

src/pages/projectSettings/Header.tsx
Reverts evergreen-ci/spruce#1278
=> Revert "EVG-16924 Remove unnecessary default to repo button on event log page"

cypress/integration/projectSettings/project_settings.ts, src/gql/generated/types.ts
EVG-16871
- Fix e2e test broken by app changes
- Fixed e2e test
https://github.com/evergreen-ci/evergreen/pull/5669#event-6653451184
=> EVG-16871: Fix e2e test

src/components/Hosts/UpdateStatusModal.tsx, src/types/host.ts
[EVG-16833](https://jira.mongodb.org/browse/EVG-EVG-16833)
Add stopped to host status modal to make it easier to unblock.
Tested locally. 
https://github.com/evergreen-ci/evergreen/pull/5682
=> EVG-16833 add stopped to host status modal

package.json, src/components/Button/index.tsx, src/components/Icon/Icon.stories.tsx, src/components/Icon/__snapshots__/Icon.stories.storyshot, src/components/Icon/icons/index.tsx, src/components/IconTooltip/__snapshots__/IconTooltip.stories.storyshot, yarn.lock
[EVG-17042](https://jira.mongodb.org/browse/EVG-17042)
Removed the ant-design/icon package. We only use it in one component and i replaced it with the Spruce Icon component.
=> EVG-17042 Remove ant-design/icon

cypress/integration/host/host_events.ts, src/pages/host/getHostEventString.tsx, src/types/host.ts
[EVG-16550](https://jira.mongodb.org/browse/EVG-16550)
Remove references to the `HOST_TASK_PID_SET` event.
https://github.com/evergreen-ci/evergreen/pull/5714
=> EVG-16550 remove host pid set events

src/pages/projectSettings/tabs/NotificationsTab/SubscriptionField.tsx
[EVG-17181 ](https://jira.mongodb.org/browse/EVG-17181 )
This adds a function to generate webhook secrets which is needed on the project page.
=> EVG-17181  Add generate webhook secret function on Spruce 

.evergreen.yml, check_codegen.sh
[EVG-17326](https://jira.mongodb.org/browse/EVG-17326)
Thought it would be useful for reviewers to see the diff of why the codegen task broke. 
Example task
https://spruce.mongodb.com/task/spruce_ubuntu1604_check_codegen_patch_2a281b272efeb91c38b653e4ccbc1e63b1266835_62d596903e8e86231992ee3c_22_07_18_17_21_26/logs?execution=0
Example diff
https://mciuploads.s3.amazonaws.com/spruce/spruce_ubuntu1604_check_codegen_patch_2a281b272efeb91c38b653e4ccbc1e63b1266835_62d596903e8e86231992ee3c_22_07_18_17_21_26/codegen/codegen.diff
=> EVG-17326 Skunkworks - Save codegen diff to evergreen task

src/pages/projectSettings/tabs/NotificationsTab/utils.ts
[EVG-17342](https://jira.mongodb.org/browse/EVG-17342)
Ran into a undefined error on this array in prod.
=> EVG-17342 Fix error with null array

src/pages/Hosts.tsx
[EVG-14773](https://jira.mongodb.org/browse/EVG-14773)
Add titles to host page
👀
=> EVG-14773 Add titles to hosts pages

config/injectVariablesInHTML.ts, vite.config.ts
[EVG-16708](https://jira.mongodb.org/browse/EVG-16798)
some env variables weren't properly being injected into the static html file that is generated.
=> EVG-16708 Add allowlist for env variables in html

src/pages/projectSettings/tabs/GeneralTab/getFormSchema.tsx, src/pages/projectSettings/tabs/PluginsTab/PluginsTab.tsx, src/pages/projectSettings/tabs/PluginsTab/getFormSchema.ts, src/pages/projectSettings/tabs/utils/form.ts
EVG-17287
- Update Plugins page validation to use less custom function and more schema rules. Also use dependencies instead of a custom hide function to control rendering of radio box fields
- On General tab, use minLength along with required. Also, don't require display name or config file (these are valid when empty according to legacy)
=> EVG-17287: Misc plugins page updates

src/constants/announcementToast.ts
[EVG-17218](https://jira.mongodb.org/browse/EVG-17218)
Add a comment to document how to set a site wide announcement toast why we process a constant in useEffect
=> EVG-17218: Document toastData variable

src/pages/projectSettings/tabs/GithubCommitQueueTab/GithubCommitQueueTab.tsx
EVG-17556
Fix text to go with https://github.com/evergreen-ci/evergreen/pull/5877
=> EVG-17556 modify webhook text

src/pages/projectSettings/tabs/GeneralTab/Fields/RepoConfigField.tsx
EVG-17091
- Stop hiding "Attach to Repo" button on production, aka release Projects Track Multiple Branches 🎉
=> EVG-17091: Enable Attach to Repo button on prod

.evergreen.yml, .storybook/main.ts
EVG-17575
Making the changes proposed in https://github.com/evergreen-ci/parsley/pull/6 here to ensure storybook is saved to s3 correctly.
=> EVG-17575 Ensure storybook artifacts are uploaded to the correct directory

src/pages/projectSettings/tabs/EventLogTab/EventLogTab.tsx
Ensure updated number fields render correctly in event log
Previously, the values would not render
=> EVG-17424: Render number changes in event log

README.md
EVG-17675
Just updates the readme deploy instructions since some steps were no longer relevant
=> EVG-17675 Update readme instructions

src/gql/generated/types.ts, src/pages/taskQueue/TaskQueueTable.tsx
EVG-17576
Adds priority column to task-queue page
=> EVG-17576 Add Priority to task-queue page

src/pages/task/executionDropdown/ExecutionSelector.tsx
EVG-17428
This PR fixes the icons in the Execution dropdown. The font size causes an overflow which is compensated for with a `title` attribute that shows on hover.
- Manually looking
=> EVG-17428: Fix icons in Execution dropdown

package.json, yarn.lock
EVG-17918
This PR upgrades `@leafygreen-ui/table` to v2.0.7.
- No visible changes.
- Existing tests should pass.
=> EVG-17918: Upgrade @leafygreen-ui/table to v2.0.7

cypress/integration/spawn/volume.ts
Jira: https://jira.mongodb.org/browse/EVG-16501
From the original PR - update the e2e Spruce test that depended on looking for an exact error message string.
N/A
e2e test should pass.
https://github.com/evergreen-ci/evergreen/pull/5940
=> EVG-16501: fix e2e error message test

src/test_utils/index.tsx
EVG-18007
Making the same change i made in https://github.com/evergreen-ci/parsley/pull/52
=> EVG-18007 test_utils now wrap element wrappers with router

src/hooks/useLegacyUIURL.ts
EVG-17503
Link to legacy UI for host page routes.
=> EVG-17503 Provide link to legacy ui for hosts pages

src/pages/host/getHostEventString.tsx, src/types/host.ts
EVG-18016
- Add volume migration error to host logging (error will be associated with the host to which the volume was initially attached)
=> EVG-18016: Log volume migration error

src/components/Notifications/form/notification.ts, src/components/SpruceForm/errors.ts
EVG-17477 
Just updating some text to include memberID
=> EVG-17477 Update placeholder and error text

package.json, src/components/Badge/index.tsx, src/components/FilterBadges/__snapshots__/FilterBadges.stories.storyshot, src/components/GroupedTaskStatusBadge/__snapshots__/GroupedTaskStatusBadge.stories.storyshot, src/components/HostStatusBadge.tsx, src/components/PatchStatusBadge.tsx, src/components/Spawn/Layout.tsx, src/components/TabLabelWithBadge.tsx, src/components/Table/__snapshots__/TasksTable.stories.storyshot, src/components/TaskStatusBadge/__snapshots__/TaskStatusBadge.stories.storyshot, src/components/TaskStatusBadge/index.tsx, src/components/VersionRestartModal/BuildVariantAccordion.tsx, src/components/VersionRestartModal/VersionRestartModal.tsx, src/constants/task.ts, src/constants/test.ts, src/pages/CommitQueue.tsx, src/pages/Hosts.tsx, src/pages/configurePatch/ParametersContent.tsx, src/pages/spawn/SpawnHost.tsx, src/pages/spawn/SpawnVolume.tsx, src/pages/spawn/spawnHost/SpawnHostTable.tsx, src/pages/task/metadata/DependsOn.tsx, src/pages/task/metadata/__snapshots__/Metadata.stories.storyshot, src/pages/task/taskTabs/buildBaronAndAnnotations/AnnotationTicketsTable/__snapshots__/AnnotationTicketRow.stories.storyshot, src/pages/task/taskTabs/buildBaronAndAnnotations/BBComponents.tsx, src/pages/task/taskTabs/testsTable/TestStatusBadge.tsx, src/pages/taskQueue/TaskQueueTable.tsx, src/pages/version/ParametersModal.tsx, yarn.lock
EVG-18145
- I opted to get rid of our own `StyledBadge` component, which made the letters lowercase. I noticed that our Figma always uses the badge as designed, so we may as well standardize. Let me know if you don't like the new look though 👀
=> EVG-18145: Upgrade LG Badge

package.json, yarn.lock
EVG-18173
- Small one! `@leafygreen-ui/inline-definition` is used once in the codebase.
=> EVG-18173: Upgrade Inline Definition

package.json, src/components/Loading/PatchAndTaskFullPageLoad.tsx, src/components/MetadataCard.tsx, src/components/Spawn/DetailsCard.tsx, src/components/SpruceForm/Container.tsx, src/components/SpruceForm/__snapshots__/SpruceForm.stories.storyshot, src/components/styles/GlobalStyles.tsx, src/components/styles/SiderCard.tsx, src/pages/configurePatch/configurePatchCore/ConfigureBuildVariants.tsx, src/pages/host/HostCard.tsx, src/pages/projectSettings/tabs/EventLogTab/EventLogTab.tsx, src/pages/spawn/spawnHost/__snapshots__/SpawnHostCard.stories.storyshot, src/pages/task/metadata/__snapshots__/Metadata.stories.storyshot, src/pages/task/metadata/index.tsx, src/pages/version/Metadata.tsx, src/pages/version/downstreamTasks/DownstreamProjectAccordion.tsx, yarn.lock
EVG-18169
- Add a bit more padding to metadata cards to complement the increased roundedness of `Card`. Also fix some uneven line heights caused by LG InlineCode and Link components setting a static line height.
- Replace nested `Link` and `InlineCode` components with an `InlineCode` that has an `href` property. This leverages LG's own styling for code/link elements.
=> EVG-18169: Upgrade Card

package.json, yarn.lock
EVG-18177
- Easy one: segmented control is only used in Spruce Form in the codebase. Works great!
=> EVG-18177: Upgrade Segmented Control

package.json, yarn.lock
EVG-18170
- Easy! `Code` is only used in 4 places in Spruce and they all look good.
=> EVG-18170: Upgrade code

src/analytics/version/useVersionAnalytics.ts, src/pages/version/Metadata.tsx
=> EVG-18328 Track project patches metadata link clicks

package.json, src/components/SpruceForm/FieldTemplates.tsx, src/components/SpruceForm/__snapshots__/SpruceForm.stories.storyshot, src/gql/generated/types.ts, yarn.lock
EVG-18250
- Upgrade expandable card, which is used only in project settings
=> EVG-18250: Upgrade Expandable Card

src/analytics/task/useTaskAnalytics.ts, src/constants/externalResources.ts, src/gql/generated/types.ts, src/gql/queries/get-task-tests.graphql, src/pages/task/taskTabs/Logs.tsx, src/pages/task/taskTabs/testsTable/LogsColumn.tsx
EVG-18435
Adds legacy lobster links back to ui temporarily
=> EVG-18435 Adds lobster task log links back to ui

src/components/Header/AuxiliaryDropdown.tsx, src/components/Header/NavDropdown.tsx, src/components/Header/Navbar.tsx, src/components/Header/UserDropdown.tsx, src/pages/commits/ActiveCommits/buildVariantCard/WaterfallTaskStatusIcon.tsx, src/pages/task/metadata/__snapshots__/Metadata.stories.storyshot, src/pages/task/metadata/index.tsx
EVG-18513
This PR fixes some visual bugs on the `lg-updates` branch. Please feel free to flag any other bugs, I am happy to fix them.
Nav bar:
Depends On: 
Waterfall Task Icon (I messed a little more with this one because to me it's hard to see the different tests in the task):
=> EVG-18513: Fix visual errors

package.json, src/components/PatchesPage/index.tsx, src/pages/task/taskTabs/FilesTables.tsx, yarn.lock
EVG-18531
- Use SearchInput component instead of a styled TextInput. Pretty easy switch!
=> EVG-18531: Use SearchInput

src/gql/generated/types.ts
EVG-18394
Bump types to reflect changes in https://github.com/evergreen-ci/evergreen/pull/6133
https://github.com/evergreen-ci/evergreen/pull/6133
=> EVG-18394 Bump types to reflect 6133

yarn.lock
=> EVG-18573 bump browser list

.evergreen.yml, src/gql/generated/types.ts
EVG-18557
This PR adds the new `auto_update` field to the Evergreen module. [Relevant documentation](https://github.com/evergreen-ci/evergreen/wiki/Project-Configuration-Files#modules)
=> EVG-18557: Add auto_update field to Evergreen module

src/pages/version/Metadata.tsx
=> EVG-17289 Consistent capitalization on version metadata

src/components/Banners/SiteBanner.tsx, src/gql/generated/types.ts, yarn.lock
EVG-18755
Noticed clicking anywhere in the notification banner would close it. This ensures it is only closed if the x button is clicked 
Also Fixes yarn.lock regenerating when running `yarn install`
=> EVG-18755 Only dismiss notification banner if explicitly closed.

src/analytics/navbar/useNavbarAnalytics.ts, src/components/Header/AuxiliaryDropdown.tsx, src/pages/CommitQueue.tsx, src/pages/commitqueue/ConfirmPatchButton.tsx
EVG-18821
Adds commit queue link to nav bar and adds a project selector on the commit queue page
=> EVG-18821 Surface commit queue link 

package.json, src/pages/version/taskDuration/__snapshots__/TaskDurationTable.stories.storyshot, yarn.lock
EVG-18651
- No API/visual changes, just introduces dark mode support.
=> EVG-18651: Upgrade Table

package.json, yarn.lock
EVG-18652
- No API/visual changes, just introduces dark mode support.
=> EVG-18652: Upgrade Confirmation Modal

package.json, yarn.lock
=> EVG-18649 Upgrade SideNav to V13

src/gql/fragments/baseHost.graphql, src/gql/fragments/baseSpawnHost.graphql, src/gql/generated/types.ts, src/pages/Host.tsx, src/pages/host/Metadata.tsx
EVG-18807
Surface host uptime on the host metadata tab on the hosts page
=> EVG-18807 Surface uptime for host on host metadata

docs/decisions/README.md, docs/decisions/adr.md.template
EVG-19026
Creates a template for ADR's following @bsamek's format established in https://github.com/evergreen-ci/pine/tree/main/docs/decisions 
https://adr.github.io/
=> EVG-19026 Create ADR template

src/gql/generated/types.ts
=> EVG-19015 Bump types

src/pages/task/metadata/__snapshots__/Metadata.stories.storyshot, src/pages/task/metadata/index.tsx
EVG-18882
- Apply strict regex to build variant on task page so that filter works as expected
- Snapshots reflect new link with regex characters
=> EVG-18882: Apply regex to build variant link

src/pages/projectSettings/CopyProjectModal.tsx, src/pages/projectSettings/CreateProjectModal.tsx
EVG-18784
Just changes warning text to be more intuitive
=> EVG-18784 Make warning more user friendly

cypress/integration/projectSettings/project_settings.ts, src/gql/fragments/projectSettings/general.graphql, src/gql/generated/types.ts, src/pages/projectSettings/tabs/GeneralTab/getFormSchema.tsx, src/pages/projectSettings/tabs/GeneralTab/transformers.test.ts, src/pages/projectSettings/tabs/GeneralTab/transformers.ts, src/pages/projectSettings/tabs/GeneralTab/types.ts, src/pages/projectSettings/tabs/testData.ts
EVG-19035
we are going to be removing this from the backend so were removing it from the ui first 
no existing tests fail
=> EVG-19035 Remove enabled from repo settings page

src/gql/generated/types.ts
EVG-19079
Update types after the evergreen pr is merged. 
https://github.com/evergreen-ci/evergreen/pull/6318
=> EVG-19079 Delete tasklogs resolver types

cypress/integration/projectSettings/project_settings.ts, src/gql/fragments/projectSettings/access.graphql, src/gql/generated/types.ts, src/pages/commits/ActiveCommits/__snapshots__/ProjectHealth.stories.storyshot, src/pages/projectSettings/CopyProjectModal.test.tsx, src/pages/projectSettings/tabs/AccessTab/getFormSchema.ts, src/pages/projectSettings/tabs/AccessTab/transformers.test.ts, src/pages/projectSettings/tabs/AccessTab/transformers.ts, src/pages/projectSettings/tabs/AccessTab/types.ts, src/pages/projectSettings/tabs/EventLogTab/EventLogTab.test.tsx, src/pages/projectSettings/tabs/testData.ts
EVG-19052
This PR removes the radio box for specifying public / private projects in project settings.
=> EVG-19052: Remove general access section from project settings

cypress/integration/banners/slack_notification_banner.ts, cypress/integration/preferences/public_key_management.ts, cypress/integration/spawn/volume.ts, cypress/integration/task/annotations.ts, cypress/utils/popconfirm.ts, src/components/AntdPopconfirm/PopconfirmWithCheckbox.test.tsx, src/components/AntdPopconfirm/index.tsx, src/components/Banners/SlackNotificationBanner.tsx, src/components/Popconfirm/Popconfirm.test.tsx, src/components/Popconfirm/index.tsx, src/pages/preferences/preferencesTabs/PublicKeysTab.tsx, src/pages/spawn/spawnHost/SpawnHostActionButton.tsx, src/pages/spawn/spawnVolume/spawnVolumeTableActions/DeleteVolumeButton.tsx, src/pages/spawn/spawnVolume/spawnVolumeTableActions/UnmountButton.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/AnnotationTicketsTable/AnnotationTicketsTable.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/FileTicketButton.tsx
Reverts evergreen-ci/spruce#1725
=> Revert "EVG-18525: Replace Antd Popconfirm"

src/components/Content/index.tsx, src/constants/routes.ts, src/pages/Container.tsx, src/pages/container/index.tsx
[EVG-19013](https://jira.mongdb.com/browse/EVG-19013)
These code create the route for the container page
=> EVG-19013: Container route and page placeholder

src/pages/preferences/preferencesTabs/CliTab.tsx, src/pages/preferences/preferencesTabs/cliTab/NodeList.tsx, src/pages/preferences/preferencesTabs/cliTab/nodeList/Node.tsx
EVG-13682
- Add step 3 with chmod instructions
=> EVG-13682: Add permissions instructions

src/components/HostStatusBadge/HostStatusBadge.stories.tsx, src/components/HostStatusBadge/__snapshots__/HostStatusBadge.stories.storyshot, src/components/PodStatusBadge/PodStatusBadge.stories.tsx, src/components/PodStatusBadge/__snapshots__/PodStatusBadge.stories.storyshot
EVG-19258
- Update stories introduced in https://github.com/evergreen-ci/spruce/pull/1743 to use new 7.0 Storybook format
=> EVG-19258: Update stories

src/components/Content/index.tsx
EVG-19303
Temporarily disabling the konami code easter egg.
https://mongodb.slack.com/archives/C0V896UV8/p1680716716393659
=> EVG-19303 Disable easter egg

src/analytics/task/useTaskAnalytics.ts, src/constants/externalResources.ts, src/gql/fragments/annotation.graphql, src/gql/generated/types.ts, src/pages/task/metadata/index.tsx
EVG-18937
Created an annotation metadata link
https://github.com/evergreen-ci/evergreen/pull/6388
=> EVG-18937 Surface annotation metadata links

src/components/ErrorBoundary/index.tsx
EVG-19266
- Add user ID to error boundary logging as done in https://github.com/evergreen-ci/parsley/pull/262
=> EVG-19266: Log user ID with error boundary

src/pages/task/metadata/index.tsx
EVG-19021
Adds container specific verbiage for container tasks.
=> EVG-19021 Update stranded error verbiage for containers

src/components/Table/TasksTable.tsx, src/components/Table/__snapshots__/TasksTable.stories.storyshot, src/components/TaskStatusBadge/TaskStatusBadge.test.tsx, src/components/TaskStatusBadge/index.tsx, src/pages/task/taskTabs/__snapshots__/ExecutionTasksTable.stories.storyshot, src/pages/version/taskDuration/TaskDurationRow.tsx
EVG-14506
EVG-17919
Links the task status badges on the tasks table and execution tasks table to the corresponding task page.
Known Issue links directly to the annotations page.
=> EVG-14506 EVG-17919 Link task status badges to task page

cypress/integration/projectSettings/project_settings.ts, src/gql/generated/types.ts, src/pages/projectSettings/tabs/ContainersTab/getFormSchema.ts
EVG-19807
The validation for container size definitions seems to not be working properly, as I'm able to save the changes when memory and CPU are empty. This PR updates the form schema so that it works correctly.
Before:
After:
- Tried to fix the flaky tests, which I ran 5 times on CI and it passed all times so I am hopeful 🤞
=> EVG-19807: Fix form validation for container size definitions

src/constants/externalResources.ts, src/pages/projectSettings/tabs/GithubCommitQueueTab/getFormSchema.tsx
EVG-19841
Reword text to be a bit clearer about what's needed, and fix links.
=> EVG-19841 tweak wording for version control aliases

src/gql/fragments/projectSettings/general.graphql, src/gql/generated/types.ts, src/pages/projectSettings/Tabs.tsx, src/pages/projectSettings/tabs/GeneralTab/GeneralTab.tsx, src/pages/projectSettings/tabs/GeneralTab/getFormSchema.tsx, src/pages/projectSettings/tabs/GeneralTab/transformers.test.ts, src/pages/projectSettings/tabs/GeneralTab/transformers.ts, src/pages/projectSettings/tabs/GeneralTab/types.ts, src/pages/projectSettings/tabs/testData.ts
EVG-19842
- Remove branch input for repos. A followup PR will remove this field from the GraphQL structure on the back end.
- Updated unit tests
=> EVG-19842: Remove branch for repo settings

package.json, yarn.lock
EVG-19209
This PR upgrades `@leafygreen-ui/palette`.
* I won't be opening a PR in Parsley because it's already up-to-date (through a Dependabot PR).
=> EVG-19209: Upgrade Palette to v4.0.4

src/pages/configurePatch/configurePatchCore/ConfigureBuildVariants.tsx
=> EVG-19654 Make selected build variants bold on configure page

README.md, package.json
EVG-20293
To help reduce some confusion around broken dependencies update the readme and introduce the `yarn clean` command
=> EVG-20293 Add yarn clean command and update readme

cypress/integration/subscription_modal.ts, cypress/integration/task/task_actions.ts, cypress/integration/version/task_filters.ts, cypress/integration/version/task_table.ts
EVG-20484
I found 2 more tasks that were duplicates and removed them
set module patch
https://spruce.mongodb.com/version/64b992767742aed8f7f187d5/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
https://github.com/evergreen-ci/evergreen/pull/6801
=> EVG-20484 Fix additional deduped tasks

yarn.lock
EVG-20523
Noticed a warning when starting the dev server about this being out of date.
=> EVG-20523 Bump caniuse-lite

src/analytics/activity/useActivityAnalytics.ts, src/analytics/addPageAction.ts, src/analytics/aprilFools/useAprilFoolsAnalytics.ts, src/analytics/breadcrumb/useBreadcrumbAnalytics.ts, src/analytics/hostsTable/useHostsTableAnalytics.ts, src/analytics/index.ts, src/analytics/joblogs/useJobLogsAnalytics.ts, src/analytics/navbar/useNavbarAnalytics.ts, src/analytics/patch/usePatchAnalytics.ts, src/analytics/patches/useProjectPatchesAnalytics.ts, src/analytics/patches/useUserPatchesAnalytics.ts, src/analytics/preferences/usePreferencesAnalytics.ts, src/analytics/projectHealth/useProjectHealthAnalytics.ts, src/analytics/projectSettings/useProjectSettingsAnalytics.ts, src/analytics/spawn/useSpawnAnalytics.ts, src/analytics/task/useAnnotationAnalytics.ts, src/analytics/task/useTaskAnalytics.ts, src/analytics/taskQueue/useTaskQueueAnalytics.ts, src/analytics/useAnalyticsAttributes.ts, src/analytics/useAnalyticsRoot.ts, src/analytics/useGetUserQuery.ts, src/analytics/version/useVersionAnalytics.ts, src/hooks/tests/usePolling.test.tsx
EVG-19319
Uses the same pattern from Parsley to memoize the analytics hooks.
=> EVG-19319: Memoize analytics hooks

cypress/integration/distroSettings/navigation.ts, cypress/integration/projectSettings/project_settings.ts, src/components/SearchableDropdown/SearchableDropdown.test.tsx, src/components/SearchableDropdown/index.tsx, src/gql/generated/types.ts, src/pages/distroSettings/DistroSelect/DistroSelect.test.tsx, src/pages/distroSettings/DistroSelect/index.tsx, src/pages/distroSettings/index.tsx
EVG-19941
This PR adds the distro dropdown.
https://github.com/evergreen-ci/spruce/assets/47064971/a826841a-fd21-4621-9c30-cab737a6ab78
- Added e2e tests
- Added Jest tests
=> EVG-19941: Add distro dropdown

.evergreen.yml, scripts/deploy/run-deploy.ts, scripts/deploy/utils/git/index.ts
EVG-20577
When we build on CI we add a few extra folders and files to the main spruce directory
=> EVG-20577 Remove clean working directory check for CI deploys

.evergreen.yml, src/gql/generated/types.ts
EVG-20617
Following up on our conversation this should reduce unnecessary uploads to the Cypress cloud service.
=> EVG-20617 Only upload to cypress if on a pr, mainline commit, or patch

src/components/MetadataCard.tsx, src/pages/configurePatch/configurePatchCore/__snapshots__/ConfigurePatchCore.stories.storyshot, src/pages/task/metadata/__snapshots__/Metadata.stories.storyshot, src/pages/version/BuildVariantCard/__snapshots__/BuildVariantCard.stories.storyshot, src/pages/version/BuildVariantCard/index.tsx
EVG-19922
- Use entirety of viewport height when showing sticky build variant card
=> EVG-19922: Increase build variant card height

src/gql/generated/types.ts, src/gql/queries/spruce-config.graphql, src/pages/projectSettings/tabs/PluginsTab/PluginsTab.tsx, src/pages/projectSettings/tabs/PluginsTab/getFormSchema.tsx
EVG-19784
Update description on plugins page to provide details about adding the Evergreen JIRA user for ticket creation
https://github.com/evergreen-ci/evergreen/pull/7048
=> EVG-19784: Add JIRA user info

cypress/integration/distroSettings/general_section.ts, cypress/integration/distroSettings/host_section.ts, cypress/integration/distroSettings/provider_section.ts, cypress/integration/distroSettings/task_section.ts, src/components/SpruceForm/errors.ts, src/gql/generated/types.ts, src/pages/distroSettings/Tabs.tsx, src/pages/distroSettings/tabs/GeneralTab/GeneralTab.tsx, src/pages/distroSettings/tabs/GeneralTab/getFormSchema.ts, src/pages/distroSettings/tabs/GeneralTab/transformers.test.tsx, src/pages/distroSettings/tabs/GeneralTab/transformers.ts, src/pages/distroSettings/tabs/GeneralTab/types.ts, src/pages/distroSettings/tabs/HostTab/getFormSchema.tsx, src/pages/distroSettings/tabs/HostTab/schemaFields.tsx, src/pages/distroSettings/tabs/ProviderTab/schemaFields.ts, src/pages/distroSettings/tabs/ProviderTab/styles.ts, src/pages/distroSettings/tabs/TaskTab/getFormSchema.ts
EVG-20995
I moved the permission updates into their own ticket: EVG-21009
- Add validation according to an audit against the legacy page that Minna and I conducted yesterday
- Also simplify General page ("Notes" having its own section felt unnecessary)
General settings updates:
- Update tests
=> EVG-20995: Improve distro settings validation

cypress/integration/nav_bar.ts, src/components/Content/index.tsx, src/components/Header/AuxiliaryDropdown.tsx, src/constants/externalResources.ts, src/constants/routes.ts, src/gql/generated/types.ts, src/hooks/index.ts, src/hooks/useFirstDistro.ts, src/hooks/useLegacyUIURL.ts, src/pages/distroSettings/DistroSelect/DistroSelect.test.tsx, src/pages/distroSettings/NavigationModal.tsx, src/pages/distroSettings/NewDistro/CopyModal.test.tsx, src/pages/distroSettings/NewDistro/CreateModal.test.tsx, src/pages/distroSettings/index.tsx, src/pages/host/Metadata.tsx, src/pages/task/metadata/index.tsx
EVG-19955
- Point all links to Spruce's distro settings instead of legacy
- Update "switch to legacy UI" link to work for distro settings
- Ungate page on production
=> EVG-19955: Release distro settings

src/pages/preferences/preferencesTabs/notificationTab/UserSubscriptions.tsx
EVG-19976
- When subscription is configured to comment on JIRA ticket, linkify the ticket number
=> EVG-19976: Linkify JIRA tickets in user subscriptions table

src/pages/projectSettings/tabs/ProjectTriggersTab/getFormSchema.ts
EVG-20987
Following up from the [previous](https://github.com/evergreen-ci/spruce/pull/2098) PR, this adds the push type to the trigger type dropdown
Confirmed locally
=> EVG-20987 Add push type to trigger dropdown

src/pages/task/taskTabs/buildBaronAndAnnotations/FileTicketButton.tsx
DEVPROD-938
When a user files a ticket, automatically refetch the ticket queries
=> DEVPROD-938: Refresh ticket queries when 'file ticket' is clicked

.evergreen.yml
=> DEVPROD-3720 switch to new module definition schema

src/components/Table/__snapshots__/BaseTable.stories.storyshot, src/pages/version/taskDuration/__snapshots__/TaskDurationTable.stories.storyshot
DEVPROD-802
Fixes broken snapshot tests on main
=> DEVPROD-802 Fix snapshots

cypress/integration/host/host_events.ts, src/pages/host/HostTable.tsx
DEVPROD-797
I just updated the table to use the most recent LeafyGreen table and the problem was fixed. This does not duplicate any work in the epic as the epic focuses on antd tables.
https://github.com/evergreen-ci/spruce/assets/47064971/db5cdb7a-c5bc-42c3-867a-d51db06f383f
- Updated Cypress test
=> DEVPROD-797: Update host events table

cypress/integration/nav_bar.ts, src/constants/externalResources.ts, src/gql/generated/types.ts, src/hooks/useLegacyUIURL.ts
DEVPROD-754
Almost forgot to remove the legacy UI link in the navbar for the distro settings page 😅
=> DEVPROD-754: Remove legacy UI link for distro settings

.evergreen.yml, scripts/deploy/create-evergreen-yml.sh
DEVPROD-4976
Use ec2.assume_role and its associated credentials.
- Tests should pass and successfully upload files to S3
=> DEVPROD-4976: Use temporary AWS credentials from ec2.assume_role command

src/pages/taskHistory/BuildVariantSelector.tsx
DEVPROD-946
The `BuildVariantSelector` will now trim search terms so that it will match more terms.
=> DEVPROD-946 Update BuildVariantSelector to trim search terms

src/pages/distroSettings/tabs/ProviderTab/schemaFields.ts
DEVPROD-3330
Adds clarifying units to throughput and size fields
=> DEVPROD-3330 Update title with unit for throughput and size fields in distro settings
