package-lock.json, package.json, src/components/app/App.tsx, src/components/patch/Patch.tsx, src/components/patch/PatchContainer.test.tsx, src/components/patch/PatchContainer.tsx
This set of changes includes adding logic to determine whether a patch should be expanded on rendering after changes occur somewhere on the page.
=> EVG-6411: Patch expand panels collapse when a new page of patches is loaded

src/components/patch/Patch.less, src/components/patch/PatchContainer.test.tsx, src/components/patch/PatchContainer.tsx
I'm still working on the styling for the expand all button (it's surprisingly hard to pin things to the bottom right of a div), but the functionality is all there. I also think it might be worth adding some code to one of the tests to confirm that the first page is in fact expanded on initial load, and another test to make sure that checking and unchecking the expand all button works. Let me know what you think.
=> EVG-6552: expand first page of patches by default and create expand all option

src/components/patch/Patch.tsx, src/components/patch/PatchContainer.test.tsx, src/components/patch/PatchContainer.tsx
**JIRA ticket:** https://jira.mongodb.org/browse/EVG-6830
Filtering on patches page was broken; the displayed patches were not being filtered based on the selected filters. This was due to multiple versions of the patches data being stored in state to represent all patches, filtered patches, and expanded patches. Having three different sources of truth for the state of the patches caused the state used to display the patches components to become out-of-sync. The changes in this PR remove the `visiblePatches` field from state. Filtering is now accomplished by filtering the patches on every re-render from `setState` based on the selected filters. Using this approach assures the the patches displayed in the UI are always in sync with the patches in state by having one source of truth for the …
=> EVG-6830: fix patches filter functionality

.evergreen.yml, .gitignore, cypress.json, cypress/integration/sample_spec.js, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, package-lock.json, package.json
- Install Cypress and write a sample test
- npm commands to open and run cypress
Having trouble running Cypress in Ubuntu 18.04 in the CI environment; therefore Cypress will only run locally for now. This will allow us to write e2e tests for the UI while the Ubuntu + Cypress issue is figured out. Once resolved, we can run all Cypress tests in the CI environment.
=> MCI-3108: Cypress tests run locally

package-lock.json, package.json, src/App.tsx, src/styles/app.ts
Add emotion library for adding css-in-js. The original plan was to add styled-jsx library, however that lib cannot be used with CRA without ejecting. 
The Cloud team and most other FE teams at Mongo swear by emotion, which is why I chose it.
=> EVG-7118: add emotion style lib

.gitignore, src/pages/Login.tsx
`location.state.referrer ?? "/"` was throwing a TypeError because `location.state` is undefined at some point in the render lifecycle
=> Fix getReferrer func

package-lock.json, package.json, src/App.tsx, src/components/Navbar/index.tsx, src/graphql/queries/get-projects.ts
=> EVG-7200: query for projects data

.evergreen.yml, config/.cmdrc_sample.json, cypress.json
The cypress tests still fail, likely due to how we're doing npm start rather than start:dev-server, but this fixes it so that we're actually running evergreen
=> MCI-3108 compile evg with correct go version

src/context/toast.tsx
change param type from `keyof typeof Toast` to `Toast` because it _does_ actually work
=> Change param to enum

package-lock.json, package.json, src/gql/GQLWrapper.tsx
https://jira.mongodb.org/browse/EVG-7139
Don't retry if the error is 401 (Unauthorized). Otherwise retry up to a maximum of 5 times where the initial delay is 300ms and subsequent delay times are randomized. The Retry link currently uses default params except for the `retryIf` field.
=> EVG-7139: Retry requests in case of network error

cypress/integration/test_table.js, cypress/utils/networking.js
This PR allows us to wait on specific gql operations in cypress with the `waitForGQL` function. Previously we've only been able to wait for the GQL endpoint without any visibility into which query we are waiting on, now we can wait on specific query operations.
=> EVG-7318: Allow Cypress to wait for specific GQL operations

cypress/integration/test_table.js, package-lock.json, package.json, src/gql/queries/get-task-tests.ts, src/pages/task/TestsTable.test.tsx, src/pages/task/TestsTableCore.tsx
This PR renders the logs column buttons and relies on https://github.com/evergreen-ci/evergreen/pull/3176.
My tests don't include verifying that a new tab has been opened after clicking on a Log column button because Cypress docs recommends against it. Instead they recommend to test the existence of attributes that would cause a new tab to open (https://docs.cypress.io/guides/references/trade-offs.html#Multiple-tabs). 
The `Buttons in log column should have target=_blank attribute` test may not pass until I insert some test results with log urls in our test server.
=> EVG-7210: Render Logs column in task page tests table

config/.cmdrc_sample.json, src/context/auth.tsx, src/utils/getEnvironmentVariables.ts
the login domain was originally being set using `getUiUrl` which was returning `localhost:3000`. However the ui url refers to the evergreen ui, which means `getUiUrl` should return `loclahost:9090` in dev/test and `evergreen.mongodb.com` in prod.
I broke the auth tests when i updated the return value of `getUiUrl` to be `localhost:9090` and realized that some additional logic was necessary to determine the domain used to make HTTP requests to `/login`.
This PR adds `getLoginDomain` to the env var utility functions. 
- add `REACT_APP_SPRUCE_URL` env var to dev in `.cmd-rc` file equal to `localhost:3000`
- if in de/test - return `REACT_APP_SPRUCE_URL`
- if in prod/staging - return `REACT_APP_UI_URL`
The dev server currently proxies all requests to `localhost:9090` from `localhost:3000`. …
=> get login domain based on env

cypress/integration/breadcrumbs.js, cypress/integration/patch-route.js, package-lock.json, package.json, src/contants/routes.ts, src/hooks/index.ts, src/hooks/types.ts, src/hooks/useDefaultPath.ts, src/hooks/useTabs.ts, src/pages/Patch.tsx, src/pages/Task.tsx, src/pages/patch/PatchTabs.tsx, src/pages/task/TestsTable.test.tsx, src/pages/task/TestsTableCore.tsx
https://jira.mongodb.org/browse/EVG-7485
**Tabs on the patch page:**
- default tab is `Tasks`
- selecting a tab updates the url path to include selected path name
- invalid tab names are replaced with default
Introduces two new hooks: `useTabs` and `useDefaultPath` that will be used by the /patch and /task routes.
=> EVG-7485: patch page tabs

.evergreen.yml, cypress/integration/breadcrumbs.js, cypress/integration/test_table.js, cypress/integration/test_table_route.js, src/components/Breadcrumb/index.tsx, src/gql/queries/get-task-tests.ts, src/pages/task/testsTable/TestsTableCore.tsx
`make local-evergreen` now seeds the `evergreen_local` db with all the data required to run e2e tests in ci. `make local-evergreen` is the db we will use from now on. 
[This back end PR](https://github.com/evergreen-ci/evergreen/pull/3271) must be merged before this front end PR
=> EVG-7481: use local evergreen in e2e ci tests

src/components/Breadcrumb/index.tsx, src/gql/queries/patch.ts, src/pages/Patch.tsx, src/pages/patch/Metadata.tsx, src/pages/patch/metadata/MetadataCard.tsx, src/pages/patch/patchTabs/tasks/TasksTable.tsx
Show loading skeletons on patch header and in metadata card
Display error message in metadata card and do NOT render breadcrumb and header
Normal view
=> EVG-7605: patch header and metadata loading and error views

cypress/integration/patch-route.js, src/gql/GQLWrapper.tsx, src/gql/queries/get-patch-tasks.ts, src/hooks/index.ts, src/hooks/useDisableTableSortersIfLoading.ts, src/pages/patch/patchTabs/Tasks.tsx, src/pages/patch/patchTabs/tasks/TasksTable.tsx, src/pages/task/testsTable/TestsTableCore.tsx
https://jira.mongodb.org/browse/EVG-7489
- When I click a task table header, sorted tasks are fetched and displayed corresponding to the clicked header
- `history.listen` is used to listen to updates to the url location
- when url location changes, the query params in url `search` are parsed and then fed to the gql `patchTasks` query as sorters
- new tasks are fetched with `fetchMore` from `useQuery` and the tasks table is updated with the new tasks
Fetch more tasks when user scrolls table: https://jira.mongodb.org/browse/EVG-7490
=> EVG-7489: fetch sorted tasks when patch headers are clicked

cypress/integration/code_changes_table.js, src/gql/queries/get-code-changes.ts, src/pages/patch/PatchTabs.tsx, src/pages/patch/patchTabs/CodeChanges.tsx
https://jira.mongodb.org/browse/EVG-7416
These code changes render code changes in the Patch page. The table does not have any pagination or sort capabilities. 
Check it out here: http://localhost:3000/patch/5e4ff3abe3c3317e352062e4/changes
Spruce:
Design: 
Next I'm working on the task page metadata panel.
=> EVG-7416: Render Code Changes in Patch page

cypress/integration/breadcrumbs.js, cypress/integration/page_tabs.js, cypress/integration/patch-route.js, src/pages/patch/patchTabs/CodeChanges.tsx, src/pages/patch/patchTabs/Tasks.tsx, src/pages/task/FilesTables.tsx, src/pages/task/testsTable/TestsTableCore.tsx
https://jira.mongodb.org/browse/EVG-7620
`Unhandled Rejection (Invariant Violation): ObservableQuery with this id doesn't exist` was caused by `fetchMore` processing a response after the component containing the useQuery has unmounted. 
This happens when switching between tabs because `history.listen` in the currently rendered component executes its callback fn (and fetchMore) with the new page route before unregistering the listener. 
To prevent the app from crashing I surrounded all calls to fetchMore  in history.listen callbacks with a try/catch. 
Another solution could have been to execute fetchMore only if the location variable in the history.listen callback matches the component route - this solution prevents a superfluous request from being made but would require parsing the …
=> EVG-7620: Prevent app crash when switching back and forth between page tabs

.evergreen.yml, README.md, package.json
`npm run start:dev-server` is just too darn long. I updated the README too with more explicit setup instructions.
=> EVG-7646: Change `npm run start:dev-server` to `npm run dev`

src/components/Typography/index.ts, src/components/styles/PageHeader.tsx, src/pages/Patch.tsx
=> EVG-7509: show patch status badge in header

cypress/integration/patch-route.js, src/components/PageTitle.tsx, src/components/TaskStatusBadge.tsx, src/components/styles/PageHeader.tsx, src/components/styles/index.ts, src/pages/Patch.tsx, src/pages/Task.tsx, src/pages/patch/patchTabs/tasks/TasksTable.tsx
https://jira.mongodb.org/browse/EVG-7395
This PR is mostly refactoring the TaskStatusBadge so we can use it on the task page as well as the task table.
=> EVG-7395: Task page title and status badge

src/gql/queries/get-task-files.ts, src/pages/task/FilesTables.tsx
https://jira.mongodb.org/browse/EVG-7633
These frontend changes reflect gql schema changes to include the fileCount in the taskFiles query result. Backend PR can be viewed here: https://github.com/evergreen-ci/evergreen/pull/3384
=> EVG-7633: adjust to taskFiles query schema changes

cypress/integration/patch-route.js, cypress/integration/test_table.js, cypress/integration/test_table_route.js, src/pages/task/TestsTable.test.tsx, src/pages/task/TestsTable.tsx, src/types/task.ts
https://jira.mongodb.org/browse/EVG-7617
Tests table now uses sortBy, sortDir and ASC/DESC instead of category, sort and 1/-1
=> EVG-7617: Make url query params between patch and task pages the same

src/context/auth.tsx
https://jira.mongodb.org/browse/MCI-3198
All of the problems with staging were around CORS and the login/logout endpoints. 
**Cause of problem:** UI was waiting for successful response from server before dispatching the `deauthenticate` action. Response from server was a CORS errors and therefore the ui showed a loading screen indefinitely. 
**Fix:** dispatch `deauthenticate` before receiving response from server. This way, if there is any issue communicating with the server, the ui still shows the right page instead of endlessly loading. 
This is due to the login and logout endpoints not supporting CORS. This is fixed in an evergreen PR [here](https://github.com/evergreen-ci/evergreen/pull/3443)
=> MCI-3198: staging should work now

src/pages/patch/patchTabs/tasks/TasksTable.tsx
https://jira.mongodb.org/browse/EVG-7757
**View an example in staging:** 
http://evergreen-staging.spruce.s3-website-us-east-1.amazonaws.com/patch/5e8e501db2373609ecbd7000/tasks
=> EVG-7757: (task table) show no status badge if status is empty

src/gql/queries/get-patch-tasks.ts
https://jira.mongodb.org/browse/EVG-7795
Patch status badge for success was showing gray color because the `Patch.Success` enum value was set to 'success'. 
Fix: 'success' => 'succeeded'
See an example in staging: 
http://evergreen-staging.spruce.s3-website-us-east-1.amazonaws.com/patch/5e8f413097b1d363114d60ad/tasks
=> EVG-7795: (patch) change patch success status to `succeeded`

cypress/integration/my_patches.js, src/components/styles/Layout.tsx, src/components/styles/filters.tsx, src/components/styles/index.ts, src/gql/queries/get-patch-tasks.ts, src/gql/queries/my-patches.ts, src/pages/MyPatches.tsx, src/pages/Patch.tsx, src/pages/my-patches/StatusSelector.tsx, src/types/build.ts, src/types/patch.ts
https://jira.mongodb.org/browse/EVG-7547
https://jira.mongodb.org/browse/EVG-7548
URL will update when inputs are interacted with and GQL query will be made. 
There are not many e2e tests for these code changes because the My Patches page is still being developed. The PR to include the virtualized list and Patch card 
(https://jira.mongodb.org/browse/EVG-7552 & https://jira.mongodb.org/browse/EVG-7551) will allow me to test the full user story in cypress - from input interaction -> url update -> rendered results.
=> EVG-7547, EVG-7548: search input for patch name & dropdown menu for statuses

cypress/integration/patch-route.ts, cypress/integration/patch/configure-patch.ts, src/pages/ConfigurePatch.tsx, src/pages/configurePatch/ConfigurePatchCore.tsx
@khelif96 uncovered an error when he was redirected to the configure page for a patch whose project had no variants and no tasks. This broke the page because it expects all patches to be associated with a project that has variants and tasks. 
**It is very unlikely that this can happen in production, but I added this check to safeguard against this error.** 
This will be changed to a full page banner error when I do the ticket to create the banners.
=> EVG-7906: show full page error if patch has no variants or tasks

cypress/integration/patch-route.ts, src/components/Navbar/index.tsx, src/gql/generated/types.ts, src/gql/queries/patch.ts, src/pages/patch/Metadata.tsx
Show commit queue position and link to commit queue page
Due to cq data not being in local evergreen
[This PR](https://github.com/evergreen-ci/evergreen/pull/3558) must be merged for tests to pass
=> EVG-7511: render commit queue position in patch metadata

src/hooks/index.ts, src/hooks/tests/useSetColumnDefaultSortOrder.test.ts, src/hooks/useSetColumnDefaultSortOrder.ts, src/pages/patch/patchTabs/Tasks.tsx, src/pages/patch/patchTabs/tasks/TasksTable.tsx, src/pages/task/testsTable/TestsTableCore.tsx
https://jira.mongodb.org/browse/EVG-7838
useSetColumnDefaultSortOrder handles setting the defaultSortOrder for the antd table column prop. I refactored the TasksTable so getQueryVariables is available in the same file as the columns in order to get the sort direction and sort category for the defaultSortOrder.
=> EVG-7838: set initial state for table sorters 

src/pages/preferences/preferencesTabs/cliTab/AuthenticationCard.tsx, src/utils/request.test.js, src/utils/request.ts
Used the already existing api route for this. 
Created some request util functions for traditional post requests to evergreen.
They wrap `axios.post()` but include some error handling and some other boiler plate code we might have to write ourselves.
Still waiting to test this on staging.
=> EVG-8079 Add ability to Reset an api key

src/pages/patch/patchTabs/Tasks.tsx, src/pages/task/testsTable/TestsTableCore.tsx
Descreased from 80 to 8. 80 is way too many and was causing the page to jump when using the filters because it would increase the size of the page.
=> EVG-8114: massively decrease amount of rows shown for loading table

src/constants/externalResources.ts, src/gql/generated/types.ts, src/gql/queries/get-client-config.ts, src/gql/queries/index.ts, src/pages/preferences/preferencesTabs/cliTab/DownloadCard.tsx
The download links for the cli binaries are now fetched from the evergreen backend. Since not every one has the same evergreen binaries on their system some download links will be disabled locally. Prod should have all the evergreen binaries and all the download links should work. 
Dependent on this.
https://github.com/evergreen-ci/evergreen/pull/3637
=> EVG-8075 Use queried download links instead of static ones

src/components/styles/Layout.tsx
=> EVG-8036: fix patch & task action buttons smooshed text

src/gql/generated/types.ts, src/gql/queries/get-patch-task-statuses.ts, src/gql/queries/index.ts, src/pages/patch/patchTabs/tasks/TaskFilters.tsx, src/utils/statuses/getCurrentStatuses.test.ts, src/utils/statuses/getCurrentStatuses.ts
Only show patch task statuses that are relevant to the patch. As the task statuses change, so do the dropdown options. 
I made `getCurrentStatuses` a util so it can be used for the task dropdown filters too
=> EVG-8021: dynamically show patch task statuses in dropdown

cypress/integration/patch/task-table.ts, src/hooks/usePollQuery.ts, src/pages/UserPatches.tsx, src/pages/patch/patchTabs/Tasks.tsx, src/pages/task/testsTable/TestsTableCore.tsx, src/pages/userPatches/PatchCard.tsx
https://jira.mongodb.org/browse/EVG-8154
the loading state for tables using the usePollQuery hook is true from the time a diff occurs query variables to when the loading state goes from true to false. the loading skeleton was being persisted because the loading state never went from true to false. 
the condition on line 87 prevented a new query from being created in scenarios where we push a default path the URL. this was here originally to prevent dispatching queries on the wrong page but I see now that it didn't work as intended.
something interesting about the apollo useQuery refetch function is that it will throw an error if called when the parent component with the useQuery hook unmounts. I added a clearInterval in the catch block to make sure we always stop the active query when the …
=> EVG-8154: prevent loading skeleton persisting

src/utils/request.test.js, src/utils/request.ts
Fix failing tests for #206 
Updated these tests to remove their dependency on console.log()
=> Remove console statements from request test

cli-scripts/deploy-prod.js, package-lock.json, package.json
Added safety to prevent accidental prod deploys while keeping it just as simple and easy as before. 
Running `npm run deploy:prod` from a branch that is not master will exit the shell script.
Running `npm run deploy:prod` from master will prompt the user for yes/no before running the production deploy script.
=> EVG-8193: script for safer prod deployment

src/pages/preferences/preferencesTabs/cliTab/VerifyCard.tsx
Because of https://github.com/evergreen-ci/evergreen/commit/59f50141ee548614ee33feabcdeefd5e9e79cd6d we no longer will have this metadata from get-update.
First spruce PR!! 😱
=> EVG-7935 use plain logger for get update

src/pages/patch/patchTabs/CodeChanges.tsx
[EVG-8178](https://jira.mongodb.org/browse/EVG-8178)
=> EVG-8178 Navigating to "RAW" link in patch configuration does not open new window and clears task selections

src/pages/task/testsTable/TestsTableCore.tsx
https://jira.mongodb.org/browse/EVG-8105
sometimes the name column is wide enough to make the other columns unreadable and unusable. this issue only occurred for the tests table not the tasks table, code changes nor files table
before:
after:
=> EVG-8105: Task page: set max width on display name part of tables

package-lock.json, package.json
[EVG-8235](https://jira.mongodb.org/browse/EVG-8235)
Updated leafygreen tooltip to 3.3.2
the following warning appeared when upgrading:
=> EVG-8235 Build variant tooltip doesn't appear over variant square

package-lock.json, package.json, src/pages/Task.tsx
Fixes an issue where really long log lines causes the page to overflow.
before: 
after:
Testing instructions:
Easiest way to test this would be to checkout this branch.
Use the version of the `.cmdrc.json` that lets you access prod data locally.
open a task with long logs and to compare what is currently in prod to what shows up locally 
The version on this branch should not have a horizontal page scroll
Prod task with a line with really long logs.
https://spruce.mongodb.com/task/sqlproxy_full_matrix__os_full_matrix~osx_mongodb_version~latest_mongodb_topology~standalone_module_tests_patch_129f80fcf3b75ecb4f8f24ecbb1ba2b5d7dc1a3e_5efa177e3e8e86592c495ab0_20_06_29_16_32_00/logs
Same task but viewable locally (You need to be using prod backend) …
=> EVG-12534 Fix log wrapper

cypress/integration/patch/configure-patch.ts, package-lock.json, package.json, src/pages/configurePatch/ConfigurePatchCore.tsx, src/pages/configurePatch/configurePatchCore/ConfigureBuildVariants.tsx, src/pages/configurePatch/configurePatchCore/ConfigureTasks.tsx, src/pages/patch/patchTabs/Tasks.tsx
https://jira.mongodb.org/browse/EVG-12503
These code changes fix a bug where the task checkboxes remain unselected after clicking a checkbox.
This bug was being caused by passing an improperly formatted 2nd parameter to `lodash.get` in the `getTaskCheckboxState` state function which caused the `getTaskCheckboxState` to always return "unchecked" for task names with periods.
=> EVG-12503: Task checkboxes remain unselected after clicking

cypress/integration/hosts/hosts-page-default.ts, src/components/Content/index.tsx, src/constants/routes.ts, src/gql/generated/types.ts, src/gql/queries/hosts.ts, src/gql/queries/index.ts, src/pages/Hosts.tsx, src/pages/Patch.tsx, src/pages/patch/patchTabs/Tasks.tsx
1. Hosts route
2. Hosts page minimal layout (page title & table)
3. GQL query to fetch hosts - pagination and filtering coming in subsequent PRs
4. E2E tests for the default hosts page - renders hosts sorted by status
I will be doing the PRs for the hosts page in as small fragments as possible, beginning with this barebones hosts page that includes the title and hosts table. 
Subsequent PRs include pagination, sorting, filtering and all the other UI represented in these beautiful mockups: https://mongodb.invisionapp.com/share/C2WKQWRWG5Y#/screens/424885145
I will also be merging the unfinished page into master. There is no link or entry point to the hosts page in the new UI so I do not expect users to accidentally stumble onto it. 
The tests in this PR depend on local evergreen hosts data …
=> EVG-12613: hosts page barebones table

package-lock.json, package.json, src/components/Button/index.tsx, src/components/Checkbox/CheckboxGroup.tsx, src/components/Checkbox/index.ts, src/components/Table/Filters.tsx, src/hooks/index.ts, src/hooks/tests/useTableFilters/TestComponent.tsx, src/hooks/tests/useTableFilters/useTableFilters.test.tsx, src/hooks/useFilterInputChangeHandler.ts, src/hooks/useTableFilters.ts, src/utils/url/index.ts, src/utils/url/updateUrlQueryParam.ts
https://jira.mongodb.org/browse/EVG-12527
- CheckboxGroup component used for filtering statuses
- The table filter dropdown UI for selecting filters, update button and reset button
- Hooks used to store filter state and update url query params
- Jest integration tests that test the UI and the table filter hooks together
Adding the UI and hooks introduced in this PR to the hosts table
=> EVG-12527: reusable table filters

cypress/integration/my-patches/patch-card/dropdown-menu.ts, cypress/integration/patch/action-buttons.ts, cypress/integration/patch/task-table.ts, src/analytics/patch/usePatchAnalytics.ts, src/components/PatchActionButtons/EnqueuePatch.tsx, src/components/PatchActionButtons/index.tsx, src/gql/generated/types.ts, src/gql/mutations/enqueue-patch.ts, src/gql/mutations/index.ts, src/gql/queries/my-patches.ts, src/gql/queries/patch.ts, src/pages/Patch.tsx, src/pages/patch/ActionButtons.tsx, src/pages/userPatches/PatchCard.tsx, src/pages/userPatches/patchCard/DropdownMenu.tsx
Just a cherry-pick of the changes from #281 which were reverted (in error) by 46961e3.
The supporting backend changes have already been restored (https://github.com/evergreen-ci/evergreen/pull/3848)
=> EVG-7952 enqueue a patch

cypress/integration/hosts/select-hosts.ts, src/gql/generated/types.ts, src/gql/mutations/index.ts, src/gql/mutations/restart-jasper.ts, src/pages/Hosts.tsx, src/pages/hosts/HostsTable.tsx
https://jira.mongodb.org/browse/EVG-12525
https://jira.mongodb.org/browse/EVG-12523
https://jira.mongodb.org/browse/EVG-12524
- able to select host table rows
- selecting rows displays hosts selection data & action button
- can restart jasper for selected hosts
- update status coming in future PR (requires modal)
The checkboxes in the table are not the Leafygreen checkboxes. Rendering a custom checkbox requires upgrading to ANTD v4, which i believe there is a ticket for but i cannot find it in the backlog. I have designer approval on this.
=> EVG-12525: show hosts selection data when hosts are selected

cypress/integration/hosts/hosts-filtering.ts, src/components/Table/Filters.tsx, src/hooks/tests/useTableFilters/useTableFilters.test.tsx, src/hooks/useTableFilters.ts
https://jira.mongodb.org/browse/EVG-12697
https://jira.mongodb.org/browse/EVG-12699
- Table dropdown input filters call `update` function when Enter key is pressed
- Trim whitespace from input filter values when calling `update` function so that values like `   centos6-perf       ` are still valid
=> EVG-12697: useTableFilters - call update fn when enter key is pressed & trim whitespace

src/pages/Hosts.tsx, src/pages/hosts/HostsTable.tsx
https://jira.mongodb.org/browse/EVG-12728
- Table columns now have a width property, which prevents column width shifting depending on content size
- I removed the skeleton loading indicator for the table and replaced it with the native antd table loader. The skeleton loader would flash briefly on the screen, creating a flashing effect.
=> EVG-12728: fixed width columns and loading

cypress/integration/hosts/update-status-modal.ts, src/components/Hosts/UpdateStatusModal.tsx, src/types/host.ts
according to [this code](https://github.com/evergreen-ci/evergreen/blob/master/api/host.go#L32-L39), these are the valid statuses to which a host can be updated
=> EVG-12520: valid host statuses

src/gql/generated/types.ts, src/gql/queries/get-task-all-executions.ts, src/pages/task/executionDropdown/ExecutionSelector.tsx, src/utils/string/index.ts
The problem was that the ingest (creation) time is always set to when the task was first created (ie. patch was scheduled). The activated time will be when it was restarted, though it can change if it gets unscheduled/rescheduled I think. Also made some improvements to the date formatting
=> EVG-12918 adjust time format for execution dropdown

src/gql/generated/types.ts, src/pages/spawn/spawnHost/SpawnHostTable.tsx
@malikchaya2  noticed that typescript broke after the Host type was changed in this pr https://github.com/evergreen-ci/evergreen/pull/3980 This pr should resolve the typescript errors.
=> Properly type prop

cypress/integration/taskQueue/route.ts, package-lock.json, src/pages/taskQueue/TaskQueueTable.tsx
https://jira.mongodb.org/browse/EVG-13082
Currently, the Spruce workflow is only officially supported for patch builds. However, the links to the patch details from the Task Queue page lead to Spruce both for patch builds and for mainline commits.
Task link should go to legacy UI if task type is `commit`
=> EVG-13082: task link in task queue item goes to legacy UI for mainline commits

cypress/integration/task_route.ts, src/pages/Task.tsx
The previous commit on this ticket exposed an existing bug where we would replace the URL search on the task page. Also removed a test that is no longer relevant now that the default tab is dynamic
This should fix the e2e tests
=> EVG-8181 preserve query part of url on task page

src/hooks/useFilterInputChangeHandler.ts, src/hooks/useTabs.ts, src/pages/patch/BuildVariants.tsx, src/pages/patch/buildVariants/GroupedTaskSquare.tsx, src/pages/patch/patchTabs/Tasks.tsx
Further changes on the build variant grid. The squares are now rectangular and smaller. 
And clicking on a status filters for that specific variant
=> EVG-13179 Update build variant design and allow for filtering by variant on status

src/components/Spawn/ExpirationField.tsx, src/components/Spawn/Layout.tsx, src/components/Spawn/index.tsx, src/pages/spawn/spawnHost/EditSpawnHostModal.tsx, src/pages/spawn/spawnHost/editSpawnHostModal/useEditSpawnHostModalState.ts, src/pages/spawn/spawnHost/fields/5-userTagsField.stories.tsx, src/pages/spawn/spawnHost/fields/UserTagsField.test.tsx, src/pages/spawn/spawnHost/fields/UserTagsField.tsx, src/pages/spawn/spawnHost/fields/VolumesField.tsx, src/pages/spawn/spawnHost/fields/index.ts, src/pages/spawn/spawnHost/spawnHostModal/HostDetailsForm.tsx
https://jira.mongodb.org/browse/EVG-13230
These code changes allow us to be more specific about information processed in our reducer functions. It also enables us to only ever have expand the host state object in our reducer function instead of within our React function components. A possible next step could be to incorporate useReducer for our Spawn Host Modal.
=> EVG-13230: Clean up useEditSpawnHostState reducer types and make HostExpirationFields a shared component

.evergreen.yml, package-lock.json, package.json
This pr adds a tool which generates a bundle analysis. This should help us understand how changes we make such as adding dependencies affect our overall bundle size, and in turn affect the loading times of spruce.
The compile task in evergreen now generates this source map automatically and it can be access in the files tab of that task
=> Add script to analyze bundle sizes

README.md, config/.cmdrc_sample.json, package-lock.json, package.json, src/components/PerfPlugin/TrendChartsPlugin.tsx, src/components/PerfPlugin/index.ts, src/pages/Task.tsx, src/pages/task/TrendCharts.tsx
There's still some work to be done before Trend Charts are complete so we're still going to leave it off for now. When the final feature PR is in, we'll have to add the prod url to the settings
=> EVG-12870: Add trend charts to Spruce task page

src/gql/generated/types.ts, src/gql/queries/get-spruce-config.ts, src/pages/spawn/spawnHost/SpawnHostModal.tsx, src/pages/spawn/spawnHost/SpawnHostTable.tsx, src/pages/spawn/spawnVolume/SpawnVolumeButton.tsx
This pr makes spruce use a queried value for the spawn volume limit.
and has some general improvements mainly for the spawn host modal. 
Some fields are now auto populated such as awsregions and public keys. The distros dropdown now filters the distro's based on the input.
dependent on https://github.com/evergreen-ci/evergreen/pull/4111
=> EVG-13320 Use volume limit for spawn volume page + misc improvements

package-lock.json, package.json
https://jira.mongodb.org/browse/EVG-13084
the issue originated in the rc-picker which antd relies on. updating antd pulls in a more recent version of the rc-picker which fixes the issue.
=> EVG-13084: update antd to show date picker month label

jest.config.js, package-lock.json, package.json, src/pages/spawn/spawnVolume/spawnVolumeButton/SpawnVolumeModal.test.tsx, src/setupTests.ts
https://jira.mongodb.org/browse/EVG-13325
This PR fixes the jest test flake by using the `waitFor` fn exported by `test-utils`. `waitFor` depends on the `MutationObserver` constructor which is unavailable with our current installed version of jsdom so I polyfilled it. The latest version of jsdom, which provides the polyfill, is available from react-scripts v4 however when I attempted to update react-scripts, there were non-trivial dependency issues so I found installing the polyfill directly the cleanest solution. We currently have a version of Jest and eslint installed in our package.json devDependencies. We should carefully remove these dependencies and rely on the installation react-scripts provides when we are ready to upgrade to react-scripts v4 (unless we decide to do something …
=> EVG-13325: Fix Create Volume Modal jest test flake

cypress/integration/task_actions.ts, src/components/LinkToReconfigurePage.tsx, src/components/PatchActionButtons/UnschedulePatchTasks.tsx, src/pages/patch/ActionButtons.tsx, src/pages/task/ActionButtons.tsx
- Add a patch/task dropdown option to disable the patch/task
- Make the patch dropdown options Sentence case to be consistent
- Enable + fix the task action tests. I'm not sure why they were disabled
Note that displaying the disabled status is a separate ticket: https://jira.mongodb.org/browse/EVG-13096
=> EVG-12443 add dropdown option to disable task

src/components/Spawn/MountVolumeSelect.tsx, src/pages/spawn/spawnHost/EditSpawnHostButton.tsx
This pr disables the ability to edit a spawn host if it is not in the running or started status. This is to prevent changes to the state of a spawned host while it is being initialized which might cause it to be in an unpredictable state.
=> EVG-13378 Dont allow user to edit spawn host if it is not running or started

src/pages/spawn/SpawnVolume.tsx, src/pages/spawn/spawnHost/EditSpawnHostModal.tsx, src/pages/spawn/spawnHost/SpawnHostActionButton.tsx, src/pages/spawn/spawnHost/SpawnHostModal.tsx, src/pages/spawn/spawnVolume/spawnVolumeButton/SpawnVolumeModal.test.tsx, src/pages/spawn/spawnVolume/spawnVolumeButton/SpawnVolumeModal.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/DeleteVolumeBtn.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/UnmountBtn.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/editButton/EditVolumeModal.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/mountButton/MountVolumeModal.tsx
https://jira.mongodb.org/browse/EVG-8030
These code changes:
1. add a skeleton to the Spawn Volume page
2. add query polling the Spawn Volume page
3. clear error banners after successful mutations
4. shows an error banner of the MyVolumes query fails
5. prevents accessing undefined data fields that could result from the MyVolumes from failing
6. adjusts the confirm button copy in the Edit Host Modal while the mutation is in flight
=> EVG-8030 & EVG-13380: Add a loading state to spawn pages & Show error banner when MyVolumes query fails

src/components/styles/StyledTabs.tsx, src/pages/patch/patchTabs/CodeChanges.tsx
This PR adds the total code changes to the changes tab.
It also fixes the padding on the leafygreen tabs that was broken when we update @leafygreen-ui/tabs
=> EVG-12541 Add total code changes and fix tabs padding

src/pages/patch/BuildVariants.tsx
https://jira.mongodb.org/browse/EVG-13386
When variant link is clicked in the Build Variants metadata on the patch details page, surround variant with `^$` to match variants strictly by the variant clicked. 
Variants
- e2e_local
- e2e_local_with_daemon
`e2e_local` variant link is clicked => filter variants strictly by `e2e_local`, do not show variants that include `e2e_local` (i.e. `e2e_local_with_daemon`)
=> EVG-13386: use strict regex when variant link clicked

src/App.tsx, src/components/Content/index.tsx, src/context/auth.tsx, src/gql/GQLWrapper.tsx, src/pages/userPatches/PatchCard.tsx
https://jira.mongodb.org/browse/EVG-12889
these code changes remove unnecessary async syntax, decrease the number of GQLWrapper renders from 3 to 2 and replace an `a` tag with a react router link
=> EVG-12889: Simplify GQLWrapper and decrease the number of renders

package.json, src/components/styles/StyledTabs.tsx, src/pages/Task.tsx, yarn.lock
With the recent update of leafygreen tabs and some clever conditionals we can now properly render conditional tabs in the task page.
This should allow us hide the tabs that aren't relevant to the task at hand. So the user facing changes would be if the build baron or trend charts plugin aren't available for a task the associated tab wont show. 
Standard Task
Task with build baron
Task with trend charts
=> EVG-13587 Conditionally render task tabs

src/analytics/addPageAction.ts, src/analytics/patch/usePatchAnalytics.ts, src/pages/patch/patchTabs/tasks/TasksTable.tsx
I added back the console.logs for analytics since they are useful when testing analytics locally. And they wont show up in production.
=> EVG-13701 Add analytics for display task dropdown

cypress/integration/patch/patch-route/patch-modal.ts, cypress/integration/patch/task-table.ts
https://github.com/evergreen-ci/evergreen/commit/cdccf100650cba4409a2444d63711d37cc998464 added a task which broke the counts. We should probably make this test more resilient, but for now this should make things green
=> EVG-13570 fix tests

cypress/integration/task/annotations.ts, src/components/BuildBaronAndAnnotations/AnnotationTickets.tsx, src/components/BuildBaronAndAnnotations/AnnotationTicketsTable.tsx, src/components/BuildBaronAndAnnotations/BuildBaron.tsx, src/components/BuildBaronAndAnnotations/BuildBaronContent.tsx
This change builds on EVG-13170, so I branched off of that branch. When reviewing this PR, please filter commits to only view the ones after the first one. (I will hold off merging, and only merge the new changes after the  EVG-13170 has been merged).
=> EVG-13169 Let users move between Issues and Suspect Issues on the UI

src/gql/GQLWrapper.tsx, src/utils/errorReporting.ts
Graphql errors no longer throw a bugsnag error and instead reported as a proper error as well as include some additional metadata
Instead of throwing a notify error
=> EVG-13316 Track gql errors in bugsnag properly and fix the notify error

src/pages/patch/patchTabs/Tasks.tsx
I had done a slight refactor of the query to return the base status as part of a base task object, but forgot to switch the data field the column was looking for
=> EVG-13365 fix gql field used for base status

cypress/integration/patch/task-table.ts, src/pages/patch/patchTabs/Tasks.tsx
This changes the default for base status from ascending to descending, so that new bugs default to the top
=> EVG-13365 sort new bugs to the top on patch page

src/gql/generated/types.ts, src/gql/mutations/file-jira-ticket.ts, src/pages/task/taskTabs/buildBaronAndAnnotations/BBCreatedTickets.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/BBFIleTicket.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/BuildBaron.test.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/BuildBaronContent.tsx
I ended up using the same backend function for both methods, so there was not much reconfiguration needed on the UI. 
Depends on [4357](https://github.com/evergreen-ci/evergreen/pull/4357) (Merged)
=> EVG-13171 Reconfigure the file ticket button on the UI

src/pages/task/taskTabs/testsTable/TestsTableCore.tsx
DO NOT MERGE until https://github.com/evergreen-ci/evergreen/pull/4405 is deployed. And the testresults query is confirmed fixed.
=> EVG-13965 Reenable polling for tests table

src/components/DatePicker.tsx, src/components/TimePicker.tsx
The babel plugin that automatically loads the styles for antd components doesn't catch the date picker and time picker components. Most likely since we use a utility function to build our own custom versions of these components. This imports the styles manually.
=> EVG-14094 Load date picker and time picker css manually

cypress/integration/task_route.ts, cypress/integration/test_table.ts
I accidentally committed this a while back and  muted all the tests locally
=> EVG-13726 Reenable cypress tests

src/pages/task/taskTabs/buildBaronAndAnnotations/BuildBaronContent.tsx
It looks like this is the only unsafe reference of bbData we have.
=> EVG-13928 check if bbData is undefined

package.json, tsconfig.json, yarn.lock
This will add styled component css checks to our linting process to ensure we dont accidentally add any invalid css styles.
You will also get intellisense support on your css..
This along side the [vscode-styled-component](https://github.com/styled-components/vscode-styled-components) plugin will help us write better css when we need to
=> Add typescript linting for styled components

src/constants/externalResources.ts, src/pages/task/taskTabs/testsTable/TestsTableCore.tsx
https://jira.mongodb.org/browse/EVG-14607
htmlDisplayURL comes from TestLog.HTMLDisplayURL in EVG and sometimes resembles a lobster link with the incorrect base
=> EVG-14607: point to evergreen lobster instead of logkeeper lobster in tests table

cypress/integration/host/host_events.ts, cypress/integration/hosts/update_status_modal.ts, cypress/integration/myPatches/my_patches.ts, cypress/integration/patch/configure_patch.ts, cypress/integration/project/patches.ts, src/pages/configurePatch/ConfigurePatchCore.tsx, src/pages/configurePatch/configurePatchCore/ConfigureBuildVariants.tsx, src/pages/configurePatch/configurePatchCore/ConfigureTasks.tsx, src/pages/configurePatch/configurePatchCore/state.ts, src/pages/host/HostTable.tsx, src/pages/patch/patchTabs/ParametersContent.tsx, src/utils/array/array.test.ts, src/utils/array/index.ts
I tracked down some of the failures to some changes that were made in Johns PR due to some data changing.
Some of the failures were a result of evergreen returning a host query slower then usual which caused an element to not be clickable. I resolved this by asserting the element is clickable.
I also did some refactoring on the configure patch page to make the state management more readable and maintainable. 
I also noticed some broken behavior with the indeterminate state handling for partially selected tasks, caused by the leafygreen checkbox component. I ommited that for now but will be fixing them in a follow up ticket once leafygreen makes the changes they need to. That work is tracked in https://jira.mongodb.org/browse/EVG-14652 and https://jira.mongodb.org/browse/PD-1386 According …
=> EVG-14632 Fix Failing cypress tests and Refactor Configure patch page

cypress/integration/patch/configure_patch.ts, src/gql/generated/types.ts, src/hooks/usePatchStatusSelect.ts
This is the corresponding pr to https://github.com/evergreen-ci/evergreen/pull/4663
This just updates some type names that were changed. 
This doesn't need to be deployed along side the back end pr. All this changes is some types. Which only really affect local development.
=> EVG-13946 Update types for mainline commits pr

cypress/integration/commit_queue.ts, src/pages/commitqueue/CommitQueueCard.tsx
Reverting the change to remove the commit queue remove patch button, since non-existent PRs on the commit queue should no longer exist.
=> EVG-14418 restore ability to remove patch from commit queue cards

src/components/Loading/PatchAndTaskFullPageLoad.tsx
[EVG-14587](https://jira.mongodb.org/browse/EVG-14587)
Removed the random semicolon on spruce loading page
=> EVG-14587 Removed Extra Semicolon

cypress/integration/patch/configure_patch.ts, src/pages/configurePatch/ConfigurePatchCore.tsx
[EVG-14694](https://jira.mongodb.org/browse/EVG-14694)
This auto selects required tasks on the configure patch page. This used to work but was removed in a past change.
It depended on the [variantsTasks patch field](https://github.com/evergreen-ci/evergreen/blob/4071b3c5984744e3a71589c95445d89f6db446be/graphql/schema.graphql#L490) which only returned required tasks.
It was replaced  by the [Patch.Project.variants](https://github.com/evergreen-ci/evergreen/blob/4071b3c5984744e3a71589c95445d89f6db446be/graphql/schema.graphql#L532) field which returns all the tasks for a patch. 
There was the assumption that these fields were the same and only one was needed but they aren't and they both are.
Local testing and added cypress tests
Related to/ Dependent on …
=> EVG-14694 Auto select required tasks in configure patch page

cypress/integration/patch/patch_route.ts, src/components/DisplayModal.tsx, src/components/FilterBadges/SeeMoreModal.tsx, src/pages/patch/ParametersModal.tsx
[EVG-14560](https://jira.mongodb.org/browse/EVG-14560)
- Discussed with Mohamed and [EVG-14754](https://jira.mongodb.org/browse/EVG-14754) has been opened to convert Spruce's more advanced modals to LeafyGreen's [Confirmation Modal](https://www.mongodb.design/component/confirmation-modal/example/). This ticket just handles basic display modals with no actions.
=> EVG-14560: Replace display modal instances

src/gql/generated/types.ts, src/gql/queries/get-mainline-commits.graphql, src/gql/queries/index.ts, src/pages/Commits.tsx
[EVG-14768(https://jira.mongodb.org/browse/EVG-14768)
* Create graphql query called get-mainline-commits
* Use projectId to query mainline commits on the waterfall page
Tried the query on playground
=> EVG-14768 Mainline Commits Query Fetch From UI

.evergreen.yml, scripts/test.js
EVG-14782
- Ensure test results are visible in Evergreen: write jest-junit output to `bin/jest/` and upload this asset
- Apply formatting & ESLint recommendations to `scripts/test.js` caught by the precommit hook
- E2E tests appear to be failing unrelatedly -- perhaps due to https://github.com/evergreen-ci/evergreen/pull/4673 and the earlier revert?
"Tests" tab no longer reports 0 tests:
=> EVG-14782: Fix Jest config on Evergreen

src/components/Content/index.tsx, src/constants/announcementToast.ts, src/context/toast.tsx, src/hooks/useAnnouncementToast.ts
EVG-14898 cc @mvankeulen94 
- Add hook for setting an announcement toast. The hook utilizes a cookie to check if the user has already dismissed the toast and hides it if so.
- Extend toasts to set custom titles and call an `onClose` function
- Announcement toast content is set in `constants/announcementToast.ts`. The toast is removed by setting this variable to `null` — this approach feels slightly haphazard so let me know if you have any other ideas!
- Will update #777 to set the appropriate toast once this is merged in.
- To test locally, set `toastData` in `constants/announcementToast.ts` to something like this:
```js
export const toastData: AnnouncementToast | null = {
closable: true,
message: "Placeholder navigation copy text.",
title: "Navigation Update Toast",
variant: "note",
}; …
```
=> EVG-14898: Add announcement toast interface

src/pages/commits/CommitsWrapper.tsx, src/pages/commits/commitChart/Grid.stories.tsx, src/pages/commits/commitChart/Grid.tsx, src/pages/commits/commitChart/__snapshots__/CommitChart.stories.storyshot, src/pages/commits/commitChart/__snapshots__/Grid.stories.storyshot
[EVG-14876](https://jira.mongodb.org/browse/EVG-14876)
Added background lines for the commits wrapper
Design:
Added storybook test
=> EVG-14876: Background Grid for Commit Charts

cypress/integration/patch/downstream_tasks.ts, src/gql/generated/types.ts, src/gql/queries/get-patch.graphql, src/pages/Patch.tsx, src/pages/patch/PatchTabs.tsx, src/pages/patch/patchTabs/DownstreamTasks.tsx
EVG-14944
- Remove all references to `childPatches` so that this field can be safely converted to `Patch` type
- Not sure if I should include the `groupId` and `StartTime` fields that got added to the generated `types.ts` file -- any thoughts?
- Downstream Task tab no longer renders (cleanly) when running local dev server
=> EVG-14944: Remove references to childPatch

cypress/integration/patch/configure_patch.ts, src/pages/configurePatch/ConfigurePatchCore.tsx
[EVG-14799](https://jira.mongodb.org/browse/EVG-14799)
This correctly selects the tab on the initial render when there isn't one in the url. 
added a cypress test to validate. Unfortunately i was unable to easily create a test that tests out the redirect from legacy evergreen ui that was described in the ticket because of cypress' single domain limit. But the test i created tests the url that is returned in the redirect
=> EVG-14799 Correctly visit configure page when no tab indicated

src/gql/generated/types.ts, src/gql/mutations/edit-spawn-host.graphql, src/pages/spawn/spawnHost/EditSpawnHostModal.tsx, src/pages/spawn/spawnHost/editSpawnHostModal/useEditSpawnHostModalState.ts
[EVG-14901](https://jira.mongodb.org/browse/EVG-14901)
Reuse the PublicKeyForm component within the EditSpawnHost modal so users can add keys to existing hosts.
Added a key to a host on staging. Also saved a new key.
https://github.com/evergreen-ci/evergreen/pull/4815
=> EVG-14901 add ssh key to EditSpawnHostModal

public/index.html, src/components/Accordion/index.tsx, src/context/Providers.tsx, src/gql/generated/types.ts, src/gql/queries/get-patch.graphql, src/pages/Patch.tsx, src/pages/patch/PatchTabs.tsx, src/pages/patch/patchTabs/DownstreamProjectAccordion.tsx, src/pages/patch/patchTabs/DownstreamTasks.tsx, src/types/patch.ts
EVG-14943
- Add link to base commit for each downstream task
- Use LeafyGreen's `InlineCode` component for rendering link
- Load font dependency via Google Fonts' CDN ([LG's recommended approach](https://github.com/mongodb/leafygreen-ui/blob/main/packages/code/README.md#source-code-pro-font))
- Lemme know if we'd rather stick to our current monospace styling!
https://github.com/evergreen-ci/evergreen/pull/4810
=> EVG-14943: Render base commit link for downstream tasks

src/pages/task/taskTabs/testsTable/TestsTableCore.tsx
EVG-14785
Default sorting of the task details' Tests table was introduced in https://github.com/evergreen-ci/spruce/pull/749. However, these query params were being set once `TestsTableCore` mounted, but before the URL was updated to the `/tests` tab. This meant that the params were immediately overwritten by [this hook](https://github.com/evergreen-ci/spruce/blob/main/src/pages/task/TaskTabs.tsx#L179-L192)'s `history.replace()` call.
Update `TestsTableCore` to watch the page's `pathname` and append query params when the pathname is updated. This results in the hook firing twice (once on the initial url and once on `/tests`), but I think that is preferable to attempting an equality check on the pathname.
=> EVG-4785: Fix Tests table default sort

src/pages/commits/ActiveCommits/ChartToggle.tsx
[EVG-15035](https://jira.mongodb.org/browse/EVG-15035)
No longer gives warning when chart toggle
=> EVG-15035 Fixed warnings for chart toggle

cypress/integration/breadcrumbs.ts, src/components/Breadcrumb/index.tsx
[EVG-15179](https://jira.mongodb.org/browse/EVG-15179)
Show we dont accidentally expose mainline commits early. 
Should revert this when we launch mainline commits
=> EVG-15179 Hide breadcrumb link

src/gql/generated/types.ts, src/gql/queries/get-version.graphql, src/pages/version/ManifestBlob.tsx, src/pages/version/Metadata.tsx
[EVG-13902](https://jira.mongodb.org/browse/EVG-13902)
Creates a link in the version metadata that opens the manifest in a new tab
opens this
Tested manually. I couldn't figure out a way to write any tests for this
CreateObjectURL isn't supported in jest and can't really be mocked since it does some stuff behind the scenes to generate the url.
Can't test in cypress because `createObjectURL` changes the domain name by prepending a `blob` to the link and cypress wont allow cross origin requests.
https://github.com/evergreen-ci/evergreen/pull/4904
=> EVG-13902 Create manifest link

package.json, yarn.lock
[EVG-15167](https://jira.mongodb.org/browse/EVG-15167)
Bumped this dep to remove the warning while building. Also removed the `--max-old-space-size` flag since its no longer needed
=> EVG-15167 bump browser list and remove max-old-space-size

cypress/integration/subscription_modal.ts, src/hooks/tests/useNotificationModal.test.tsx, src/pages/task/actionButtons/TaskNotificationModal.tsx
[EVG-14332](https://jira.mongodb.org/browse/EVG-14332)
Notify if the task is failed or blocked. (Could've made this just notify on blocked; I thought a bit about the reporter's use case / general use case for this and I think failed + blocked does make the most sense, but the work to add "just blocked" would be similar to this if it's ever requested in the future.)
Tested on staging with blocked and failed task (pictures available on Evergreen PR).
https://github.com/evergreen-ci/evergreen/pull/4914
=> EVG-14332 add task failed or blocked notification type

src/components/Content/index.tsx, src/constants/routes.ts, src/pages/ProjectSettings.tsx, src/pages/preferences/PreferencesTabs.tsx, src/pages/projectSettings/ProjectSettingsTabs.tsx, src/pages/projectSettings/projectSettingsTabs/AccessTab.tsx, src/pages/projectSettings/projectSettingsTabs/EventLogTab.tsx, src/pages/projectSettings/projectSettingsTabs/GeneralTab.tsx, src/pages/projectSettings/projectSettingsTabs/GitHubCommitQueueTab.tsx, src/pages/projectSettings/projectSettingsTabs/NotificationsTab.tsx, src/pages/projectSettings/projectSettingsTabs/PatchAliasesTab.tsx, src/pages/projectSettings/projectSettingsTabs/PeriodicBuildsTab.tsx, src/pages/projectSettings/projectSettingsTabs/ProjectTriggersTab.tsx, src/pages/projectSettings/projectSettingsTabs/VariablesTab.tsx, src/pages/projectSettings/projectSettingsTabs/VirtualWorkstationTab.tsx, src/pages/projectSettings/projectSettingsTabs/index.tsx
EVG-15074
[Figma](https://www.figma.com/file/Z0rfsPjVKglRq9baDhsSux/Project-Settings-Sections)
- Add project settings pages to `/project/<project>/settings`
- Nested pages (e.g. "General Configuration" under "General Settings") will be added in a future PR since they represent anchor links to content that doesn't exist yet. Nesting also isn't available in `@leafygreen-ui/side-nav@5.0.2` ([see changelog](https://github.com/mongodb/leafygreen-ui/blob/main/packages/side-nav/CHANGELOG.md#710))
- We need to upgrade `@leafygreen-ui/side-nav` in order to match the designs and use nested pages; this work is captured in EVG-15289
=> EVG-15074: Add project settings page structure

src/pages/spawn/spawnHost/SpawnHostActionButton.tsx
[EVG-15365](https://jira.mongodb.org/browse/EVG-15365)
For some reason the Play icon and only the Play icon had a fill value of none?
=> EVG-15365 Add default fill color to play icon

src/components/ButtonDropdown.tsx
EVG-8290
- While looking into [Mohamed's comment](https://jira.mongodb.org/browse/EVG-15288?focusedCommentId=4019765&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4019765) I noticed that this was a usage issue, not a LG bug. LeafyGreen sets the trigger's `onClick` prop itself [here](https://github.com/mongodb/leafygreen-ui/blob/857a680a03d3523aafcc8773c6a23ca0cc1422a7/packages/menu/src/Menu.tsx#L367), so doing that on our end was overriding their logic around whether the menu should close.
https://user-images.githubusercontent.com/9298431/132907864-dc56c9b2-6b65-40ca-b2a7-2b7434d457dc.mov
=> EVG-8290: Close menu on outside click

src/components/Banners/SlackNotificationBanner.tsx, src/components/styles/SideNav.tsx, src/context/toast.tsx
EVG-15404
- Prevent sidebar from blocking toast contents
Also make slack banner look less awkward with padding
=> EVG-15404: Prevent sidebar from covering toast

cypress/integration/version/unscheduled_patch/configure_patch.ts, src/gql/generated/types.ts, src/gql/queries/get-patch-configure.graphql, src/hooks/useConfigurePatch.ts, src/pages/configurePatch/ConfigurePatchCore.tsx, src/pages/configurePatch/configurePatchCore/ConfigureBuildVariants.tsx, src/pages/configurePatch/configurePatchCore/ConfigureTasks.tsx, src/pages/configurePatch/configurePatchCore/state.ts
EVG-15287
- Add "Downstream Tasks" section on patch configure page, allowing aliases to be scheduled from the UI _only_ if the patch has not yet run
- Also show child patches that have been invoked via `--trigger-alias` on the CLI; these patches are read-only on the UI and interaction is disabled
- Upcoming work
- Show name of trigger used to invoke child patch (EVG-15385)
- Attach tasks/variants to aliases so that users can see which tasks will be run
- Staging has some good data for testing this page; `yarn run staging` and visit http://localhost:3000/patch/61378d50b237365d9b57e1aa/configure/tasks
- Add integration tests
=> EVG-15287: Add trigger aliases on configure page

cypress/integration/job_logs.ts, src/constants/externalResources.test.ts, src/constants/externalResources.ts, src/gql/generated/types.ts, src/gql/queries/get-task-tests.graphql, src/gql/queries/get-tests.graphql, src/pages/JobLogs.tsx, src/pages/task/taskTabs/testsTable/TestsTableCore.tsx
[EVG-15379](https://jira.mongodb.org/browse/EVG-15379)
Lobster will now build the test log url using a groupId passed from spruce.
https://github.com/evergreen-ci/lobster/pull/114/files
https://github.com/evergreen-ci/evergreen/pull/5017
=> EVG-15379: Pass groupID to Lobster Test Log URL

src/gql/generated/types.ts, src/gql/queries/get-patch-configure.graphql, src/pages/configurePatch/ConfigurePatchCore.tsx, src/pages/configurePatch/configurePatchCore/ConfigureBuildVariants.tsx
EVG-15385
- Label child patches with the alias that invoked them; also remove this alias from the list of aliases that can be scheduled
- Fix bug where "Select downstream tasks" sidebar was showing for projects with no available downstream tasks
- Local data isn't properly configured to test this case so I omitted integration tests. Would like to address this in a future app PR!
- Staging links to test
- http://localhost:3000/patch/6148b54697b1d33369655ab8/configure/tasks
- http://localhost:3000/patch/6007393897b1d37434957d04/configure/tasks ("select downstream tasks" does not appear on this page)
https://github.com/evergreen-ci/evergreen/pull/5036
=> EVG-15385: Attach aliases to child patches

src/gql/generated/types.ts, src/gql/queries/get-task-tests.graphql, src/gql/queries/get-tests.graphql, src/pages/JobLogs.tsx, src/pages/task/taskTabs/testsTable/getColumnsTemplate.tsx
[EVG-15465](https://jira.mongodb.org/browse/EVG-15465)
testFile represents test names as of https://github.com/evergreen-ci/evergreen/pull/5048
=> EVG-15465: Represent test names with testFile only instead of testFile and displayTestName

.evergreen.yml
[EVG-15487](https://jira.mongodb.org/browse/EVG-15487)
Spruce deploys are arguably pretty important and should have a high priority than most other tasks. 
Tagging @ablack12  and @bsamek  to make sure it's ok to do this.
=> EVG-15487 Give deploys a higher priority

src/components/Accordion/index.tsx
EVG-15200
- Don't clip overflow when accordion is open
- Manually tested all pages where `Accordion` appears
=> EVG-15200: Fix filter dropdown on Version Restart modal

src/components/Accordion/index.tsx
[EVG-15515](https://jira.mongodb.org/browse/EVG-15515)
The accordion had a max height of 1500px which cut off the downstream tasks after the 25th task. 
Before:
After: 
Tested on staging
=> EVG-15515 Fix Downstream Tasks cutting off after the 25th task

cypress/integration/version/unscheduled_patch/configure_patch.ts, src/gql/generated/types.ts, src/gql/queries/get-patch-configure.graphql, src/hooks/useConfigurePatch.ts, src/pages/configurePatch/ConfigurePatchCore.tsx, src/pages/configurePatch/configurePatchCore/ConfigureTasks.tsx, src/types/utils.ts
EVG-15443
- Display variants/tasks that would be run by scheduling an alias. Use these tasks to update the sidebar's badge count.
- Add integration test to ensure that the one task associated with the "logkeeper" alias renders correctly
- I set up staging so that you can view a patch with both a child patch and an alias [here](https://spruce-staging.corp.mongodb.com/patch/6155cb4997b1d3345c40835f/configure/tasks). Or run your own on staging:
```
evergreen -c ~/.evergreen-staging.yml patch -p mci --trigger-alias e2e
```
https://github.com/evergreen-ci/evergreen/pull/5047
https://github.com/evergreen-ci/evergreen/pull/5072
=> EVG-15443: Render variant tasks for aliases

cli-scripts/notify-email.js
[EVG-15621](https://jira.mongodb.org/browse/EVG-15621)
Just cleaning up this file.
Removing the callback hell that was occurring and instead just performing the steps in serial. 
Should clean up the format of the deploy email to be more consistent with the other deploy projects deploy emails.
Tagging @bsamek  for any comments about the structure of the email. I also think you may have reviewed this script in the past. 
I have not included the link to the revert email in this ticket and will do it in a follow up ticket once i think about the logic a bit more.
=> EVG-15621 Deploy email cleanup

cypress/integration/myPatches/my_patches.ts, cypress/integration/task/test_table.ts, cypress/utils/index.js, src/components/PatchesPage/ListArea.tsx, src/components/PatchesPage/StatusSelector.tsx, src/components/PatchesPage/index.tsx, src/gql/generated/types.ts, src/hooks/useUpdateURLQueryParams.ts, src/pages/ProjectPatches.tsx, src/pages/UserPatches.tsx, src/types/patch.ts
[EVG-13766](https://jira.mongodb.org/browse/EVG-13766)
Refactor patches pages to support filtering by only commit queue patches on project pages. Also a minor refactor on those pages since the default behavior for the project patches pages and the user pages are now slightly different. (User patches include commit queue patches by default / Project patches pages allow you to optionally only filter for commit queue patches.)
https://user-images.githubusercontent.com/4605522/138978382-4bff1b09-263c-43ee-afee-3ae80d69acab.mov
On staging and current e2e tests
https://github.com/evergreen-ci/evergreen/pull/5137
=> EVG-13766 Support filtering for only commit queue patches on the project patches page

src/pages/commits/ActiveCommits/buildVariantCard/WaterfallTaskStatusIcon.test.tsx, src/pages/spawn/spawnHost/SpawnHostButton.test.tsx
[EVG-13626](https://jira.mongodb.org/browse/EVG-13626)
This PR modifies `SpawnHostButton.test.tsx` such that it passes (previously, the test suite was skipped over entirely).
- Ran `yarn test`
=> EVG-13626 Make SpawnHostButton test pass

src/components/HistoryTable/Cell.tsx, src/components/HistoryTable/HistoryTableContext.test.tsx, src/components/HistoryTable/HistoryTableContext.tsx, src/pages/taskHistory/ColumnHeaders.tsx, src/pages/variantHistory/ColumnHeaders.tsx
[EVG-15759](https://jira.mongodb.org/browse/EVG-15759)
Limits to 7 columns and adds some padding in between columns as well as word breaking. 
Before: 
After:
=> EVG-15759 Update Historytable to only show 7 columns by default

src/pages/task/taskTabs/TestsTable.tsx
[EVG-14764](https://jira.mongodb.org/browse/EVG-14764)
Currently, it is unclear that tests exist for some tasks because "No Data" is displayed while the tests are loading. This PR adds a loading state to the Tests table to inform the user if tests are still loading.
https://user-images.githubusercontent.com/47064971/140333575-6dd2f3ad-bbcd-49db-a663-b84ab77f4958.mov
- Tested with a patch on `yarn prod`
=> EVG-14764 Add loading state to Tests table

src/components/HistoryTable/Row.tsx, src/pages/TaskHistory.tsx, src/pages/VariantHistory.tsx, src/pages/taskHistory/ColumnHeaders.tsx, src/pages/variantHistory/ColumnHeaders.tsx
[EVG-15806](https://jira.mongodb.org/browse/EVG-15806)
Show the loading state on initial page load instead of waiting for column headers to resolve
https://user-images.githubusercontent.com/4605522/140774877-8455ed5b-f96d-4845-8d26-d136aedb2f40.mp4
=> EVG-15806 Add loading state on initial page load

src/constants/routes.ts, src/gql/generated/types.ts, src/gql/queries/get-mainline-commits.graphql, src/pages/commits/ActiveCommits/BuildVariantCard.tsx, src/pages/commits/ActiveCommits/CommitChart.stories.tsx, src/pages/commits/ActiveCommits/index.tsx
[EVG-15816](https://jira.mongodb.org/browse/EVG-15816)
These changes were cherry-picked from https://github.com/evergreen-ci/spruce/pull/966 with some styling improvements. 
< add a description of how you tested it >
< link to a corresponding evergreen PR if applicable >
=> EVG-15816: waterfall page links to build variant history

.evergreen.yml
EVG-15285
- Remove call to `get-go-modules`. We don't need to explicitly call `mod-tidy` because installing the modules will be triggered by running the server via `make local-evergreen` (as per @Kimchelly)
=> EVG-15825: Fix e2e_test task

.evergreen.yml, README.md
Jira: https://jira.mongodb.org/browse/EVG-15826
Spruce has a dependency on how Evergreen builds its local server for CI testing, Since Evergreen uses modules, it's no longer tied to a `GOPATH`. I updated the evergreen YAML to reflect this. I put it in the `build` directory instead of `gopath/src/github.com/evergreen-ci`, but if you prefer it to be somewhere else, let me know. The location doesn't really matter that much.
* Clean up the usages of `GOPATH` (no longer necessary) and `GO_BIN_PATH` (no longer used for Evergreen Go builds).
* Update the README slightly since Evergreen no longer depends on `GOPATH`.
N/A
N/A
N/A
=> EVG-15826: update evergreen YAML for Go module changes

src/gql/GQLWrapper.tsx, src/gql/generated/types.ts, src/gql/queries/get-agent-logs.graphql, src/gql/queries/get-event-logs.graphql, src/gql/queries/get-system-logs.graphql, src/gql/queries/get-task-logs.graphql, src/pages/task/taskTabs/logs/LogTypes.tsx
[EVG-14680](https://jira.mongodb.org/browse/EVG-14680)
This is a very specific bug that seems to only occur in one situation.
When you restart a task, the execution for that task will show `No logs` (as the task has not run yet). Switching to another execution whose logs are _already in the cache_ will cause `No logs` to persist, which is not correct. However, this behavior will only persist for **one** execution. Here is an example:
https://user-images.githubusercontent.com/47064971/141480405-07e85eac-e76d-428b-84a6-584ff2835b7c.mov
The root cause appears to be that we determine a `noLogs` status based on if an error occurs. For some reason, switching to another execution whose logs are already in the cache will return both an error and the data that we want to display. This behavior is …
=> EVG-14680 Resolve incorrect display of TaskLogs between executions

src/pages/preferences/preferencesTabs/NewUITab.tsx
[EVG-15843](https://jira.mongodb.org/browse/EVG-15483)
The new ui toggle would sometimes become out of sync with the data returned in the user settings queries and wouldn't accurately reflect changes to the data. 
Its state was managed independently of the response from the query, Which caused the discrepancies. But now its state will reflect the data requested.
=> EVG-15483 Fix new ui toggle not accurately reflecting status

src/components/Breadcrumb/index.tsx, src/components/CommitChartLabel/CommitChartLabel.test.tsx, src/components/CommitChartLabel/index.tsx, src/pages/Version.tsx, src/pages/commits/ActiveCommits/index.tsx, src/pages/spawn/spawnHost/spawnHostModal/SetupScriptForm.tsx, src/utils/string/index.ts, src/utils/string/string.test.ts
[EVG-15838](https://jira.mongodb.org/browse/EVG-15838)
These code changes shorten all occurrences of githash displays to 7 characters
=> EVG-15838: Shorten githash to 7 characters

src/components/HistoryTable/HistoryTable.tsx, src/components/HistoryTable/HistoryTableContext.test.tsx, src/components/HistoryTable/HistoryTableContext.tsx, src/components/HistoryTable/historyTableContextReducer.ts, src/pages/TaskHistory.tsx, src/pages/VariantHistory.tsx
[EVG-15780](https://jira.mongodb.org/browse/EVG-15780)
This allows us to dynamically keep track of how many rows we need for the history table. So we can avoid a situation in which we don't have enough rows or we have more rows then we need. This can not be calculated on the server since we dynamically generate  some of the rows on the front end (For folded commits and date separators). So it tries to estimate the value and refine that estimate as the user scrolls and we fetch more data.
=> EVG-15780 Manage commitCount for table rows

.evergreen.yml, check_codegen.sh, src/gql/generated/types.ts
[EVG-16021](https://jira.mongodb.org/browse/EVG-16021)
This adds a new evergreen task that validates if the codegen command was ran. This should help prevent mistyped queries from forgetting to run this command. Or to catch broken files from bad merge conflict resolutions.
Test with a broken types.ts file (Should fail)
https://spruce.mongodb.com/version/61c491baa4cf47367121f77f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Test with a valid types.ts file (Should Pass)
https://spruce.mongodb.com/version/61c491a7d6d80a2275c83078/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> EVG-16021 Add a Codegen task 

.evergreen.yml
[EVG-16014](https://jira.mongodb.org/browse/EVG-16104)
Should resolve the failure in https://spruce.mongodb.com/task/spruce_ubuntu1604_deploy_to_prod__v2.26.0_22_01_12_12_13_51/logs?execution=0
Unable to test without running that task which would result in a deploy but fairly confident this is the fix.
=> EVG-16104 Use node 16 for deploy-to-prod task

src/components/GroupedTaskStatusBadge/__snapshots__/GroupedTaskStatusBadge.stories.storyshot, src/constants/task.ts
[EVG-15779](https://jira.mongodb.org/browse/EVG-15579)
Umbrella status now also shows timed out
=> EVG-15579 Update failed label to also represent timed out

src/utils/environmentalVariables.ts
[EVG-16126](https://jira.mongodb.org/browse/EVG-16126)
Accidentally committed this when i was testing something. 
React env variables need to begin with REACT_APP_...
=> EVG-16126 Fix typo to environmental variables

cypress/integration/version/version_route.ts, src/pages/version/Tabs.tsx
[EVG-14429](https://jira.mongodb.org/browse/EVG-14429)
This PR makes it so that if a user is on a different tab like `Changes` or `Downstream Tasks` on the Patch page, clicking on a task status badge will bring them back to the `Tasks` tab (with the correct filters applied).
https://user-images.githubusercontent.com/47064971/150021885-6b75986a-0d33-43e3-830b-cf9061bc7911.mov
- Edited e2e test in `version_route.ts`
=> EVG-14429: Navigate to task tab when clicking on build variant badges

src/pages/task/taskTabs/testsTable/LogsColumn.tsx, src/utils/string/index.ts
[EVG-16173](https://jira.mongodb.org/browse/EVG-16173)
Since the history table applies a regex search and the tests table often has test names with characters that can be mistaken for regex we need to escape them before using them in the history table otherwise we won't be able to match on them.
=> EVG-16173 Escape regex characters on history table links

src/components/HistoryTable/Cell.tsx, src/constants/history.ts, src/gql/generated/types.ts, src/pages/TaskHistory.tsx, src/pages/VariantHistory.tsx, src/pages/taskHistory/ColumnHeaders.test.tsx, src/pages/taskHistory/ColumnHeaders.tsx, src/pages/variantHistory/ColumnHeaders.test.tsx, src/pages/variantHistory/ColumnHeaders.tsx, src/utils/string/index.ts, src/utils/string/string.test.ts
[EVG-16119](https://jira.mongodb.org/browse/EVG-16119)
This PR linkifies the column headers on the variant and task history pages. It also trims column headers by inserting an ellipsis (`...`) if a variant or task name exceeds a given length. If a variant or task name has been trimmed, a tooltip displaying the full name will appear when hovering over it; otherwise, no tooltip appears.
Also adds a small CSS fix to solve a visual bug that was occurring on Safari.
https://user-images.githubusercontent.com/47064971/150229673-5e561fbf-2cc0-425a-a580-592f27eef34c.mov
- Added unit tests for `ColumnHeaders.tsx` in `pages/variantHistory` and `pages/taskHistory` folders
- Added a unit test for new function `trimMiddleText` in `utils/string/string.test.ts`
=> EVG-16119: Linkify & trim column headers on Variant/Task History pages

src/components/Accordion/index.tsx, src/components/ProjectSettingsTabs/AccessTab/getFormSchema.ts, src/components/ProjectSettingsTabs/Context.tsx, src/components/ProjectSettingsTabs/GeneralTab/getFormSchema.ts, src/components/ProjectSettingsTabs/VariablesTab/getFormSchema.ts, src/components/SpruceForm/CustomFields.tsx, src/components/SpruceForm/FieldTemplates.tsx, src/components/SpruceForm/LeafyGreenWidgets.tsx, src/components/SpruceForm/SpruceForm.test.tsx, src/components/SpruceForm/__snapshots__/SpruceForm.stories.storyshot, src/components/SpruceForm/__snapshots__/SpruceForm.test.tsx.snap, src/components/SpruceForm/index.tsx
EVG-16153
Break up some of the UI work from EVG-15081. This PR includes general changes that are not specific to the GitHub/Commit Queue page, but are used by this page
- Improve support for `null` type fields
- Better array customization
- Add new `sectionTitle` flag to expand form's text hierarchy
- Support hiding input labels by using LeafyGreen's text input's `ariaLabelledBy` prop
- Update unit tests & snapshot
=> EVG-16153: Update SpruceForm ui elements

src/components/SearchableDropdown/__snapshots__/SearchableDropdown.stories.storyshot, src/components/SearchableDropdown/index.tsx, src/pages/TaskQueue.tsx, src/pages/commits/projectSelect/__snapshots__/ProjectSelect.stories.storyshot, src/pages/taskHistory/BuildVariantSelector.tsx, src/pages/taskQueue/DistroOption.tsx
[EVG-16143](https://jira.mongodb.org/browse/EVG-16143)
This PR solves the issue where the options in the `SearchableDropdown` on the Task & Variant History pages would not wrap, causing many of them to be unreadable.
It also fixes some styling in the custom `SearchableDropdown` option used on the Task Queue page.
Before      |  After
Before      |  After
- Just visually
=> EVG-16143: Wrap options in SearchableDropdown

src/components/FilterBadges/FilterBadge.tsx, src/components/FilterBadges/FilterBadges.test.tsx, src/components/FilterBadges/__snapshots__/FilterBadges.stories.storyshot
[EVG-15974](https://jira.mongodb.org/browse/EVG-15974)
Currently, there is a visual bug where long text in filter badges will overflow.
This PR trims text so that it fits within the fixed filter badge width (`260px`). If the text in a filter badge has been trimmed, a tooltip displaying the full text will appear when hovering over it; otherwise, no tooltip appears.
https://user-images.githubusercontent.com/47064971/150845010-55a23272-d857-4e9a-a45a-16a4d1533854.mov
- Added test in `FilterBadges.test.tsx`
=> EVG-15974: Trim filter badge text

cypress/integration/nav_bar.ts, src/components/Dropdown/__snapshots__/Dropdown.stories.storyshot, src/components/Dropdown/index.tsx, src/components/Header/AuxiliaryDropdown.tsx, src/components/SearchableDropdown/SearchableDropdown.stories.tsx, src/components/SearchableDropdown/__snapshots__/SearchableDropdown.stories.storyshot, src/components/SearchableDropdown/index.tsx, src/pages/commits/projectSelect/__snapshots__/ProjectSelect.stories.storyshot
[EVG-14849](https://jira.mongodb.org/browse/EVG-14849)
This PR adds a `Project Patches` link in the navbar dropdown based on a user's most recently selected project. 
Information about a user's most recently selected project is stored in the cookie `mci-project-cookie`. If a user does not have this cookie, then this link defaults to `mongodb-mongo-master` (alternatively `evergreen` if running entirely locally).
https://user-images.githubusercontent.com/47064971/151207754-9a26309f-c385-4bc9-b0f2-f57b146e4947.mov
- Added tests in `nav_bar.ts` (e2e)
=> EVG-14849: Add Project Patches link in Navbar dropdown

src/pages/commits/CommitsWrapper.tsx
[EVG-16085](https://jira.mongodb.org/browse/EVG-16085)
Currently, when you view the `/commits` page with a small screen you will see a few visual bugs (see image): 
1. "Unmatching" text will overlap with commits text
2. Text in the sticky headers will overflow and overlap the task results below
<p align="center">
</p>
I modified some CSS to prevent this from happening. Most importantly, I gave the `CommitWrapper` a `min-width` because right now it shrinks proportionately to the screen size which causes the overflow to get worse.
<p align="center">
</p>
- Visually
=> EVG-16085: Prevent text from overlapping on Commits page

cypress/integration/projectSettings/project_settings.ts, src/components/ProjectSettingsTabs/GithubCommitQueueTab/getFormSchema.ts, src/components/ProjectSettingsTabs/GithubCommitQueueTab/transformers.test.ts, src/components/ProjectSettingsTabs/GithubCommitQueueTab/transformers.ts, src/components/ProjectSettingsTabs/GithubCommitQueueTab/types.ts, src/components/ProjectSettingsTabs/testData.ts, src/components/SpruceForm/LeafyGreenWidgets.tsx, src/gql/fragments/projectSettings/githubCommitQueue.graphql, src/gql/generated/types.ts
EVG-16258
- Add field for commit queue's `requireSigned` field
Project attached to repo view:
Repo/non-attached project view:
- Manual testing, update unit test
- To preview locally when running a dev server using the latest main branch of evergreen:
- http://localhost:3000/project/evergreen/settings/github-commitqueue to view a project that inherits from a repo
- http://localhost:3000/project/spruce/settings/github-commitqueue to view a project that does not inherit from a repo
- http://localhost:3000/project/602d70a2b2373672ee493184/settings/github-commitqueue to view a repository's settings
=> EVG-16258: Add requireSigned field

cypress/integration/commits/route.ts
[EVG-16088](https://jira.mongodb.org/browse/EVG-16088)
This test broke when i changed the logic for returning projects
=> EVG-16088 Fix e2e test

src/gql/generated/types.ts, src/pages/spawn/spawnHost/SpawnHostModal.tsx
[EVG-15529](https://jira.mongodb.org/browse/EVG-15529)
Normally, users cannot spawn a host until they provide a public key (the intended behavior). However, spawning a host from a task will ignore this requirement and allow users to spawn a host without a public key, which leads to an error. This PR fixes this bug.
The error was occurring because `GetMyPublicKeysQuery` always returns an array but we were always setting the `publicKey` to `publicKeys[0]`, even if the array had no length.
https://user-images.githubusercontent.com/47064971/153950728-57c96d68-e7c3-4c7a-bcc0-bf4b2b1a58a1.mov
- Manually
=> EVG-15529: Block users from spawning host from task if public key is missing

src/pages/version/BuildVariants.tsx
[EVG-16355](https://jira.mongodb.org/browse/EVG-16355)
Fixes styling bug introduced #1093 
Before: 
After:
=> EVG-16355 Fix build variant panel styling

src/components/Dropdown/index.tsx, src/components/SearchableDropdown/SearchableDropdown.test.tsx, src/components/SearchableDropdown/index.tsx
[EVG-16330](https://jira.mongodb.org/browse/EVG-16330)
This PR adds the functionality to reset the search (i.e. clear the text input and show all available options) for two scenarios:
1. the user closes the `SearchableDropdown` by clicking on an option
2. the user closes the `SearchableDropdown` by clicking outside of it
Note that for the scenario where the user clicks on an option, we only reset the search state if `SearchableDropdown` does NOT allow multiselect. This is because we don't close the dropdown after the user clicks on an option if multiselect is enabled.
https://user-images.githubusercontent.com/47064971/156393125-05d01188-b9bf-42cd-8fdb-4e6ad92ae113.mov
- Added tests in `SearchableDropdown.test.tsx`
=> EVG-16330: Reset search when SearchableDropdown closes

src/pages/preferences/preferencesTabs/ProfileTab.tsx, src/pages/spawn/spawnHost/SpawnHostButton.test.tsx, src/pages/spawn/spawnHost/SpawnHostModal.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/BuildBaron.test.tsx
[EVG-15533](https://jira.mongodb.org/browse/EVG-15533)
This PR makes it so that the "Region" dropdown in the `SpawnHostModal` is pre-filled to the user’s preferred AWS region if it exists. Otherwise, it's just set to the first region in the list of AWS regions.
It also fixes a separate bug where the Profile tab doesn't properly display a user's preferred AWS region. (see video below)
https://user-images.githubusercontent.com/47064971/156423730-ae22c838-49b4-4fb9-bded-d0f47b6f83d7.mov
https://user-images.githubusercontent.com/47064971/156426305-48d67a20-3b8a-4322-98d1-9d037f3a3b19.mov
- Manually
=> EVG-15533: Default to user's preferred AWS region in SpawnHostModal

cypress/integration/projectSettings/project_settings.ts, src/components/ProjectSettingsTabs/Context.tsx, src/components/ProjectSettingsTabs/DefaultSectionToRepoModal.tsx, src/components/ProjectSettingsTabs/GeneralTab/getFormSchema.ts, src/components/ProjectSettingsTabs/GeneralTab/transformers.test.ts, src/components/ProjectSettingsTabs/GeneralTab/transformers.ts, src/components/ProjectSettingsTabs/Header.tsx, src/components/SpruceForm/LeafyGreenWidgets.tsx, src/gql/generated/types.ts, src/gql/mutations/default-section-to-repo.graphql, src/gql/mutations/index.ts
EVG-16436
- Call `defaultSectionToRepo` resolver when "Default Page to Repo" button is clicked
- Added integration tests
https://github.com/evergreen-ci/evergreen/pull/5443
=> EVG-16436: Add default to repo button

src/pages/commits/utils.test.ts, src/pages/commits/utils.ts
[EVG-16356](https://jira.mongodb.org/browse/EVG-16356)
Noticed a edge case where a lone variant filter would cause the task status icons to appear. 
Before:
After:
Wrote tests for this edge case and tested
=> EVG-16356 Fix task grouping with build variant filter applied

package.json, src/pages/spawn/spawnHost/SpawnHostActionButton.tsx
[EVG-16284](https://jira.mongodb.org/browse/EVG-16284)
[EVG-16378](https://jira.mongodb.org/browse/EVG-16378)
Fix typo and clear the babel cache before builds
Clearing the babel cache will prevent it from using cached data such as outdated graphql queries when ever we build a prod build.
=> EVG-16284 EVG-16378 Fix typo and clear babel cache 

src/hooks/useFilterInputChangeHandler.ts
[EVG-16332](https://jira.mongodb.org/browse/EVG-16332)
Somewhere along the line, we stopped sending analytics events for text inputs filters (e.g. `taskName`, `variant`) on the `Task` and `Test` tables. This PR adds that line of code back (+ moves a few things around just for organization sake).
- Manually checked the console
=> EVG-16332: Send analytics events for text input filters

src/gql/generated/types.ts, src/gql/queries/get-task-for-tests-table.graphql, src/gql/queries/index.ts, src/pages/Task.tsx, src/pages/task/ActionButtons.tsx, src/pages/task/taskTabs/TestsTable.tsx, src/pages/task/taskTabs/testsTable/LogsColumn.tsx, src/pages/task/taskTabs/testsTable/getColumnsTemplate.tsx
[EVG-16384](https://jira.mongodb.org/browse/EVG-16384)
Disable history buttons on execution tasks
Execution task
Display task
Normal task
=> EVG-16384 Remove history buttons on execution tasks

src/pages/TaskHistory.tsx, src/pages/VariantHistory.tsx, src/utils/array/index.ts
[EVG-16470](https://jira.mongodb.org/browse/EVG-16470)
Fix crashes that occurred when trying to load the history pages for tasks that have no prior commits with the same name.
Add some error reporting when we encounter this scenario. We have removed all links to these pages in https://jira.mongodb.org/browse/EVG-16384
=> EVG-16470 Fix crashes when we fail to load column headers

src/hooks/tests/usePolling.test.tsx, src/hooks/usePolling.ts, src/pages/Version.tsx, src/pages/spawn/spawnHost/SpawnHostActionButton.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/BBFileTicket.tsx
[EVG-16534](https://jira.mongodb.org/browse/EVG-16534)
It's possible for `startPolling` and `stopPolling` to be undefined when using `useLazyQuery`. We should check that these functions are defined before calling them in the hook.
=> EVG-16534: Modify usePolling to work with lazy queries

package.json, src/components/ProjectSettingsTabs/GeneralTab/Fields/RepoConfigField.tsx, src/components/ProjectSettingsTabs/utils/alias.ts, src/components/SpruceForm/LeafyGreenWidgets.tsx, yarn.lock
EVG-16512
- Update RJSF to improve project settings form performance, particularly on GitHub/Commit Queue page. This made such a difference that I didn't look into any other approaches, but we can revisit if things start to get sluggish again.
- Remove `showErrors` option for two reasons:
1. The [`transformErrors` function](https://github.com/evergreen-ci/spruce/blob/000302e68d2106b7c6ebdae83789a5d2816a9e20/src/components/SpruceForm/errors.ts#L3) supresses all of the errors that needed this option  
2. RJSF added a `hideError` option, so we should use the supported way if we need this in the future
- Manual testing
=> EVG-16512: Improve form performance

src/components/ProjectSettingsTabs/GithubCommitQueueTab/GithubCommitQueueTab.tsx, src/components/ProjectSettingsTabs/GithubCommitQueueTab/getFormSchema.tsx, src/components/ProjectSettingsTabs/GithubCommitQueueTab/types.ts, src/components/ProjectSettingsTabs/testData.ts, src/gql/fragments/projectSettings/githubCommitQueue.graphql, src/gql/generated/types.ts, src/pages/projectSettings/Tabs.tsx
Addresses changes made in EVG-16208
- https://github.com/evergreen-ci/evergreen/pull/5495 renamed `gitHubWebhooksEnabled` to `githubWebhooksEnabled`. Reflect these changes which should fix broken e2e tests
https://github.com/evergreen-ci/evergreen/pull/5495
=> EVG-16208: Update GraphQL Schema

src/components/projectSelect/index.tsx
[EVG-16626](https://jira.mongodb.org/browse/EVG-16626)
This error was pretty noisy during local development on the commits page. It should be suppressed on non project settings pages.
=> EVG-16626 Only call getRepoId if on project settings page

src/analytics/version/useVersionAnalytics.ts, src/gql/generated/types.ts, src/gql/queries/get-version.graphql, src/pages/version/Metadata.tsx
[EVG-16574](https://jira.mongodb.org/browse/EVG-16574)
Show previous commit instead of base commit for mainline commits.
These changes will be reflected in the table and the version metadata.
Spruce tests with evergreen pr changes on top 
https://spruce.mongodb.com/version/623e053f2fbabe3b63973ad3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
https://github.com/evergreen-ci/evergreen/pull/5523
=> EVG-16574 Show previous version in version metadata

src/components/Table/Filters.tsx
[EVG-15835](https://jira.mongodb.org/browse/EVG-15835)
Replaced Antd table icons with LG Icons and updated their active colors to make it more visible that there are filters applied.
=> EVG-15835 Use lg icons for table selectors

src/pages/projectSettings/tabs/GeneralTab/transformers.test.ts, src/pages/projectSettings/tabs/GeneralTab/transformers.ts, src/pages/projectSettings/tabs/GeneralTab/types.ts
EVG-16675
- Fix e2e test: include `identifier` in calls to save project so that it is not overwritten to an empty string.
=> EVG-16675: Fix e2e test

src/gql/queries/get-mainline-commits-for-history.graphql, src/pages/TaskHistory.tsx, src/pages/VariantHistory.tsx
[EVG-16567](https://jira.mongodb.org/browse/EVG-16567)
Commits that do not contain matching tasks will be collapsed by default.
before: 
after:
=> EVG-16567 Collapse unmatching commits

cypress/integration/projectHealth/commits.ts, src/components/CommitChartLabel/index.tsx, src/components/HistoryTable/HistoryTableRow/FoldedCommit.tsx, src/components/HistoryTable/HistoryTableRow/Row.tsx, src/gql/fragments/upstreamProject.graphql, src/gql/generated/types.ts, src/gql/queries/get-mainline-commits-for-history.graphql, src/gql/queries/get-mainline-commits.graphql, src/gql/queries/get-version.graphql, src/pages/commits/ActiveCommits/index.tsx, src/pages/commits/InactiveCommits/InactiveCommits.stories.tsx, src/pages/commits/InactiveCommits/index.tsx, src/pages/version/Metadata.tsx, src/types/triggers.ts
[EVG-16660](https://jira.mongodb.org/browse/EVG-16660)
Upstream Projects triggered versions will now link to the triggering task or version
Since we do not have the concept of builds on the spruce UI we will default to linking the version associated with a build.
Staging and locally
https://github.com/evergreen-ci/evergreen/pull/5565
=> EVG-16660 Add upstreamProject field to versions and mainline commits

src/pages/commits/ActiveCommits/buildVariantCard/WaterfallTaskStatusIcon.tsx
[EVG-16740](https://jira.mongodb.org/browse/EVG-16740)
Currently LG tooltips try to render as soon as you hover over them. This is problematic if a user mouses over several icons because they will all try to render and then stop rendering which causes the page to jitter when rendering all of the tooltips that are never used.  
https://user-images.githubusercontent.com/4605522/163607717-312bc841-1b13-4359-8486-baf61abfb5ca.mov
=> EVG-16740 Control LG tooltip enabled behavior on waterfall icons

src/pages/projectSettings/tabs/EventLogTab/EventLogDiffs.test.ts, src/pages/projectSettings/tabs/EventLogTab/EventLogDiffs.ts, src/types/utils.ts
[EVG-16716](https://jira.mongodb.org/browse/EVG-16716)
Add functions needed to calculate and reduce event log diffs so that they can later be put into columns on the event log page. 
Testing on staging
=> EVG-16716 Compute eventLog diff

package.json, src/pages/commits/ActiveCommits/__snapshots__/ProjectHealth.stories.storyshot, yarn.lock
[EVG-16689](https://jira.mongodb.org/browse/EVG-16689)
The following error was occurring when interacting with the Chart Toggle on the Project Health page:
This was an error also noticed by other LG users. The error was addressed in [PD-1485](https://jira.mongodb.org/browse/PD-1485). 
If you click on the code sandbox in the ticket and change the `leafygreen-ui/radio-group` version to `v7.0.5` (our current version), you will see that this error occurs. If you change the version to `v7.0.6`, the error no longer occurs. For this reason I upgraded our dependency to `v7.0.6` so that the error would be removed.
There is a way to remove the error on our current version by making use of the `checked` prop on the `Radio` component (see docs …
=> EVG-16689: Upgrade LG Radio Group to remove console error

src/gql/generated/types.ts, src/pages/TaskHistory.tsx, src/pages/VariantHistory.tsx, src/pages/commits/utils.test.ts, src/pages/commits/utils.ts
[EVG-16759](https://jira.mongodb.org/browse/EVG-16759)
Uses the toggle introduced in https://github.com/evergreen-ci/evergreen/pull/5598 to prevent fetching base tasks for mainline commits. 
https://github.com/evergreen-ci/evergreen/pull/5598
=> EVG-16759 Exclude base tasks for mainline commits queries

src/pages/commitqueue/ConfirmPatchButton.tsx
[EVG-16438](https://jira.mongodb.org/browse/EVG-16438)
Super small change to just make the `X` button and `Cancel` button functional for this modal 😀 (they did not work before)
https://user-images.githubusercontent.com/47064971/164327504-bd9ebdd7-180b-4206-a1ef-f4031d48aebc.mov
- Manually
=> EVG-16438: Allow commit queue removal modal to be closed 

cypress/integration/preferences/public_key_managment.ts, src/pages/preferences/preferencesTabs/publicKeysTab/EditModal.tsx, src/utils/validators/index.ts, src/utils/validators/validators.test.ts
[EVG-13451](https://jira.mongodb.org/browse/EVG-13451)
allow more ssh key types
cypress
[  < link to a corresponding evergreen PR if applicable >
](https://github.com/evergreen-ci/evergreen/pull/5591)
=> EVG-16760 Support modern ssh key types

src/components/Breadcrumb/index.tsx, src/components/PatchesPage/PatchCard.tsx, src/constants/routes.ts, src/gql/fragments/patchesPage.graphql, src/gql/generated/types.ts, src/gql/queries/get-task.graphql, src/pages/task/metadata/__snapshots__/Metadata.stories.storyshot, src/pages/task/metadata/index.tsx, src/pages/task/metadata/taskData.js, src/pages/version/Metadata.tsx
[EVG-16590](https://jira.mongodb.org/browse/EVG-16590)
This PR makes it so that the `projectIdentifier` is used instead of the `id` (`projectId`) in the project patches route.
The reason this still works despite there being no changes in the Evergreen repo is because the [ById](https://github.com/evergreen-ci/evergreen/blob/main/model/project_ref.go#L1210-L1217) function used to look up projects actually matches on either the project ID or identifier. In fact, if you go to the [sandbox](https://spruce-staging.corp.mongodb.com/project/5ffe393097b1d3759dd3c1a3/patches?commitQueue=false) project on spruce-staging and replace the ID in the url with `sandbox`, you'll see that this functionality already works.
- No visible changes (only the links have changed)
- Manually on prod; an example of …
=> EVG-16590: Use projectIdentifier in Project Patches route

package.json, yarn.lock
EVG-16595
- Update RJSF to 4.2.0, which includes a commit that fixes the orderable bug: https://github.com/rjsf-team/react-jsonschema-form/pull/2797
All arrays using `ui:orderable: false` (i.e. all besides virtual workstation commands) no longer include arrow buttons for reordering.
=> EVG-16595: Fix ui:orderable bug

cypress/integration/myPatches/my_patches.ts, src/components/PatchesPage/index.tsx
[EVG-16519](https://jira.mongodb.org/browse/EVG-16519)
Small PR to reset the page number to 0 whenever a user uses the search box on the My Patches page.
https://user-images.githubusercontent.com/47064971/167480428-8a002e14-49e7-4804-871e-7557dd9f9a74.mov
- Modified `my_patches.ts` (Cypress)
=> EVG-16519: Reset page number on patch description search

src/components/CodeChanges/CodeChanges.tsx, src/components/PatchActionButtons/EnqueuePatch.tsx, src/gql/generated/types.ts, src/pages/version/EnqueueModal.tsx, src/utils/commits/index.ts
[EVG-14731](https://jira.mongodb.org/browse/EVG-14731)
This PR makes it so that if a user tries to enqueue a patch that was created with the `--preserve-commits` option, there will be 1) a message that says the commits will be preserved and 2) no text box as the commit message cannot be edited.
Note: The enqueue button is only enabled for patches. So this modal would never be reachable from a version.
https://user-images.githubusercontent.com/47064971/166992260-66986e3a-5f8f-47b3-a1dd-f6639811dcc3.mov
- manually, example patch [here](https://spruce.mongodb.com/user/minna.kt/patches?commitQueue=true&patchName=preserve%20commits)
=> EVG-14731: Indicate when commits will be preserved in Enqueue Modal

src/pages/hosts/HostsTable.tsx
[EVG-16080](https://jira.mongodb.org/browse/EVG-16080)
The idle time on the Hosts page always says "51 years" or "52 years" because we incorrectly interpret the idle time as a date when it's actually a duration.
Example: if a host has been idle for 1 hour, we were interpreting that as 1 hour since January 1st, 1970, which is 52 years ago.
https://user-images.githubusercontent.com/47064971/167657756-2b709a90-0c9d-4485-83fa-012ced605e57.mov
- Manually looked at the idle time durations and plugged them into a calculator to see if the new times were correct
- Note: easiest way to see idle times that aren't `N/A` is to sort by DESC
=> EVG-16080: Show correct idle times on Hosts page

src/components/Popconfirm/PopconfirmWithCheckbox.test.tsx, src/hooks/tests/useVersionStatusSelect.test.ts, src/pages/commits/InactiveCommits/InactiveCommits.test.tsx, src/pages/projectSettings/tabs/GeneralTab/Fields/RepoConfigField.test.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/BBComponents.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/BuildBaron.test.tsx
[EVG-15580](https://jira.mongodb.org/browse/EVG-15580)
This PR improves our unit tests by making sure to always use `await` when we use `waitFor`.
I removed `waitFor` from places that didn't actually need it.
- This entire PR! 😎
=> EVG-15580: Fix unit tests to always use await before waitFor

src/analytics/version/useVersionAnalytics.ts, src/constants/externalResources.ts, src/gql/generated/types.ts, src/gql/queries/get-version.graphql, src/pages/task/metadata/__snapshots__/Metadata.stories.storyshot, src/pages/task/metadata/index.tsx, src/pages/version/Metadata.tsx
[EVG-16449](https://jira.mongodb.org/browse/EVG-16449)
Link to github commit from version metadata.
use `shortenGithash` function to trim githashes for consistency.
https://github.com/evergreen-ci/evergreen/pull/5653
=> EVG-16449 Add link to github commits

src/pages/spawn/spawnHost/EditSpawnHostModal.tsx, src/utils/string/index.ts
[EVG-16849](https://jira.mongodb.org/browse/EVG-16849)
This PR resolves an issue where SSH keys that are `undefined` throw an error when being passed to the `stripNewLines` function.
=> EVG-16849: Strip new lines for ssh keys only if they are defined

cypress/integration/projectSettings/project_settings.ts, src/pages/ProjectSettings.tsx, src/pages/projectSettings/tabs/GithubCommitQueueTab/GithubCommitQueueTab.tsx, src/utils/environmentalVariables.ts
EVG-16935
- Use `REACT_APP_RELEASE_STAGE` environment variable to determine if a deployment is in the staging environment
- Show project settings in every environment except on production deployment
- Bonus: remove workaround that prevented GitHub/Commit Queue page from being disabled (EVG-16958). Because the test data was updated in https://github.com/evergreen-ci/evergreen/pull/5680, this is no longer necessary for tests to run successfully.
- View project settings at https://spruce-staging.corp.mongodb.com/project/evg/settings/general
- View the same project locally via `yarn staging` at http://localhost:3000/project/evg/settings
=> EVG-16935: Make project settings visible on staging

src/gql/generated/types.ts, src/gql/queries/get-task.graphql, src/pages/task/metadata/index.tsx
[EVG-14353](https://jira.mongodb.org/browse/EVG-14353)
Currently the "Submitted At" timestamp in the task metadata is always the same time, no matter what task execution you click on. (See example [here](https://spruce.mongodb.com/task/spruce_ubuntu1604_e2e_test_patch_f405163513f97f35fa83e9dce5b842ca6510d274_627b2984a4cf473d7821f66d_22_05_11_03_12_05/tests?execution=1&sortBy=STATUS&sortDir=ASC).)
This leads to some confusion among users, because they don't understand where the timestamps in the Execution Dropdown come from. This PR makes it so that the "Submitted At" timestamp always matches with the timestamp of the current selected execution.
(I'm looking at Execution 2 for this task. The "Submitted At" timestamp matches the timestamp for Execution 2 in the dropdown.)
- Manually
=> EVG-14353: Use activated time as "Submitted At" in Task Metadata

src/components/PageTitle.tsx, src/components/TaskStatusBadge/index.tsx, src/pages/CommitQueue.tsx, src/pages/Host.tsx, src/pages/Task.tsx, src/pages/Version.tsx, src/utils/statuses/getStatusBadgeCopy.test.ts, src/utils/statuses/getStatusBadgeCopy.ts
[EVG-15798](https://jira.mongodb.org/browse/EVG-15798)
Originally we were hiding the action buttons on the task page when the task status was null. These code changes make sure that we always show the action buttons by removing `<PageTitle hasData />`
=> EVG-15798: Remove <PageTitle hasData />

.evergreen.yml, email.sh
[EVG-15181](https://jira.mongodb.org/browse/EVG-15181)
Now tries to fetch the tagged commit before the currently checked out commit. Since we rely on git tags to determine what is deployed it should accurately track the commits between the two tags. 
Fixed some formatting now spruce deploy emails look like evergreen and cedar emails.
Added a hint for reverts.
Checked out a previous tag commit that is not HEAD and attempted to send an email.
=> EVG-15181 Fix revert emails not being sent

cypress/integration/version/downstream_tasks.ts, src/components/VersionRestartModal/VersionRestartModal.tsx, src/gql/fragments/patchesPage.graphql, src/gql/generated/types.ts, src/gql/queries/get-patch.graphql, src/gql/queries/get-version.graphql, src/pages/version/DownstreamTasks.tsx, src/pages/version/downstreamTasks/DownstreamProjectAccordion.tsx
[EVG-16674](https://jira.mongodb.org/browse/EVG-16674)
This PR removes references to `baseVersionID`, a deprecated field. It also removes some fields that appeared to be unused from a few graphql queries that I was looking at.
I also changed the downstream task base commit link to link to Spruce (right now it links to Evergreen legacy UI). I can change it back if that was intentional.
https://user-images.githubusercontent.com/47064971/171432033-8a205933-a82f-4c2f-8878-9f50d61a0b17.mov
- Manually, [here](https://spruce.mongodb.com/version/6228e1a33627e02c15fa71ca/downstream-tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) is an example patch on prod
- Added test in `downstream_tasks.ts` (Cypress)
=> EVG-16674: Remove references to baseVersionID

src/pages/preferences/preferencesTabs/cliTab/AuthenticationCard.tsx
[EVG-17024](https://jira.mongodb.org/browse/EVG-17024)
Noticed some Bugsnag errors when the reset api key button is pressed. Heres a quick fix.
It was due to a second path name being added to the url
=> EVG-17024 Fix bug where resetting api key doesn't work

cypress/integration/projectSettings/project_settings.ts
EVG-17049
- Fix flakiness by reordering tests
- I ran 6 executions [here](https://spruce.mongodb.com/task/spruce_ubuntu1604_e2e_test_patch_6849eb041f3093b76b6416d5f8afd5b2a4b2513b_62a2392e0ae6062ba1f50dab_22_06_09_18_17_25/tests?execution=2&sortBy=STATUS&sortDir=ASC) and [here](https://spruce.mongodb.com/task/spruce_ubuntu1604_e2e_test_patch_6849eb041f3093b76b6416d5f8afd5b2a4b2513b_62a2395f7742ae6c9b241abf_22_06_09_18_18_08/tests?execution=2&sortBy=STATUS&sortDir=ASC) which all passed
=> EVG-17049: Fix project settings e2e flakiness

src/components/ConditionalWrapper/index.tsx, src/components/Table/TasksTable.tsx, src/constants/patch.ts, src/constants/task.ts, src/pages/task/ActionButtons.tsx
[EVG-16951](https://jira.mongodb.org/browse/EVG-16951)
It's possible to visit the task history for the `merge-patch` task and the variant history for the `Commit Queue Merge` build variant. However, this task and build variant only appears on commit queue patches, so we don't maintain their history on mainline commits at all.
This PR disables the links for the `merge-patch` task and the `Commit Queue Merge` build variant so that a user cannot reach their corresponding variant & task history pages.
(This task and build variant are something that we own and are defined in the Evergreen repo [here](https://github.com/evergreen-ci/evergreen/blob/main/globals.go#L262-L263).)
https://user-images.githubusercontent.com/47064971/172473660-54018890-6e61-4785-9016-695ab913f5d3.mov
- Manually
=> EVG-16951: Disable history links for Commit Queue Merge & merge-patch

package.json
- According to [BUILD-14325](https://jira.mongodb.org/browse/BUILD-14325), evergreen uses Node v16.13.0 to test and build spruce. We also use packages with dependencies of Node 16+, so update our engines field to ensure local processes use the correct version
=> Update package.json engines field

src/components/Header/AuxiliaryDropdown.tsx, src/pages/ProjectSettings.tsx, src/utils/environmentalVariables.ts
EVG-16933
- Add project settings link, which is hidden on prod but visible on staging, beta, and local envs. I opted to rename from "Projects" to "Project Settings" because I think this more accurately captures the pages within, but let me know if there's a good reason not to.
- When EVG-17059 is completed and project settings is released, the legacy "Projects" link will be removed and the Spruce link will be made visible on prod.
=> EVG-16933: Add project settings link

cli-scripts/deploy-prod.js, package.json, yarn.lock
[EVG-17052](https://jira.mongodb.org/browse/EVG-17052)
Cleans up the deploy script and removes some of the confusing nested callbacks.
Removes logic surrounding semver versioning and will now default to a patch. 
Removes `prompt-run` package and replaces with [execSync](https://nodejs.org/api/child_process.html#child_processexecsynccommand-options) `prompt-run` is an abstraction around `execSync`. Which is what caused the confusing nested callbacks.
Ran the script but substituted the deploy commands with `echo statements`
=> EVG-17052 Cleanup and simplify deploy script 

src/pages/projectSettings/tabs/GeneralTab/Fields/RepoConfigField.tsx
EVG-17090
- To facilitate the release of project settings sans attaching to repos, hide the "attach" button in production environment
=> EVG-17090: Hide "Attach to Repo" button on production

package.json, yarn.lock
[EVG-17168](https://jira.mongodb.org/browse/EVG-17168)
Since we upgraded to react router 6 we no longer need to use an external types library for react-router-dom we can use its built in typing
=> EVG-17168 Remove @types/react-router-dom in favor of built in types

email.sh
[EVG-17051](https://jira.mongodb.org/browse/EVG-17051)
Removes single quotes from strings and replaces them with an html character code equivalent. This prevents us from accidentally escaping the bash command to send an email if there is a single quote in the email message.
Tested both sed and gsed commands on linux and osx respectively.
=> EVG-17051 Remove single quotes from deploy emails

src/pages/commits/commitTypeSelect/index.tsx, src/types/commits.ts
[EVG-17085](https://jira.mongodb.org/browse/EVG-17085)
This adds Periodic Builds to the dropdown on the waterfall page. 
[Tested on staging](http://localhost:3000/commits/mci?requester=all,gitter_request,git_tag_request,trigger_request,ad_hoc&skipOrderNumber=7828) on the mci project. 
[5751](https://github.com/evergreen-ci/evergreen/pull/5751)
=> EVG-17085 Add periodic build as a requestor in the new UI

src/test_utils/index.tsx
[EVG-17254](https://jira.mongodb.org/browse/EVG-17254)
This was originally included in #1363 but i am moving it out to make reviewing that pr easier.
This allows us to use our customQueries with RTL [screen method](https://testing-library.com/docs/queries/about/#screen)
=> EVG-17254 Support Screen use with custom query methods

src/pages/projectSettings/tabs/GeneralTab/getFormSchema.tsx
[EVG-17282](https://jira.mongodb.org/browse/EVG-17282)
It was possible to save a project without a owner and repo this would cause issues when it came to enabling github tracking. We should disable the ability to save projects that are missing a owner and repo
=> EVG-17282 Require owner and repo field in order to save

package.json, yarn.lock
[EVG-17411](https://jira.mongodb.org/browse/EVG-17411)
Bumps types/node to have the same major version that we require to build spruce.
=> EVG-17411 Bump @types/node to match required node version

cypress/integration/subscription_modal.ts, cypress/integration/task/annotations.ts, cypress/integration/version/task_filters.ts, cypress/support/commands.ts, cypress/utils/index.ts, src/components/Table/TasksTable.stories.tsx, src/components/Table/TasksTable.tsx, src/components/Table/__snapshots__/TasksTable.stories.storyshot, src/gql/generated/types.ts, src/gql/queries/get-version-tasks.graphql
[EVG-13880](https://jira.mongodb.org/browse/EVG-13880)
Since `version.tasks` already fetches the `baseTask` for every task, there's no reason to also fetch the `baseStatus`.
- Modified `TasksTable.stories.tsx`
=> EVG-13880: Remove baseStatus from version.tasks query

src/gql/generated/types.ts, src/pages/projectSettings/tabs/EventLogTab/EventLogTab.tsx
EVG-17397
- Disable cache on project settings events so that fields are not combined in the name of caching
Before (task regex renaming is missing -- since the alias has the same `id` field before and after the change is made, Apollo thinks it's being smart by caching and reusing the data):
After:
=> EVG-17397: Fix event log caching bug

src/constants/volumes.ts
EVG-17210
GP3 volume type is accessible via the backend and can be inputted in the old UI, but Spruce does not have it in the volume types allowed
https://github.com/evergreen-ci/evergreen/pull/5769
=> EVG-17210 Add GP3 volume type

src/gql/generated/types.ts, src/pages/projectSettings/tabs/GithubCommitQueueTab/getFormSchema.tsx
EVG-17491
- Authorized users/teams for git tags should not be able to be reordered
Field no longer has arrows next to each array item:
=> EVG-17491: Make git tag user/team fields not orderable

src/components/VersionTaskPageBreadcrumbs/VersionTaskPageBreadcrumbs.test.tsx, src/components/VersionTaskPageBreadcrumbs/index.tsx, src/hooks/index.ts, src/hooks/tests/useBreadcrumbRoot.test.tsx, src/hooks/tests/useBreadcrumbVersion.test.tsx, src/hooks/useBreadcrumbRoot.ts, src/hooks/useBreadcrumbVersion.ts, src/pages/Version.tsx
EVG-17417
This PR attempts to address the destructuring error we keep encountering in `useBreadcrumbRoot`. I refactored the code around `VersionTaskPageBreadcrumbs` to hopefully make it easier to understand, and added some guards.
I'm not 100% sure this will work, so once this is merged I'll keep this ticket in Blocked to see if it had any real effect.
- Moved hooks that were initially in `VersionTaskPageBreadcrumbs.tsx` to `hooks/useBreadcrumbRoot.ts` and `hooks/useBreadcrumbVersion.ts`
- Added tests for each of these hooks
=> EVG-17417: Fix destructuring error in VersionTaskPageBreadcrumbs

src/components/PageTitle.tsx, src/hooks/usePolling.ts, src/pages/CommitQueue.tsx, src/pages/Host.tsx, src/pages/Task.tsx, src/pages/Version.tsx
EVG-17352
`@apollo/client` changed the behavior of `startPolling` and `stopPolling`. It used to be that they would be `undefined` for lazy queries if the query hadn't been called yet, but now they are always defined. This was causing the `getVersion` to be called on component mount.
I ended up removing the polling for the `getVersion` lazy query because it didn't seem necessary.
Also refactored some usage of `usePageTitle` because it helps make `Version.tsx` look cleaner.
- N/A
=> EVG-17352: Remove polling on getVersion lazy query

src/constants/externalResources.ts, src/pages/task/taskTabs/Logs.tsx, src/pages/task/taskTabs/testsTable/LogsColumn.tsx, src/utils/environmentalVariables.ts
EVG-17932
Lobster links will now redirect to parsley on non prod deployments.
Note. This is temporary during development for the production release we will update the links on the evergreen side and return the appropriate link. 
Didn't write any tests since this is only used for internal testing
=> EVG-17932 Redirect lobster links to parsley

upload-bugsnag-sourcemaps.js
EVG-17985
@SupaJoon  caught that we weren't uploading source maps to bugsnag which may have been the cause of our mystery errors. This updates the script to upload them correctly
Ran the script locally and ensured source maps were uploaded.
=> EVG-17985 Upload source maps from the correct directory

cypress/integration/commit_queue.ts, cypress/integration/host/host_buttons.ts, cypress/integration/hosts/hosts_sorting.ts, cypress/integration/hosts/select_hosts.ts, cypress/integration/hosts/update_status_modal.ts, cypress/integration/projectSettings/project_settings.ts, cypress/integration/subscription_modal.ts, cypress/integration/task/execution_task_table.ts, cypress/integration/task/files_tables.ts, cypress/integration/task/task_actions.ts, cypress/integration/task/task_logs.ts, cypress/integration/version/action_buttons.ts, cypress/integration/version/routes.ts, cypress/integration/version/subscription_modal.ts, cypress/integration/version/task_duration.ts, cypress/support/commands.ts, cypress/support/e2e.ts
EVG-17080
(Disclaimer: I don’t know if this is the correct solution. But I ran this test in a [patch](https://spruce.mongodb.com/task/spruce_ubuntu1604_e2e_test_patch_126f75e0b9637086da6925747c8cd7c43c6169cd_63457fbf30661531116aee10_22_10_11_14_37_57/tests?execution=19&sortBy=STATUS&sortDir=ASC) 20 times and the only time it failed was because of an unrelated test.)
This PR makes it so that all toasts in `project_settings.ts` are automatically closed.
I noticed that there would always be a toast covering the `Add to GitHub Trigger Alias` checkbox. Because the toast is covering the checkbox, it's impossible to confirm in the Cypress video whether it has been properly checked or not. I was thinking that the toast might be causing us to sometimes check the checkbox, and sometimes not.
In any …
=> EVG-17080: Fix e2e failure caused by patch trigger alias

cypress/integration/hosts/select_hosts.ts, cypress/integration/projectSettings/project_settings.ts, cypress/integration/taskQueue/route.ts
EVG-17080
This PR is more to help me debug than actually solve the flaky test problem. The test currently doesn't scroll the field of interest into view so I can't see what's going on 🙃 
I also added more guards in attempt to fix the flaky reprovision hosts test.
Here's a [patch](https://spruce.mongodb.com/task/spruce_ubuntu1604_e2e_test_patch_10a00b29040b1136e9f0c4bcee9aa5f563230624_634eb42f61837d1f5a044e62_22_10_18_14_12_11/tests?execution=9&sortBy=STATUS&sortDir=ASC) that I ran ten times with no failures, but I could just be lucky.
- N/A
- N/A
=> EVG-17080: Address miscellaneous flaky e2e tests

cypress/integration/projectSettings/project_settings.ts, package.json, src/pages/projectSettings/Header.tsx, src/pages/projectSettings/Tabs.tsx, src/pages/projectSettings/getTabTitle.ts, src/pages/projectSettings/tabs/VariablesTab/PromoteVariablesModal.tsx, yarn.lock
EVG-17691
- On attached project pages, add link to repo settings. The page will open on the same tab that the project was viewing.
- Remove unused subtitle field from project settings pages
- Upgrade Cypress to 10.10.0. This version fixes a bug that prevented Cypress from running locally using Firefox: https://github.com/cypress-io/cypress/issues/23897
- Bonus: add additional text to promote variables modal to indicate that vars will be deleted (follow up to https://github.com/evergreen-ci/spruce/pull/1465)
- Add Cypress tests (flaky tests are failing)
=> EVG-17691: Add repo link to project settings pages

cypress/integration/projectHealth/taskHistory.ts, cypress/integration/projectHealth/variantHistory.ts, cypress/integration/projectSettings/project_settings.ts, cypress/integration/taskQueue/route.ts, src/components/SearchableDropdown/index.tsx, src/components/TupleSelect/__snapshots__/TupleSelect.stories.storyshot, src/components/TupleSelect/index.tsx, src/pages/TaskHistory.tsx, src/pages/VariantHistory.tsx, src/pages/taskHistory/BuildVariantSelector.tsx, src/pages/variantHistory/TaskSelector.tsx
EVG-17687
This PR prevents errors in `BuildVariantSelector` and `TaskSelector` by setting a default array value.
It also stops the commit history from loading forever on the variant history and task history pages if it could not be fetched.
- Added tests in `variantHistory.ts` and `taskHistory.ts` (Cypress)
=> EVG-17687: Fix null array errors in SearchableDropdown

.evergreen.yml
EVG-18163
Fixes the invalid node version errors causing spruce builds to fail
=> EVG-18163 Use node version defined in evergreen expansions

src/components/PatchesPage/PatchCard.tsx, src/gql/fragments/patchesPage.graphql, src/gql/generated/types.ts, src/pages/version/Metadata.tsx
EVG-18118
- For patches attached to a repo instead of a project, display `owner/repo` since no project name exists. These don't link anywhere because we don't support a repo patches page.
**Before:**
My patches:
Patch page:
**After:**
My patches:
Patch page:
=> EVG-18118: Display fallback project for repo patches

cypress/integration/version/task_filters.ts
EVG-16341
Renaming the "Failed" task umbrella in [7921cb7](https://github.com/evergreen-ci/spruce/commit/7921cb77989f4c54b8452623424f6d7a177da682#diff-09686debf3a71d22bf34e4110a7bcc5e9b6cf98e9fcf99f949a134cebbabea17) caused Cypress tests to fail as a result of the parent "Failed" status having the same name as its child Failed status.
- Update Cypress tests
=> EVG-16341 followup: Fix e2e test

package.json, src/pages/Preferences.tsx, src/pages/ProjectSettings.tsx, src/pages/preferences/Card.tsx, src/pages/preferences/PreferencesTabs.tsx, src/pages/preferences/preferencesTabs/CliTab.tsx, src/pages/preferences/preferencesTabs/NewUITab.tsx, src/pages/preferences/preferencesTabs/NotificationsTab.tsx, src/pages/preferences/preferencesTabs/ProfileTab.tsx, src/pages/preferences/preferencesTabs/cliTab/AuthenticationCard.tsx, src/pages/preferences/preferencesTabs/cliTab/DownloadCard.tsx, src/pages/preferences/preferencesTabs/cliTab/VerifyCard.tsx, src/pages/preferences/preferencesTabs/notificationTab/ClearSubscriptionsCard.tsx, yarn.lock
EVG-18143
- Upgrade `@leafygreen-ui/side-nav` to the latest version
- Since I was inspecting the user preferences page this seemed like a good time to streamline some styling
- Replace various styled `Card` components with one `PreferencesCard` component
- Remove legacy macOS build as a primary CLI option since engineers are no longer receiving non-ARM machines (the build is still available under "Show More")
- Increase Node heap size for storybook task to 6GB — I was seeing a lot of OOM failures on this task. Interestingly, I can reproduce the failure on my machine on Node v16.17, but it passes on v16.13 😮 so this may be related to the recent upgrade to the Node version in Evergreen. I'll circle back to a more permanent solution but for now increasing heap size unblocks us.
=> EVG-18143: Upgrade Side Nav

src/pages/spawn/spawnHost/SpawnHostTableActions.test.tsx, src/pages/spawn/spawnHost/SpawnHostTableActions.tsx, src/test_utils/index.tsx, src/utils/string/index.ts
EVG-17064
This PR removes the deprecated `document.execCommand` from Spruce. It also removes the `div` wrapper we had on the LG Tooltip in `SpawnHostTableActions` because it seems like the original problem went away.
I also exported `userEvent` from our test_utils file because that's how Parsley does it and I feel like the reason we aren't using it is because of the extra import we have to do... in a future ticket we can update this import statement in the test files.
- N/A
- Updated `SpawnHostTableActions.test.tsx`
=> EVG-17064: Remove document.execCommand usage

src/components/Spawn/spawnHostModal/utils.test.ts, src/components/Spawn/spawnHostModal/utils.ts
EVG-16156
This PR disables the Spawn button when the "Save Public Key" option is checked yet no public key name is provided. Note that I didn't modify the behavior for the Edit Spawn Host modal because it depends on [EVG-18014](https://jira.mongodb.org/browse/EVG-18014).
Currently we show a toast error which works fine, but the ticket seems to imply that we should disable the button instead. If the current behavior is preferred, I can just close this pull request.
Current behavior (show error toast):
New behavior (disable button):
- Added tests to `spawnHostModal/utils.test.ts`
=> EVG-16156: Disable spawn button if public key name is required and missing

src/gql/generated/types.ts, src/gql/mutations/deactivate-stepback-task.graphql, src/gql/mutations/deactivate-stepback-tasks.graphql, src/gql/mutations/index.ts, src/pages/projectSettings/tabs/GeneralTab/Fields/DeactivateStepbackTaskField.test.tsx, src/pages/projectSettings/tabs/GeneralTab/Fields/DeactivateStepbackTaskField.tsx, src/pages/projectSettings/tabs/GeneralTab/Fields/DeactivateStepbackTasksField.test.tsx, src/pages/projectSettings/tabs/GeneralTab/Fields/DeactivateStepbackTasksField.tsx, src/pages/projectSettings/tabs/GeneralTab/Fields/RepoConfigField.test.tsx, src/pages/projectSettings/tabs/GeneralTab/Fields/RepoConfigField.tsx, src/pages/projectSettings/tabs/GeneralTab/Fields/index.tsx, src/pages/projectSettings/tabs/GeneralTab/getFormSchema.tsx
EVG-17947
This PR makes it so that we call the new mutation resolver for deactivating stepback tasks. The new resolver requires both a build variant name and a task name, so these fields were added to the Deactivate Stepback Modal.
(Not sure about the wording here, and if we should possibly provide placeholders as an example.)
- Wrote test file `DeactivateStepbackTasksField.test.tsx`
- Changed `fireEvent` => `userEvent` in `RepoConfigField.test.tsx` just because it was close by
- [Patch with module](https://spruce.mongodb.com/version/63751e593e8e863310325cdd/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
- evergreen-ci/evergreen/pull/6068
=> EVG-17947: Modify stepback modal to require build variant and task

cypress/integration/projectSettings/project_settings.ts, src/pages/projectSettings/CreateDuplicateProjectButton.test.tsx
EVG-18333
- Updating all packages to run on the same version of LeafyGreen provider seems to have eliminated the unit test timeouts we were seeing
- Reintroduce unit tests and remove duplicate Cypress tests.
=> EVG-18333: Remove unit test skips

src/components/ProjectSelect/ProjectOptionGroup.tsx, src/pages/ProjectSettings.tsx
EVG-18272
This PR just adjusts some CSS. Users reported that because the `SideNav` was so small, it was hard to scroll and read through the projects in the `SearchableDropdown`.
(Screenshots are from beta to show that the changes will work with LeafyGreen updates.)
`SideNav`        |  `SearchableDropdown`
=> EVG-18272: Adjust CSS for project settings side nav

src/pages/version/taskDuration/TaskDurationRow.tsx, src/pages/version/taskDuration/TaskDurationTable.test.tsx, src/pages/version/taskDuration/TaskDurationTable.tsx
EVG-18449
- Updates to LeafyGreen Table prevent nested rows from being wrapped in parent components. To get around this limitation, render execution tasks directly as `Row` and `Cell` components. This should be fixed by LeafyGreen's table overhaul [LG-2231](https://jira.mongodb.org/browse/LG-2231). See [here](https://mongodb.slack.com/archives/CFFA5BS79/p1670426093909309?thread_ts=1651780191.082089&cid=CFFA5BS79) for more details.
- Add unit test
=> EVG-18449: Fix nested rows in task duration table

.evergreen.yml, scripts/wait-for-evergreen.sh
EVG-18555
This PR adds a script to wait for Evergreen (copied from Parsley) so that the Cypress tests will pass.
- e2e tests should pass.
=> EVG-18555: Add function to wait for Evergreen in e2e task

cypress/integration/spawn/host.ts, src/components/Spawn/spawnHostModal/getFormSchema.tsx, src/components/SpruceForm/Widgets/LeafyGreenWidgets.tsx, src/components/SpruceForm/__snapshots__/SpruceForm.stories.storyshot, src/pages/spawn/spawnHost/spawnHostButton/SpawnHostModal.tsx
EVG-14252
This PR prevents users from submitting the `Spawn host from task` form with both the setup script and project setup script checked. Only one of these values can be checked at a time.
It also removes a style I had applied to the `CheckboxWidget` which was incorrect.
Check setup script        |  Check project setup script
- Added test in `spawn/host.ts` (Cypress)
=> EVG-14252: Conditionally disable setup script and project setup script

src/constants/triggers.ts
[EVG-18546](https://jira.mongodb.org/browse/EVG-18546)
Right now, [evergreen converts](https://github.com/evergreen-ci/evergreen/blob/main/rest/data/subscription.go#L63) any incoming subscriptions that are a Version type and on an outcome to the family equivalent. Ideally, they should be sent in the family format. 
Existing tests
[6131](https://github.com/evergreen-ci/evergreen/pull/6131)
=> EVG-18546 Switch version outcomes to family 

src/gql/generated/types.ts, src/pages/projectSettings/tabs/PeriodicBuildsTab/getFormSchema.ts
EVG-18506
Merged https://github.com/evergreen-ci/evergreen/pull/6140/files to make the same change to legacy. This is to help users avoid mixing up periodic build and cron.
=> EVG-18506 clarify help text for periodic build

src/components/HistoryTable/HistoryTableIcon/index.tsx
EVG-18597
This PR makes it so that the text wraps in the tooltips on the history pages.
* Existing tests should pass.
=> EVG-18597: Wrap text in tooltips on history pages

src/pages/taskQueue/TaskQueueTable.tsx
EVG-18623
This PR makes it so that task links are wrapped and don't overflow into the next column of the Task Queue table.
Before        |  After
=> EVG-18623: Wrap task and version links on task queue page

src/components/styles/GlobalStyles.tsx
EVG-18710
- Apply [font smoothing](https://css-tricks.com/understanding-web-fonts-getting/#aa-font-smoothing), which is used by Atlas and I think improves legibility of our sans serif font.
- Preview on [beta](https://spruce-beta.corp.mongodb.com/)
=> EVG-18710: Add font-smoothing property

src/types/subscription.ts
I noticed this in a Slack conversation about the webhook notification. I think this is slightly misleading, since there's nothing specifically "Evergreen" about the webhook, in the same way that we write "Slack message", not "Evergreen Slack message".
=> EVG-18759 Fix webhook naming nit

src/components/Spawn/ExpirationField.tsx, src/pages/spawn/spawnVolume/spawnVolumeButton/SpawnVolumeModal.tsx, src/pages/spawn/spawnVolume/spawnVolumeButton/spawnVolumeModal/SizeSelector.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/UnmountButton.tsx, src/pages/spawn/spawnVolume/spawnVolumeTable/spawnVolumeTableActions/editButton/EditVolumeModal.tsx
EVG-15510
This PR replaces `antd` tooltips with LeafyGreen tooltips.
`UnmountButton` (before)        |  `UnmountButton` (after)
`ExpirationField` (before)        |  `ExpirationField` (after)
`SizeSelector` (before)        |  `SizeSelector` (after) - removed tooltip
- Existing tests should pass
=> EVG-15510: Replace antd tooltips with LeafyGreen tooltips

cypress/integration/projectSettings/constants.ts, cypress/integration/projectSettings/new_project.ts, cypress/integration/projectSettings/project_settings.ts, src/pages/projectSettings/CreateDuplicateProjectButton.tsx, src/pages/projectSettings/CreateProjectModal.test.tsx, src/pages/projectSettings/CreateProjectModal.tsx, src/pages/projectSettings/tabs/GeneralTab/Fields/MoveRepoModal.tsx, src/pages/projectSettings/tabs/GeneralTab/Fields/RepoConfigField.test.tsx, src/pages/projectSettings/tabs/GeneralTab/Fields/RepoConfigField.tsx, src/test_utils/index.tsx
EVG-17549
- Update Create Project and Move Project modals to use dropdown for selecting which GitHub org should be used.
=> EVG-17549: Use dropdown for project org selection

src/components/CodeChanges/CodeChanges.tsx, src/components/Table/TaskLink.tsx, src/pages/CommitQueue.tsx, src/pages/preferences/preferencesTabs/cliTab/NodeList.tsx, src/pages/task/executionDropdown/ExecutionSelector.tsx, src/pages/taskQueue/TaskQueueTable.tsx, src/pages/version/Metadata.tsx, src/utils/index.ts, src/utils/numbers/index.ts, src/utils/task.ts
[EVG-12490](https://jira.mongodb.org/browse/EVG-12490)
The commit queue position was displayed as 0 index, which didn't match how it was displayed in the commit queue itself. 
I added a function to convert zero to one index and used it in other parts of the codebase where it seems appropriate.
=> EVG-12490 Fix the commit queue position being zero index 

src/analytics/patches/useProjectPatchesAnalytics.ts, src/constants/routes.ts, src/gql/generated/types.ts, src/gql/queries/get-build-variants-for-task-name.graphql, src/gql/queries/get-commit-queue.graphql, src/gql/queries/get-last-mainline-commit.graphql, src/gql/queries/get-task-names-for-build-variant.graphql, src/gql/queries/project-patches.graphql, src/pages/CommitQueue.tsx, src/pages/Commits.tsx, src/pages/ProjectPatches.tsx, src/pages/TaskHistory.tsx, src/pages/VariantHistory.tsx, src/pages/commits/utils.test.ts, src/pages/commits/utils.ts, src/pages/projectSettings/Tabs.tsx, src/pages/projectSettings/tabs/GithubCommitQueueTab/GithubCommitQueueTab.tsx, src/pages/projectSettings/tabs/GithubCommitQueueTab/types.ts, src/pages/taskHistory/BuildVariantSelector.tsx, src/pages/taskHistory/ColumnHeaders.test.tsx, src/pages/taskHistory/ColumnHeaders.tsx, src/pages/variantHistory/ColumnHeaders.test.tsx, src/pages/variantHistory/ColumnHeaders.tsx, src/pages/variantHistory/TaskSelector.tsx
EVG-16434
This PR makes it so that we use the `projectIdentifier` param rather than `projectID` param for certain GraphQL queries.
- Patch with module ([link](https://spruce.mongodb.com/version/63d423fa32f4173896f6a32a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC))
- On staging
* evergreen-ci/evergreen/pull/6218
=> EVG-16434: Use projectIdentifier in place of projectID where appropriate

src/gql/generated/types.ts, src/pages/projectSettings/tabs/ProjectTriggersTab/getFormSchema.ts, src/pages/projectSettings/tabs/ProjectTriggersTab/transformers.ts, src/pages/projectSettings/tabs/ProjectTriggersTab/types.ts
EVG-18452
- Support omitting input for dateCutoff field within new project triggers since this field is nullable
- Also reorder inputs so that required fields appear before optional inputs
- Codegen will fail until the linked Evergreen PR is merged
https://github.com/evergreen-ci/evergreen/pull/6235
=> EVG-18452: Accept null input for dateCutoff

cypress/integration/myPatches/my_patches.ts, src/components/PatchesPage/index.tsx
EVG-18781
- Stringify query used to filter patch names so that numbers don't throw an error
- Update e2e test
=> EVG-18781: Safely search for patches by number

src/components/Table/TaskLink.tsx, src/constants/routes.ts, src/pages/task/taskTabs/__snapshots__/ExecutionTasksTable.stories.storyshot
EVG-18647
Execution tasks links now include an execution
=> EVG-18647 Include executions in exec tasks table links

package.json, src/pages/task/taskTabs/logs/LogTypes.tsx, yarn.lock
EVG-18676
This PR upgrades `html-react-parser`. Major changes include:
- bump domhandler from 4 to 5, html-dom-parser from 2 to 3
- Looked at the task logs, since this is the only place where the library is called
=> EVG-18676: Upgrade html-react-parser to v3.0.9

.evergreen.yml
[EVG-18584](https://jira.mongodb.org/browse/EVG-18584)
https://github.com/evergreen-ci/evergreen/pull/6285 will update the go version for evergreen to go1.19. In order for the e2e test to be able to build evergreen, it needs to be running a version of go greater than or equal to evergreen's version. I'd like to merge this before the evergreen PR so the e2e task doesn't break when the evergreen changes merge.
N/A
Hopefully the e2e test will pass on this PR 😄 
https://github.com/evergreen-ci/evergreen/pull/6285
=> EVG-18584 upgrade go version for evergreen

src/gql/generated/types.ts, src/gql/queries/get-host.graphql, src/pages/host/Metadata.tsx
EVG-5829
Exposes the AMI field for hosts that have one.
https://github.com/evergreen-ci/evergreen/pull/6296/files
=> EVG-5829 Conditionally render AMI for hosts

package.json, src/components/Header/NavDropdown.tsx, src/components/PatchActionButtons/ScheduleUndispatchedBaseTasks.tsx, src/components/PatchActionButtons/SetPatchPriority.tsx, src/components/PatchActionButtons/UnscheduleTasks.tsx, src/pages/task/actionButtons/SetTaskPriority.tsx, yarn.lock
EVG-18945
- Upgrade Menu, which fixes some of the weird properties we've seen around `as`
- The type of `MenuItem` has been restricted so it does not accept refs anymore. This is pretty easy to work around for the new Popconfirm by wrapping the menu items in a div containing the corresponding ref.
=> EVG-18945: Upgrade Menu

src/gql/fragments/baseTask.graphql, src/gql/generated/types.ts, src/pages/task/metadata/__snapshots__/Metadata.stories.storyshot, src/pages/task/metadata/index.tsx, src/pages/task/metadata/taskData.ts
EVG-19118
Surfaces a tasks build variant display name on the metadata panel
=> EVG-19118 Surface build variant display name on task metadata

src/pages/commits/utils.ts
EVG-17198
- Expand definition of "failed" for project health page to include system & setup failure statuses in order to show their icons.
=> EVG-17198: Include system/setup failure icons on project health page

src/components/HostStatusBadge/HostStatusBadge.stories.tsx, src/components/HostStatusBadge/__snapshots__/HostStatusBadge.stories.storyshot, src/components/HostStatusBadge/index.tsx, src/components/PodStatusBadge/PodStatusBadge.stories.tsx, src/components/PodStatusBadge/__snapshots__/PodStatusBadge.stories.storyshot, src/components/PodStatusBadge/index.tsx, src/gql/generated/types.ts, src/gql/queries/get-pod.graphql, src/gql/queries/index.ts, src/pages/container/EventsTable/index.tsx, src/pages/container/Metadata/index.tsx, src/pages/container/index.tsx, src/pages/host/index.tsx, src/pages/spawn/spawnHost/SpawnHostTable.tsx, src/types/pod.ts
EVG-19018
Creates some types used by pods for statuses
Create Pod page, fetch data and render metadata
Render boilerplate placeholder for pod events (Eternal loading skeleton)
localhost: 
localhost:3000/container/localhost
staging:
<stagingURL>/container/641ae3bd0f40259343a6ffec
=> EVG-19018 Create pod page

src/pages/projectSettings/tabs/AccessTab/getFormSchema.ts
EVG-19279
Add an extra line saying that admins will have access to create projects
saw that text changed
=> EVG-19279 Add help text to project settings admin section

src/gql/generated/types.ts, src/hooks/useQueryParam/useQueryParam.test.tsx, src/utils/queryString/stringifyQuery.test.ts, src/utils/queryString/stringifyQuery.ts
EVG-19228
This was caused by a parameter that removed empty strings. 
I'll make this change on parsley as well.
https://user-images.githubusercontent.com/4605522/229576634-cdc28bc0-97bc-4ae6-b326-362562b89d4e.mov
=> EVG-19228 Fix bug causing query params to be cleared when resizing mainline commits

src/gql/generated/types.ts, src/hooks/useQueryParam/index.ts, src/utils/queryString/stringifyQuery.test.ts, src/utils/queryString/stringifyQuery.ts
EVG-19304
Eliminates a render caused by `parseQueryString(searchParams.toString())` returning a new reference each time.
=> EVG-19304 Memoize useQueryParams return type

cypress/integration/version/routes.ts, src/gql/generated/types.ts
EVG-19322
- Since https://github.com/evergreen-ci/evergreen/pull/6382 introduces a version for patch `5e94c2dfe3c3312519b59480`, it is no longer unactivated. I added another patch there that is unactivated; we should now use it in the e2e test that checks that unactivated patches redirect to the commit queue.
- Verified locally on Cypress
https://github.com/evergreen-ci/evergreen/pull/6382
=> EVG-19322: E2E test references new unactivated CQ patch

src/components/SpruceForm/errors.ts, src/pages/projectSettings/tabs/GithubCommitQueueTab/getFormSchema.tsx
EVG-19272
- Update page schema to use a dependency so that Commit Queue fields that are not currently active/visible (e.g. when CQ is disabled) are not validated
- Improve error message for when commit queue is enabled
=> EVG-19272: Commit Queue settings page is error-free for new projects

src/pages/projectSettings/tabs/PluginsTab/getFormSchema.ts
EVG-19058
- Remove Build Baron language on plugins settings page since the settings are not necessarily BB related
=> EVG-19058: Remove build baron language on settings page

src/pages/task/metadata/index.tsx, src/pages/version/Metadata.tsx
EVG-19694
- Simplify metadata by omitting seconds in the sidebar. Hovering will show seconds via `title` attribute.
=> EVG-19694: Omit seconds from task and version metadata

src/pages/Version.tsx
EVG-19697
- Handle [BugSnag error](https://app.bugsnag.com/mongodb/evergreen/errors/6447d32e5c001f00099a5733?event_id=6447d32e00bbae55dec30000&i=sk&m=nw) by ensuring array is defined before accessing its length
=> EVG-19697: Ensure error/warning arrays exists before checking length

src/pages/task/metadata/index.tsx
EVG-19746
Sometimes we might show the `Host` label in a task metadata for container tasks that have not been assigned a podId yet. This adds an additional guard to ensure that a hostId also exists.
=> EVG-19746 Hide Host in side panel for container tasks

src/pages/task/taskTabs/buildBaronAndAnnotations/BuildBaron.test.tsx, src/pages/task/taskTabs/buildBaronAndAnnotations/FileTicketButton.tsx
EVG-19768 
This mutation being successful just means that we successfully created and enqueued the ticket creation notification, not that the ticket was successfully created (unfortunately) so wanted to tweak this wording. 
not adding a screenshot since this is tiny
Updated test
=> EVG-19768 fix misleading ticket creation text

src/components/Content/index.tsx, src/pages/version/TaskDuration.tsx, src/pages/version/Tasks.tsx
EVG-8291
Adds pagination and table controls to the bottom of the tasks and task duration tables.
Only show the options if the table has > 10 entries to avoid the "small sandwich" look.
I also noticed that the floating buttons on the bottom of the page tend to overlap with the pagination buttons at the bottom so I added transparency to them so they are less obtrusive.
=> EVG-8291 Add pagination to bottom of tasks tables

package.json, yarn.lock
EVG-19796
Removed the webpack dependency as we no longer use it. I checked each of our tools to make sure I didn't miss a spot. Local and production storybook. The dev server, prod builds, source map generation, codegen, local cypress, and CI headless cypress all still work.
=> EVG-19796 Remove unused webpack dependencies

cypress/integration/breadcrumbs.ts, src/analytics/breadcrumb/useBreadcrumbAnalytics.ts, src/components/Breadcrumbs/index.tsx, src/pages/Task.tsx, src/pages/task/Breadcrumbs/index.tsx
EVG-18646
This PR adds a breadcrumb for display tasks. Although a link to the display task exists in the Task Metadata panel, many users try to navigate with the breadcrumb and get frustrated when they get redirected to the entire patch.
- Added tests in `breadcrumbs.ts` (Cypress)
=> EVG-18646: Show breadcrumb for display tasks

src/gql/fragments/projectSettings/index.graphql, src/gql/fragments/projectSettings/projectEventSettings.graphql, src/gql/generated/types.ts, src/pages/projectSettings/CopyProjectModal.test.tsx, src/pages/projectSettings/tabs/EventLogTab/EventLogTab.test.tsx, src/pages/projectSettings/tabs/NotificationsTab/transformers.ts
EVG-19804
- Part 1 of changing the type of the `subscriptions` field from `ProjectSubscription` to `GeneralSubscription`: start querying `projectSubscriptions` instead so that we can change the type of `subscriptions` without breaking the UI.
=> EVG-19804: Query projectSubscriptions instead of subscriptions

package.json, yarn.lock
EVG-19903
Opted not to make the changes for env variable injection since that requires all env variables to be prefixed with vite_ and will be too risky for a simple dependency update. 
https://vitejs.dev/guide/env-and-mode.html#html-env-replacement
=> EVG-19903 Bump vite to latest

src/components/MetadataCard.tsx, src/pages/version/BuildVariants.tsx
EVG-19588
Makes the build variant card sticky so it is always viewable when scrolling through a large tasks table.
https://github.com/evergreen-ci/spruce/assets/4605522/8e9172b4-2daa-4f2a-879b-b63dce9b92e8
=> EVG-19588 Make build variant container sticky

src/gql/GQLWrapper.tsx, src/gql/fragments/projectSettings/index.graphql, src/gql/fragments/projectSettings/notifications.graphql, src/gql/fragments/projectSettings/projectEventSettings.graphql, src/gql/generated/types.ts, src/pages/projectSettings/CopyProjectModal.test.tsx, src/pages/projectSettings/tabs/EventLogTab/EventLogTab.test.tsx, src/pages/projectSettings/tabs/NotificationsTab/transformers.ts
EVG-19804
- Step 3 of deprecating the `ProjectSubscription` type: Stop making calls to `projectSubscriptions` fields, which use the deprecated type.
- Update caching rule to target `GeneralSubscription` instead of `ProjectSubscription`
=> EVG-19804: Fetch subscriptions instead of projectSubscriptions

cypress/integration/myPatches/patchCard/dropdown_menu.ts, src/components/PatchActionButtons/SetPatchVisibility.tsx, src/components/PatchActionButtons/index.tsx, src/components/PatchesPage/patchCard/DropdownMenu.tsx, src/gql/generated/types.ts, src/gql/mutations/index.ts, src/gql/mutations/set-patch-visibility.graphql
EVG-14033
Adds a button that will hide patches from appearing on the patches pages.
https://github.com/evergreen-ci/spruce/assets/4605522/df9a61e3-98e5-4f15-abef-9d99ba6dce17
https://github.com/evergreen-ci/evergreen/pull/6485
=> EVG-14033 Add button to hide a patch from the my patches pages

cypress/integration/version/unscheduled_patch/configure_patch.ts, src/gql/generated/types.ts, src/pages/configurePatch/ConfigurePatchCore.tsx
EVG-18757
Adds a cancel button for patches that have already been configured
=> EVG-18757 Allow canceling configuration for configured patches

cypress/integration/host/host_events.ts, src/pages/host/getHostEventString.tsx
EVG-17636
This PR adds failure descriptions and logs for the `HOST_CREATED`, `HOST_STARTED`, `HOST_STOPPED`, and `HOST_MODIFIED` events. I also removed some unnecessary leading & trailing whitespace from other events.
- Updated e2e tests (won't pass until Evergreen PR is merged). [Link to passing patch](https://spruce.mongodb.com/version/646f87c50ae606e58ab98def/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
- evergreen-ci/evergreen/pull/6549
=> EVG-17636: Expose more error logs in host events

src/constants/routes.ts, src/pages/projectSettings/Header.tsx, src/pages/projectSettings/HeaderButtons.tsx, src/pages/projectSettings/Tabs.tsx, src/pages/projectSettings/getTabTitle.ts, src/pages/projectSettings/index.tsx, src/pages/projectSettings/tabs/ViewsAndFiltersTab/ViewsAndFiltersTab.tsx, src/pages/projectSettings/tabs/ViewsAndFiltersTab/getFormSchema.ts, src/pages/projectSettings/tabs/ViewsAndFiltersTab/transformers.ts, src/pages/projectSettings/tabs/ViewsAndFiltersTab/types.ts, src/pages/projectSettings/tabs/index.tsx, src/pages/projectSettings/tabs/transformers.ts, src/pages/projectSettings/tabs/types.ts
EVG-19883
This PR creates an outline for the new Views & Filters tab. This is just a basic skeleton to unblock [EVG-19891](https://jira.mongodb.org/browse/EVG-19891) and [EVG-19892](https://jira.mongodb.org/browse/EVG-19892).
Since Views & Filters settings are not available at the repo level, I made it so that the tab does not show up on repos and the "Go to repo settings" link does not appear. (Also if you want the tabs in a different order let me know 🙏)
=> EVG-19883: Create outline for Views & Filters tab

cypress/integration/version/restart_modal.ts, src/components/TasksTable/__snapshots__/TasksTable.stories.storyshot, src/components/TasksTable/index.tsx, src/pages/task/taskTabs/__snapshots__/ExecutionTasksTable.stories.storyshot
EVG-20039 
@julianedwards  pointed out we use the labels `Patch/ Version Status` on the tasks table over a column that represents task statuses. This updates the verbiage to reflect that.
=> EVG-20039 Rename patch status to task status

cypress/integration/projectSettings/project_settings.ts, src/constants/triggers.ts, src/gql/generated/types.ts, src/pages/projectSettings/tabs/NotificationsTab/NotificationsTab.tsx
EVG-19628
- We were already prohibiting JIRA comments when tasks finish/fail, just needed to add JIRA issue creation to our validator.
=> EVG-19628: Prohibit JIRA comments when task finishes

src/gql/mocks/getUser.ts, src/hooks/tests/useBreadcrumbRoot.test.tsx, src/hooks/useGetUserPatchesPageTitleAndLink.ts
EVG-19732
This PR fixes the flaky `useBreadcrumbRoot` test. The test was having an issue dealing with the cache data, since the UserQuery's key field is `"userId"` rather than the default `"id"`. 
- The original test failure can be replicated locally, so I just ran the changes 20 times and made sure it never failed
=> EVG-19732: Fix flaky useBreadcrumbRoot test

src/components/PatchesPage/PatchCard.tsx, src/constants/patch.ts
EVG-20117
- Unlink github_pull_request as a user in the project patches page. Querying its patches takes a long time and they are not very useful. I also threw in parent_patch since it is similarly useless. The pages can still be accessed directly if so desired.
=> EVG-20117: Unlink GitHub PR user

src/pages/projectSettings/Tabs.tsx, src/pages/projectSettings/index.tsx, src/pages/projectSettings/tabs/ContainersTab/ContainersTab.tsx
EVG-17134
Now that we have multiple teams moving forward to onboard containers to their project,  we should allow for the exposure of the containers tab in Spruce. Given that only a select few beta testers are using this, and they are manually coordinating with us, I added a banner to make that clear.
=> EVG-17134: Expose container configurations to production

src/gql/fragments/projectSettings/projectEventSettings.graphql, src/gql/generated/types.ts, src/pages/projectSettings/tabs/EventLogTab/EventLogTab.test.tsx
EVG-20340
There was a slight oversight in that I just forgot to add it to the event log query. 🫠
If you do yarn prod, you should see the changes now.
=> EVG-20340: Show Views & Filters changes in event log

src/constants/externalResources.test.ts, src/constants/externalResources.ts
[EVG-19743](https://jira.mongodb.org/browse/EVG-19743)
RATE_AVG is more what users would want to see for the network metrics (per @opsnlops)
=> EVG-19743 RATE_AVG for network stats

src/gql/generated/types.ts, src/pages/projectSettings/tabs/GithubCommitQueueTab/getFormSchema.tsx
EVG-20304
Brian is unable to test on staging due to the current state of the GitHub app project. To get around this, he wants to use the `'github-merge-queue-sandbox'` project on production so that he can manually test the merge queue behavior.
I made a special check for that project so that Brian can test on production.
=> EVG-20304: Show merge queue section for 'github-merge-queue-sandbox' project

cypress/integration/version/task_filters.ts
EVG-20416
While working on https://github.com/evergreen-ci/evergreen/pull/6760 I noticed that one of the assertions we we were doing for task status was just looking at the length of the count instead of the actual count it self this fixes that assertion.
set-module-patch
https://spruce.mongodb.com/version/64bab2590ae606bb26511947/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
https://github.com/evergreen-ci/evergreen/pull/6760
=> EVG-20416 Fix task filter base task assertion

cypress/integration/projectSettings/project_settings.ts, src/constants/externalResources.ts, src/gql/generated/types.ts, src/pages/projectSettings/tabs/GithubCommitQueueTab/getFormSchema.tsx
EVG-20078
This PR removes the `isProduction()` flag from the merge queue section. Also removes the "beta" badge since the GitHub merge queue is out of beta.
For some reason, removing the beta badge caused the e2e tests to fail... the only way I could fix it was removing the invalid objects from the Radio widget. So the GitHub documentation link unfortunately had to be removed.
Also cleaned up some assertions.
=> EVG-20078: Expose merge queue section to production

cypress/integration/myPatches/my_patches.ts, package.json, src/components/PatchesPage/index.tsx, src/pages/task/taskTabs/FilesTables.tsx, yarn.lock
EVG-19037
- Upgrade `SearchInput` to the latest version
- We don't have any uses where it would make sense to use the `SearchResult`/typeahead features of this release. The files table, for example, pretty much already implements this behavior in the table itself.
- The ticket suggested converting some `TextInput` to `SearchInput` to remove unit test warnings. However, all of the existing `type="search"` inputs are not convertible because they either use a prop not offered by `SearchInput`, like `label` or `description`, or use icons in a way that's better suited to an empty input. Too bad because those warnings are annoying!
- Update Cypress tests because `SearchInput` now uses an `<input>` nested inside of a `<form>`, which is where the `data-cy` attribute is attached.
=> EVG-19037: Upgrade SearchInput

package.json, yarn.lock
EVG-19220
Upgrades `date-fns-tz`.
=> EVG-19220: Upgrade date-fns-tz to v2.0.0

cypress/integration/myPatches/patchCard/dropdown_menu.ts, cypress/integration/version/restart_modal.ts, package.json, src/components/TaskStatusFilters/index.tsx, src/components/VersionRestartModal/BuildVariantAccordion.tsx, src/components/VersionRestartModal/TaskStatusCheckbox.tsx, src/components/VersionRestartModal/TaskStatusCheckboxContainer.tsx, src/components/VersionRestartModal/VersionRestartModal.tsx, src/components/VersionRestartModal/VersionTasks.tsx, src/gql/generated/types.ts, yarn.lock
EVG-20126
This PR:
* Replaces `FixedSizeList` with `Virtuoso`
* Removes `react-window` from dependencies
* Removes styles that were unnecessary + updates styles
* Alphabetizes props
(Looks the same pretty much)
https://github.com/evergreen-ci/spruce/assets/47064971/9ad508e4-7807-4dbe-a256-d83c9d491851
- Updated e2e tests
=> EVG-20126: Use react-virtuoso in VersionRestartModal

.github/dependabot.yml
EVG-20601
Following up from the UI round table and updating Dependabot to only trigger once a week. 3 per repo should be a nice balance while not being overwhelming for whoever is on call.
=> EVG-20601 Update dependabot frequency to once a week

src/pages/spawn/spawnVolume/SpawnVolumeModal.test.tsx
EVG-20570
Increases timeout for this test so it doesn't fail. Ideally, we should figure out why these long timeouts are necessary/ avoidable but for now, this should suppress the noisy tests. 
Feel free to merge if I'm away when this is approved.
=> EVG-20570 Increase timeout on spawn volume test

cypress/integration/commit_queue.ts
EVG-20360
This test is failing on my Evergreen PR because it's trying to remove a patch from the Logkeeper commit queue, but the Logkeeper project does not have the commit queue enabled. There's already another test for removing from the commit queue in this same file, so I think it's okay to remove. It's not really meaningful to test it twice because the admin user is a superuser and can remove anything they want.
I'm planning to remove this patch data since it doesn't make sense that a patch is on a disabled commit queue.
* evergreen-ci/evergreen/pull/6946
=> EVG-20360: Remove redundant test from commit_queue.ts

src/pages/task/taskTabs/logs/logTypes/TaskEventLogLine.tsx, src/types/task.ts
EVG-20086
Added a new event for TASK_BLOCKED. There isn't any additional info in the event that can be used for the copy.
=> EVG-20086 Add task blocked event copy

src/components/SpruceForm/Widgets/LeafyGreenWidgets.tsx, src/components/SpruceForm/Widgets/types.ts, src/gql/fragments/projectSettings/projectTriggers.graphql, src/gql/generated/types.ts, src/pages/distroSettings/tabs/testData.ts, src/pages/projectSettings/tabs/ProjectTriggersTab/getFormSchema.ts, src/pages/projectSettings/tabs/ProjectTriggersTab/transformers.test.ts, src/pages/projectSettings/tabs/ProjectTriggersTab/transformers.ts, src/pages/projectSettings/tabs/ProjectTriggersTab/types.ts, src/pages/projectSettings/tabs/testData.ts
EVG-20650
Adding a "Unschedule Downstream Versions" checkbox to the project triggers field in Spruce now that resolvers are supported with this field on the Evergreen side
Tested in staging and modified unit tests here.
https://github.com/evergreen-ci/evergreen/pull/6968
=> EVG-20650 Add unscheduleDownstreamVersions to Spruce

src/hooks/index.ts, src/pages/task/taskTabs/logs/logTypes/LogMessageLine.tsx
EVG-20019
This fixes the log message timestamp format and updates the code to use the user timezone on the task page.
Tested in staging that the correct timestamp format and timezone are printed.
https://github.com/evergreen-ci/evergreen/pull/7018
=> EVG-20019: set log message timezone to user timezone and fix format

src/gql/GQLWrapper.tsx
EVG-20661
We were reporting GraphQL errors using a POJO instead of an `Error`. BugSnag will try to coerce the object into an error ([source](https://docs.bugsnag.com/platforms/javascript/reporting-handled-errors/#basic-usage)):
> If you provide something that is not an Error, such as a string or an object with name and message fields, notify will attempt to generate a stacktrace.
but Sentry does not, instead logging many events like this:
Using a proper `Error` fixes the issue. [Here](https://mongodb-org.sentry.io/issues/4480655275/?query=is%3Aunresolved+stack.function%3AlogErrorsLink&referrer=issue-stream&statsPeriod=14d&stream_index=1) is an example.
=> EVG-20661: Fix useless Sentry error

package.json, src/components/styles/Link.tsx, src/components/styles/index.ts, yarn.lock
EVG-20831
- Upgrade typography package
- Remove Link styling rules that are now present in the package itself
=> EVG-20831: Upgrade typography

src/gql/generated/types.ts, src/gql/mocks/taskData.ts, src/gql/queries/task-files.graphql, src/gql/queries/task.graphql, src/pages/task/TaskTabs.tsx, src/pages/task/taskTabs/FileTable/index.tsx, src/pages/task/taskTabs/FileTable/types.ts
EVG-20802
Updates all GraphQL queries that rely on `Task.TaskFiles` to now use `Task.Files`
N/A
=> EVG-20802 Migrate Task.TaskFiles usage to task.files

cypress/integration/preferences/notifications.ts
EVG-20818
Let me know if this PR should do more than this!!
- Remove `testIsolation` flag
- Fix warnings caused by chaining `clear()` and `type()`
- All tests in file passing
=> EVG-20818: Remove testIsolation for notification preferences

cypress/integration/commit_queue.ts
EVG-20820
Enables test isolation (use `beforeEach` where necessary & tweak some test descriptions).
=> EVG-20820: Enable test isolation in commit_queue.ts

cypress/integration/distroSettings/provider_section.ts, src/pages/distroSettings/tabs/ProviderTab/ProviderTab.tsx, src/pages/distroSettings/tabs/ProviderTab/getFormSchema.ts, src/pages/distroSettings/tabs/ProviderTab/schemaFields.ts, src/pages/distroSettings/tabs/ProviderTab/styles.ts, src/pages/distroSettings/tabs/ProviderTab/transformerUtils.ts, src/pages/distroSettings/tabs/ProviderTab/transformers.test.ts, src/pages/distroSettings/tabs/ProviderTab/transformers.ts, src/pages/distroSettings/tabs/ProviderTab/types.ts
EVG-19948
Adds support for EC2 On-Demand. It's very similar to the EC2 Fleet settings but doesn't have the fleet options section.
I moved stuff around with the `schema` & `uiSchema` in an attempt to make it easier to cross-reference them.
- Jest and Cypress tests
- evergreen-ci/evergreen/pull/7093
=> EVG-19948: Support EC2 On-Demand on provider settings page

src/components/ExpandedText/index.tsx, src/pages/task/metadata/Metadata.test.tsx, src/pages/task/metadata/index.tsx
EVG-19254
Users can set the value of `description` even if the task has succeeded ([docs](https://docs.devprod.prod.corp.mongodb.com/evergreen/Project-Configuration/Task-Runtime-Behavior#manually-set-task-status)), but we only show it if the task has failed. We should show the description if it exists.
I wasn't sure what verbiage to use since `description` can be set to anything of the user's choice (or it will default to the last run command), so if you have another suggestion feel free to let me know.
- Jest test
- Manually testing using the example link from the ticket
=> EVG-19254: Show details.description regardless of task status

src/components/Buttons/LoadingButton.stories.tsx, src/components/Buttons/LoadingButton.tsx, src/components/Settings/EventLog/EventLog.tsx, src/gql/generated/types.ts, src/pages/configurePatch/configurePatchCore/index.tsx, src/pages/task/actionButtons/previousCommits/index.tsx
EVG-20201
Updates the `LoadingButton` component to use the native props on the LG button.
=> EVG-20201: Use new LeafyGreen props in LoadingButton component

src/context/auth.tsx, src/gql/generated/types.ts
EVG-21018
This has been pretty noisy on the ops-alerts channel. Looks like we aren't catching any errors when the logout request happens.
=> EVG-21018 Catch logout errors

cypress/integration/distroSettings/permissions.ts, src/gql/generated/types.ts, src/gql/queries/user-distro-settings-permissions.graphql, src/pages/distroSettings/DeleteDistro/DeleteDistro.test.tsx, src/pages/distroSettings/NewDistro/NewDistroButton.test.tsx, src/pages/distroSettings/tabs/BaseTab.tsx
EVG-21009
- Make all forms disabled if user lacks edit permissions for a given distro. The save button would currently fail under these conditions, but making the page clearly view-only is more helpful than only notifying a user once their save fails.
- Limiting users who lack view permissions already works as designed
- Create, copy, and delete functionality is also appropriately gated
Disabled general settings page. You can see that the "New distro" button is omitted, and the delete button is disabled as well.
Existing functionality for a user who lacks view permissions:
=> EVG-21009: Make distro settings page readonly if user lacks edit permissions

cypress/integration/version/banners.ts, src/components/Icon/icons/index.tsx, src/constants/externalResources.ts, src/gql/generated/types.ts, src/gql/queries/mainline-commits.graphql, src/gql/queries/version.graphql, src/pages/Version.tsx, src/pages/commits/InactiveCommits/InactiveCommits.stories.tsx, src/pages/commits/InactiveCommits/InactiveCommits.test.tsx, src/pages/commits/InactiveCommits/index.tsx, src/pages/commits/ProjectHealth.stories.tsx, src/pages/version/Banners/IgnoredBanner/index.tsx, src/pages/version/Banners/index.tsx
EVG-20692
This PR makes it possible to tell if a version has been ignored on Spruce. Previously, there was no information about ignored versions at all.
`Banner` on Version page (I used a `Banner` because the LeafyGreen design docs say `Callout` should be reserved for [docs only](https://www.mongodb.design/component/callout/guidelines/#basic-usage)):
`Icon` in the inactive commits tooltip (this is the same icon on the legacy UI, but if it doesn't seem clear enough, I could also just write out `IGNORED` explicitly):
- Cypress tests
=> EVG-20692: Indicate if a version has been ignored

src/components/ErrorHandling/Sentry.tsx, src/components/ErrorHandling/initialize.test.ts
EVG-20308
- Add Sentry replay logging
- Note that replays can't currently be logged to the UI because the MongoDB's replay quota has been used up:
However, baas-ui was the main user of Replay and they introduced some changes 3 weeks ago that will hopefully alleviate this problem when the quota is refreshed https://github.com/10gen/baas-ui/pull/3455
- Viewed that Sentry attempted to send replays on staging (the requests were denied for the reason above)
=> EVG-20308: Add Sentry Replay

src/analytics/task/useTaskAnalytics.ts, src/pages/task/taskTabs/FileTable/GroupedFileTable/index.tsx
EVG-20808
Added an analytics tracking event for link clicks to open task files.
I've included a field that will be in a future PR be conditionally set if parsley is usable for that file. I'm hoping this can be used to gain insights if people are opting to use Parsley instead of the normal log viewer if it is available. 
Also logging the file name so that we can determine if some types of files are more likely to be used in Parsley than others. I'm hopeful this will allow us to gain some more insights into the use cases people like Parsley for.
n/a
=> EVG-20808 Add analytics events for task file link clicks.

src/pages/projectSettings/tabs/GithubCommitQueueTab/GithubCommitQueueTab.tsx
EVG-21038
updates message to tell users that they need a github app to use github features
local message
=> EVG-21038 Update webhook disabled message to mention the GitHub app

src/pages/task/taskTabs/testsTable/getColumnsTemplate.tsx
DEVPROD-920
- In the tests table, omit the base status badge if undefined. We already do this in the tasks table.
Before:
After:
=> DEVPROD-920: Conditionally render base status badge

src/constants/externalResources.test.ts, src/constants/externalResources.ts, src/pages/task/metadata/index.tsx
[DEVPROD-1759](https://jira.mongodb.org/browse/DEVPROD-1759)
If there's no end time given then Honeycomb will truncate the trace to only show the first 10 minutes. Giving the end time will help Honeycomb find the entire trace.
The Honeycomb docs for linking to a trace are [here](https://docs.honeycomb.io/working-with-your-data/direct-trace-links/).
No visible changes.
The end time was added in local evergreen (when I added a trace id to a task so the links would show).
=> DEVPROD-1759 add end time to the Honeycomb trace link

src/pages/preferences/preferencesTabs/notificationTab/ClearSubscriptions.tsx, src/pages/taskHistory/ColumnHeaders/index.tsx, src/pages/variantHistory/ColumnHeaders.tsx
DEVPROD-945
Fixes the toast text for clearing subscriptions.
Also downgrades the build variant / task history page errors to warnings. Added a rule to exclude `"warning"` level errors on Sentry so that they won't report to Slack and tested this on staging (the errors will still report on the Sentry dashboard, just not on Slack).
=> DEVPROD-945: Fix toast text for clearing subscriptions

src/constants/routes.ts, src/pages/task/ActionButtons.tsx, src/pages/task/taskTabs/testsTable/LogsColumn.tsx
DEVPROD-949
The show history button should only surface the history for the currently selected build variant
=> DEVPROD-949 Only surface build variant for current task on task history page

src/pages/projectSettings/tabs/PatchAliasesTab/getFormSchema.tsx, src/pages/projectSettings/tabs/PatchAliasesTab/transformers.test.ts, src/pages/projectSettings/tabs/PatchAliasesTab/transformers.ts, src/types/patch.ts
EVG-20704
Save patch trigger aliases with "success" status.
After deploying this change, the following operation will be run, first on staging, to convert all patch trigger aliases from "succeeded" to "success" status:
```
db.project_ref.updateMany(
{ "patch_trigger_aliases": { $exists: true } },
{ $set: { "patch_trigger_aliases.$[elem].status": "success" } },
{ arrayFilters: [ { "elem.status": "succeeded" } ] }
)
```
Validated DB command on local database, ensured that patch trigger aliases with either string function as expected.
=> EVG-20704: Save patch trigger aliases with new success status

cypress/integration/version/task_table.ts, src/gql/generated/types.ts
DEVPROD-359
The flake happens because the AntD table header sort button won't run the onClick handler when it's clicked on right after page load. Subsequent clicks work fine. I suspect this is an issue with how AntD attaches the callback because cypress selector successfully finds and clicks the sort button.
I tried to fix this before in https://github.com/evergreen-ci/spruce/pull/2079 by waiting on table UI state -- this worked well for the test table. An open question is why doesn't the fix for test table flake work and I'm actually not sure. It could be because something on the task page slows down AntD's ability to attach the listener or the loading icon dom update is inconsistent. 
I ran the test [200 times with waiting (0% flake)](https://spruce.mongodb.com/version/6542960d7742ae85f0 …
=> DEVPROD-359: Fix task_table sort button flake

src/gql/generated/types.ts, vite.config.ts
DEVPROD-934
Node 17 had a breaking change where it prefers IPv6 over IPv4. For localhost, IPv6 corresponds to `::1` and IPv4 corresponds to `127.0.0.1`.
Ultimately, I think this is a bug in Cypress described by [this issue](https://www.github.com/cypress-io/cypress/issues/25397). If you are using Node 17+, then running `yarn dev` will launch the server on `::1`. The issue describes a bug where if you call `cy.request()` before any `cy.visit()` calls, Cypress will "lock" itself into using `127.0.0.1`. This is bad because we're expecting `::1`. 
We run into this problem because we call [`cy.login()`](https://github.com/evergreen-ci/spruce/blob/8f2f1cdcff36d42d9edc43aa5d33a625cbe754c2/cypress/support/commands.ts#L64-L70) before all of our tests, which uses `cy.request()`. So we fulfill the …
=> DEVPROD-934: Allow Cypress to test against dev server on Node 17+

src/gql/generated/types.ts, src/gql/queries/base-version-and-task.graphql, src/pages/task/actionButtons/previousCommits/PreviousCommits.test.tsx, src/pages/task/actionButtons/previousCommits/index.tsx
DEVPROD-2234
We've been querying for task history using the version's project instead of the task's. This is often fine, but downstream tasks will use the wrong value for queries.
The bug was present in the previous version of the history selector, but was encountered a lot less often because a user would have to select "Go to last passing task" in the dropdown before the query ran.
Now, get the project identifier directly from the task.
- Update unit tests
=> DEVPROD-2234: Use correct project for querying task history

src/gql/fragments/projectSettings/index.graphql, src/gql/fragments/projectSettings/viewsAndFilters.graphql, src/gql/generated/types.ts, src/pages/projectSettings/Header.tsx, src/pages/projectSettings/Tabs.tsx, src/pages/projectSettings/index.tsx, src/pages/projectSettings/tabs/ViewsAndFiltersTab/ViewsAndFiltersTab.tsx, src/pages/projectSettings/tabs/ViewsAndFiltersTab/getFormSchema.ts, src/pages/projectSettings/tabs/ViewsAndFiltersTab/transformers.test.ts, src/pages/projectSettings/tabs/ViewsAndFiltersTab/transformers.ts, src/pages/projectSettings/tabs/ViewsAndFiltersTab/types.ts, src/pages/projectSettings/tabs/testData.ts, src/pages/projectSettings/tabs/types.ts
DEVPROD-948
- Allow users to save Parsley filters for repos
- For attached projects, show repo level filters in a disabled view
- I didn't add a "Move filters to repo" button like we have for variables; due to the usage rate of filters, this would be high effort with low impact. It's easy enough to copy the values over manually.
- ~~**Fun update:** because the `Project` resolver [applies the `includeRepo` flag](https://github.com/evergreen-ci/evergreen/blob/26a9c74fb94c21556995b848c5ae9fd6b4a20192/rest/data/project.go#L35), Parsley already handles applying repo-level filters without any further updates 🎉 you can try it out as part of reviewing this PR! I personally don't think there's any need to distinguish a project vs repo-level filter on the Parsley UI.~~ nvm 😢 small backend update …
=> DEVPROD-948: Allow setting Parsley filters for repos

src/components/CommitChartLabel/index.tsx
DEVPROD-2662
Thought it would be nice to see the exact time when you hover over the date on the project health page. We use this pattern in a few other spots as well.
=> DEVPROD-2662 Show exact time on hover of project health timestamp

cypress/integration/spawn/volume.ts, src/constants/cookies.ts, src/gql/generated/types.ts, src/pages/spawn/spawnVolume/SpawnVolumeTable.tsx, src/pages/spawn/spawnVolume/spawnVolumeTableActions/MigrateButton.tsx, src/types/spawn.ts
DEVPROD-357
Make tests atomic and individually runnable.
Remove New Feature Guide cue for spawn host migration since it's been around for a while now.
=> DEVPROD-357 Make spawn volume tests atomic

cypress/integration/version/action_buttons.ts, cypress/integration/version/restart_modal.ts, cypress/integration/version/routes.ts, cypress/integration/version/task_duration.ts, cypress/integration/version/unscheduled_patch/configure_patch.ts, src/gql/generated/types.ts
DEVPROD-358
Reenables commented-out tests and enables test isolation for configure patch tests
=> DEVPROD-358 Enable test isolation for remaining e2e tests 

cypress/integration/version/unscheduled_patch/configure_patch.ts, src/gql/generated/types.ts
DEVPROD-2597
Testing for patches not being able to be scheduled because of an empty github token is redundant now that we are not relying on that behavior now
https://github.com/evergreen-ci/evergreen/pull/7245
=> DEVPROD-2597 Delete test that fails due to no GitHub Token

src/components/SpruceForm/FieldTemplates/ArrayFieldTemplates/index.tsx, src/gql/generated/types.ts
DEVPROD-789
There was an odd spacing around array buttons because we always rendered the `<Placeholder>` component for an empty array, even if `placeholder` was not defined.
(These are just a few examples, you would be able to see it on any array form element.)
Before       |  After
Before     |  After
=> DEVPROD-789: Fix spacing bug in ArrayFieldTemplate

src/constants/externalResources.ts, src/gql/generated/types.ts
DEVPROD-2622
Swaps the pid used for linking to the jira ticket form from the Evergreen Project to the DEVPROD project
=> DEVPROD-2622 Update Jira ticket url to use DEVPROD project

src/pages/projectSettings/tabs/GithubCommitQueueTab/getFormSchema.tsx
DEVPROD-2253
- Mark Evergreen commit queue as deprecated
=> DEVPROD-2253: Mark Evergreen commit queue as deprecated

src/utils/string/index.ts, src/utils/string/string.test.ts
DEVPROD-820
`msToDuration` did not return any thing when the duration was below 1s so this corrects that and will return the ms unit.
Unit tests and tested on the task provided in the ticket
=> DEVPROD-820 Support displaying sub 1s durations on the tests table

src/constants/externalResources.test.ts, src/constants/externalResources.ts, src/gql/generated/types.ts, src/gql/queries/task.graphql, src/pages/task/metadata/Metadata.test.tsx, src/pages/task/metadata/index.tsx
[DEVPROD-1661](https://jira.mongodb.org/browse/DEVPROD-1661)
This ought to be the last of the PRs for this feature. This modifies the Honeycomb system metrics link to include disk stats for the disk names that were recorded when a task finished running.
N/A
[This query](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/kNsjoK2xqau?omitMissingValues) got generated for a task with a distro that had two disk devices configured.
https://github.com/evergreen-ci/evergreen/pull/7308
=> DEVPROD-1661 add disk metrics to honeycomb metrics link

src/gql/mocks/taskData.ts
[DEVPROD-1661](https://jira.mongodb.org/browse/DEVPROD-1661)
https://github.com/evergreen-ci/spruce/pull/2183 added a required field after https://github.com/evergreen-ci/spruce/pull/2188 added test data without the required field.
=> DEVPROD-1661 fix merge conflict

src/gql/mocks/taskData.ts, src/pages/configurePatch/configurePatchCore/index.tsx
DEVPROD-1134
Indicate project associated with patch on the configure tasks page
=> DEVPROD-1134: Add project link to configure patch page

src/gql/mocks/taskData.ts
My PR #2194 introduced a field that had already been added to the mock. This should fix the waterfall.
=> DEVPROD-1134 fix: Remove duplicate key

src/analytics/task/useTaskAnalytics.ts, src/gql/generated/types.ts, src/gql/queries/task.graphql, src/pages/task/metadata/index.tsx
DEVPROD-1122
This adds and propogates the "stepbackInfo" field in the Task struct to the task page's metadata card on the left hand side.
I explain in the video:
https://github.com/evergreen-ci/spruce/assets/64446617/52ce85dd-a9c9-4439-8ac5-9a34b89f1eee
Tested via staging. I considered some tests for it but I'm not sure if it is worth testing, since it is only links from the task data. I thought it might be more baggage to test it via cypress than the returns- but if the UI team feels otherwise, I won't hesitate to add them! I don't hold this opinion strongly, it's more so I don't want to add roi tests
[Evergreen PR](https://github.com/evergreen-ci/evergreen/pull/7341)
=> DEVPROD-1122 Add stepback information to task metadata

cypress/integration/projectSettings/notifications.ts, cypress/integration/subscription_modal.ts, src/components/Notifications/utils.test.ts, src/constants/triggers.ts, src/pages/preferences/preferencesTabs/notificationTab/useSubscriptionData.tsx, src/pages/projectSettings/tabs/NotificationsTab/getGqlPayload.test.ts, src/pages/projectSettings/tabs/NotificationsTab/transformers.test.ts, src/pages/projectSettings/tabs/NotificationsTab/transformers.ts, src/types/triggers.ts
DEVPROD-2227
This PR removes the usage of family triggers from the trigger definitions. 
It's too complicated to process which trigger we need to assign in the frontend. The notifications are already quite tricky and they would become even harder to understand if we added another layer of complexity. Instead, we will make up for it by doing some extra processing in the backend.
* evergreen-ci/evergreen/pull/7333
=> DEVPROD-2227: Remove family triggers from trigger definitions

src/constants/hosts.ts
DEVPROD-823
Removes the terminated status so it's no longer a filterable option on the hosts table since it is omitted by the underlying query
=> DEVPROD-823 Remove terminated status from hosts table filters

cypress/integration/projectSettings/plugins.ts, cypress/integration/task/test_table.ts, src/components/SpruceForm/Widgets/MultiSelect.tsx, src/pages/projectSettings/tabs/PluginsTab/PluginsTab.tsx, src/pages/projectSettings/tabs/PluginsTab/getFormSchema.tsx, src/pages/projectSettings/tabs/PluginsTab/transformers.test.ts, src/pages/projectSettings/tabs/PluginsTab/transformers.ts, src/pages/projectSettings/tabs/PluginsTab/types.ts, src/pages/projectSettings/tabs/testData.ts, src/pages/task/taskTabs/TestsTable.tsx, src/pages/version/Metadata.tsx, src/types/task.ts
DEVPROD-834
Allow projects to define multiple metadata links. Note that these links are for patch metadata, not task metadata. I put a limit of 5 metadata links after speaking to Annie; having a lot of links would make their patches look ugly so I'm hoping users will not need more than 5.
- Updated Cypress tests to save multiple metadata links
- Updated transformers test
=> DEVPROD-834: Allow projects to define multiple metadata links

.github/dependabot.yml
- I sometimes forget to review dependabot PRs on rotation because they don't show up in my inbox without a request from `evg-ui`. I figured adding the team would be helpful to flag these PRs, and then the rotator can change the reviewer to their own user.
- [Config file docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers)
=> Dependabot: Add team as reviewer

src/pages/projectSettings/tabs/GithubCommitQueueTab/getFormSchema.tsx
DEVPROD-781
Adding some clarity on how authorization is intended to work for git tags.
https://github.com/evergreen-ci/evergreen/pull/7414
=> DEVPROD-781: Add further detail to git tag text

src/gql/generated/types.ts, src/gql/queries/project-health-view.graphql, src/pages/commits/ViewToggle.tsx
DEVPROD-3935
We have logged nearly 7k events to sentry due to a failing permission check caused by the `projectHealthView` query consistently failing. It was trying to use the `ProjectSettings` query to fetch the `projectHealthView` state
Since most users don't have project settings access this query always fails and will consistently report an error.
This pr updates it so that we use a query that does not require the same permissions.
Since I am an admin it is difficult to test but since the query does not have a permissions check directive this should work.
=> DEVPROD-3935 Use correct query for project health view setting

src/components/Banners/SlackNotificationBanner.tsx, src/gql/generated/types.ts
DEVPROD-788
- Don't show Slack banner if user has already added their Slack username. I think if they've done so it's safe to assume they have used notifications and don't need prompting.
=> DEVPROD-788: Hide Slack banner more reliably

cypress/integration/distroSettings/general_section.ts, src/gql/generated/types.ts, src/gql/queries/distro.graphql, src/pages/distroSettings/tabs/GeneralTab/getFormSchema.ts, src/pages/distroSettings/tabs/GeneralTab/transformers.test.ts, src/pages/distroSettings/tabs/GeneralTab/transformers.ts, src/pages/distroSettings/tabs/GeneralTab/types.ts, src/pages/distroSettings/tabs/testData.ts
DEVPROD-3533
- Add field on general distro settings tab to mark distro as admin-only. This has no effect at present, but DEVPROD-3532 will hide these distros from user-facing menus, like distro selection when spawning hosts.
- Update unit and Cypress tests
https://github.com/evergreen-ci/evergreen/pull/7376
=> DEVPROD-3533: Add admin-only distro setting

src/components/VersionRestartModal/VersionRestartModal.tsx
DEVPROD-2707
This PR fixes a bug where restarting a downstream task via the VersionRestartModal would also restart all of the tasks in the parent patch.
The issue seems to stems from a change in restart logic made in Evergreen four months ago. When restarting a downstream task from the UI, the payload looks like the following:
```
{
// In the parent patch, restart nothing.
{ 
versionId: "123", 
taskIds: []
},
// In the child patch, restart "downstream-task".
{ 
versionId: "123", 
taskIds: ["downstream-task"]
}
}
```
However, according to the function that restarts versions, an empty `taskIds` array means that ALL completed tasks belonging to the version will be restarted. See screenshot below:
<br /><br />
The given payload means that `"downstream-task"` will be correctly restarted in the …
=> DEVPROD-2707: Avoid modifying parent patch when restarting downstream tasks

cypress/constants/index.ts, cypress/integration/distroSettings/permissions.ts, cypress/integration/nav_bar.ts, cypress/support/commands.ts, cypress/support/e2e.ts
DEVPROD-808
Edits the Cypress test to use the regular & privileged users for non-admin views. Some granularity was lost in the distro settings permission test but I'm kind of assuming that's okay.
* evergreen-ci/evergreen/pull/7531 (must be merged first)
=> DEVPROD-808: Use regular & privileged users to test non-admin views

src/components/ErrorHandling/Sentry.tsx, src/gql/GQLWrapper.tsx, src/utils/errorReporting.test.ts, src/utils/errorReporting.ts
DEVPROD-356
Added two new fields to GraphQL errors that should help with grouping in the app:
- Adding a [fingerprint](https://docs.sentry.io/platforms/javascript/usage/sdk-fingerprinting/) based on the operation name should force these errors to be grouped together. I've also appended the path to the fingerprint, which means that errors will only be grouped if the same field was the cause of the error. This is a little bit more aggressive than just grouping on operation name, but I think it will be helpful
- Adding operation name as a [tag](https://docs.sentry.io/platforms/javascript/guides/react/enriching-events/tags/) allows it to be searchable.
- The [event grouping information](https://mongodb-org.sentry.io/issues/4981024769/?environment=staging&project=4505211042856960&referrer=issue …
=> DEVPROD-356: Add Sentry grouping

cypress/integration/task/select_execution.ts, src/gql/generated/types.ts, src/pages/task/executionDropdown/ExecutionSelector.tsx
DEVPROD-4251
Fixes flaky test in `select_execution.ts`.
- The current test is flaky locally as well and fails about 50% of the time for me. I ran the test with these changes 10+ times and did not observe any failures
- Sorry that you can't see the files right now... that will be fixed by my other PR
=> DEVPROD-4251: Resolve flake in select_execution.ts

scripts/deploy/deploy.sh
DEVPROD-5097
The `deploy_to_prod` task succeeds even if this command fails. We should error and exit on failure.
- [Patch](https://spruce.mongodb.com/task/spruce_ubuntu2204_deploy_to_prod_patch_cde0efda6d1825120ab2d2ed4f91fc0331553359_65d8f3501e2d17c1f5afe208_24_02_23_19_34_47/logs?execution=0) where I made it fail
=> DEVPROD-5097: Prevent deploy_to_prod task from failing silently

src/pages/spawn/spawnHost/EditSpawnHostButton.tsx
DEVPROD-3326
- Use a `key` prop associated with the host ID to reset the modal's state when working with different hosts.
- Unable to reproduce as described in ticket with these changes applied
=> DEVPROD-3326: Reset edit host modal state

cypress/integration/projectSettings/not_defaulting_to_repo.ts, src/gql/generated/types.ts
DEVPROD-3495
This test fails with the unexpected error "user 'admin' does not have permission to view project 'spruce'." My hypothesis is that the reload in the prior test is introducing some race condition with the seeding data, since the test for `cy.dataCy("var-name-input").should("not.exist");` does not really verify that the page has finished loading. Adding a check for an element on the page may remove this race.
I've run a [passing patch](https://spruce.mongodb.com/task/spruce_ubuntu2204_e2e_test_patch_d5c630347001be8daa6166ce7c71ea9c67b88049_65e0f3232fbabecf79e6aa79_24_02_29_21_12_11/logs?sortBy=STATUS&sortDir=ASC) several times.
Since this addition is still correct and doesn't break anything, I think it makes sense to let it bake in production and see if further failures are …
=> DEVPROD-3495: Fix flaky git tag test

.evergreen.yml
DEVPROD-787
The Node installation can sometimes fail due to network errors. This PR retries the installation 5 times, with a 10 second waiting period between each try. I can raise the waiting time if you guys think it should be higher!
Will open Parsley PR after I get approval.
- Tested with a [patch](https://spruce.mongodb.com/version/65e0aaec3066150264d38aca/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) in which the loop instead prints a message and waits for 60 seconds in between attempts. You can see five messages for `"Running in the loop."` printed. The timestamps of these messages are kinda weird but I assume that's a symptom of how the agent processes output because the task takes as long as I would expect.
=> DEVPROD-787: Retry Node installation on CI

.yarnrc, scripts/deploy/utils/git/tag/constants.ts, scripts/deploy/utils/git/tag/tag-utils.ts, scripts/push-version.sh, src/gql/generated/types.ts
DEVPROD-5132
- Ahead of the monorepo merge, make Spruce's tags unique by using `spruce/vX.Y.Z`. The commit message has also been changed from "vX.Y.Z" to "spruce/vX.Y.Z"
- Remove references to remote URL. We can assume users have their upstream properly configured (and if they don't commands will fail, which is fine)
- Added a new git tag regex to Spruce's project settings. When this is merged I will delete the old one:
- Tested with my wifi off 🤣 the correct tag names were generated and git attempted to push to the correct place as part of the postversion script!
=> DEVPROD-5132: Make tags unique

scripts/deploy/utils/git/tag/tag-utils.test.ts
Fixes bug in DEVPROD-5132 (#2282)
- This test started failing after we introduced the first tag with the `spruce/v` prefix.
- Fix test by only having it check that the tag ends in X.Y.Z; when we start tagging Spruce and Parsley in the same codebase we won't have a consistent prefix so this is more future-proof.
=> DEVPROD-5132: Don't include tag prefix in test

src/pages/projectSettings/tabs/GeneralTab/getFormSchema.tsx
[DEVPROD-5336](https://jira.mongodb.org/browse/DEVPROD-5336)
This changes the conditional to include projects & projects attached to repos. The only type of projectref non-deletable (which is just hiding) is the repo project.
With the UI change, the button showed up correctly. The true test was testing it against the PR (linked below) that changes the route to allow for this behavior.
The following is using this change always (I tested without but it just doesn't show the button). The 'change' referenced below is the app PR/route change.
Before change:
After change:
There's [this](https://github.com/evergreen-ci/evergreen/pull/7591) PR in the app repository that I deployed and tested against. Separately I tested the app PR directly against the endpoint rather than spruce.
Here's the …
=> DEVPROD-5336 Allow projects to be deleted for projects not attached to a repo

cypress/integration/version/unscheduled_patch/configure_patch.ts, src/pages/configurePatch/configurePatchCore/ConfigureTasks/ConfigureTasks.test.tsx, src/pages/configurePatch/configurePatchCore/ConfigureTasks/index.tsx
DEVPROD-3088
Fixes bug where the "Select all" checkbox was only checking the plain text string and not the regex expression.
- Modified existing tests
=> DEVPROD-3088: Fix checkbox behavior for regex search on Configure Patch page

src/components/Table/BaseTable.tsx, src/components/Table/__snapshots__/BaseTable.stories.storyshot, src/pages/version/taskDuration/__snapshots__/TaskDurationTable.stories.storyshot
DEVPROD-5282
Wanted to fix this before [DEVPROD-1976](https://jira.mongodb.org/browse/DEVPROD-1976).
LeafyGreen just said to not use padding. I think padding might still be valuable for non-nested rows though, the test and files tables look kind of bad without it 😅
=> DEVPROD-5282: Remove padding for nested table rows

.evergreen.yml
DEVPROD-5665
Stops reporting e2e results to cypress cloud and also adds a step to attach logkeeper logs to the task files tab incase they are relevant.
=> DEVPROD-5665 Stop reporting e2e results to cypress cloud

package.json, src/components/EditableTagField/__snapshots__/EditableTagField.stories.storyshot, src/components/FilterBadges/__snapshots__/FilterBadges.stories.storyshot, src/components/HistoryTable/HistoryTableTestSearch/__snapshots__/HistoryTableTestSearch.stories.storyshot, src/components/PageSizeSelector/__snapshots__/PageSizeSelector.stories.storyshot, src/components/SpruceForm/__snapshots__/SpruceForm.stories.storyshot, src/components/Table/TableControl/__snapshots__/TableControl.stories.storyshot, src/components/TextInputWithGlyph/__snapshots__/TextInputWithGlyph.stories.storyshot, src/components/TextInputWithValidation/__snapshots__/TextInputWithValidation.stories.storyshot, src/components/TupleSelect/__snapshots__/TupleSelect.stories.storyshot, src/components/TupleSelectWithRegexConditional/__snapshots__/TupleSelectWithRegexConditional.stories.storyshot, src/pages/commits/__snapshots__/ProjectHealth.stories.storyshot, src/pages/configurePatch/configurePatchCore/__snapshots__/ConfigurePatchCore.stories.storyshot, yarn.lock
DEVPROD-5595
- Downgrade package to the same version on Parsley. This version does not use the `@leafygreen-ui/form-field` package which introduced the styling bugs.
The input on this page is styled correctly again:
=> DEVPROD-5595: Downgrade LG text input

scripts/deploy/deploy-production.ts, scripts/deploy/utils/git/tag/mock-tag-utils.ts, scripts/deploy/utils/git/tag/tag-utils.ts
DEVPROD-5788
Noticed that our deploy script no longer allows upgrading anything besides patch version. I'm going to upgrade the major version when we switch to a monorepo so we need this functionality. Will add to Parsley after!
Ran `createTagAndPush` command locally/wifi off to verify prompt works as designed
=> DEVPROD-5788: Allow upgrading to minor or major version

src/components/Header/Navbar.tsx
DEVPROD-5766
Updates the height of the HybridTreeIcon to preserve the aspect ratio of the original svg
=> DEVPROD-5766 Update HybridTree icon height
